### ISSUE TITLE
NullReference-Exception when using UseMassTransitInterop()

### ISSUE THREAD

**Issue by dreammaster38** [JasperFx/wolverine#1106]
**Describe the bug**
Configuring '.UseMassTransitInterop()' on an HostedEnvironment leads to a NullReference-Exception (pls. see below)

`
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Wolverine.RabbitMQ
  StackTrace:
   at Wolverine.RabbitMQ.Internal.RabbitMqEndpoint.MassTransitUri()
   at Wolverine.Runtime.Interop.MassTransit.MassTransitJsonSerializer..ctor(IMassTransitInteropEndpoint endpoint)
   at Wolverine.RabbitMQ.Internal.RabbitMqEndpoint.UseMassTransitInterop(Action`1 configure)
   at Wolverine.RabbitMQ.RabbitMqSubscriberConfiguration.<>c__DisplayClass1_0.<UseMassTransitInterop>b__0(RabbitMqEndpoint e)
   at Wolverine.Configuration.DelayedEndpointConfiguration`1.Wolverine.Configuration.IDelayedEndpointConfiguration.Apply()
   at Wolverine.Configuration.Endpoint.Compile(IWolverineRuntime runtime)
   at Wolverine.Transports.BrokerTransport`1.<InitializeAsync>d__22.MoveNext()
   at Wolverine.Runtime.WolverineRuntime.<startMessagingTransportsAsync>d__111.MoveNext()
   at Wolverine.Runtime.WolverineRuntime.<StartAsync>d__104.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0& )
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WolverineReceiverTest.Program.Main(String[] args) 
`

**To Reproduce**
Create a Console-Application with the following configuration (from the docs):

`
namespace WolverineReceiverTest;

using JasperFx.Core;
using Microsoft.Extensions.Hosting;
using Oakton;
using Oakton.Resources;
using Wolverine;
using Wolverine.RabbitMQ;
using Wolverine.Transports.Tcp;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = Host.CreateDefaultBuilder(args)
                     .UseWolverine(opts =>
                     {
                        opts.ApplicationAssembly = typeof(Program).Assembly;
                        opts.Discovery.IncludeAssembly(typeof(PongMessage).Assembly);
                        opts.UseRabbitMqUsingNamedConnection("rabbit")
                           .CustomizeDeadLetterQueueing(new DeadLetterQueue("errors", DeadLetterQueueMode.InteropFriendly))
                           .AutoProvision().AutoPurgeOnStartup()
                           .BindExchange("wolverine").ToQueue("wolverine")
                           .BindExchange("masstransit").ToQueue("masstransit");
                        opts.PublishAllMessages().ToRabbitExchange("masstransit")
                        // Tell Wolverine to make this endpoint send messages out in a format
                        // for MassTransit
                        .UseMassTransitInterop();
                     );
        var host = builder.Build();
        host.Run();
    }
}
`

**Expected behavior**
No NullReference exception

**Desktop (please complete the following information):**
 - OS: Windows 11, Version 10.0.26100
 - .Net 8, Version 8.0.403
 - Wolverine Fx Version 3.1.0
 - Wolverine Fx RabbitMq Version 3.1.0-rc.3

**Comment by dreammaster38** [comment]
Hi,

I found a workaround to avoid the NullReference-Exception:

` UseWolverine(opts =>
        {
            opts.ApplicationAssembly = GetType().Assembly;
            opts.Discovery.IncludeAssembly(typeof(PongMessage).Assembly);
            opts.UseRabbitMq(config =>
            {
                new ConnectionFactory() { VirtualHost = "/", HostName = "localhost" };
            })
                .CustomizeDeadLetterQueueing(new DeadLetterQueue("errors", DeadLetterQueueMode.InteropFriendly))
                .AutoProvision().AutoPurgeOnStartup()
                .BindExchange("wolverine").ToQueue("wolverine")
                .BindExchange("masstransit").ToQueue("masstransit");

            opts.PublishAllMessages().ToRabbitExchange("masstransit")

            // Tell Wolverine to make this endpoint send messages out in a format
            // for MassTransit
            .UseMassTransitInterop();

            opts.ListenToRabbitQueue("wolverine")

                // Tell Wolverine to make this endpoint interoperable with MassTransit
                .UseMassTransitInterop(mt =>
                {
                    // optionally customize the inner JSON serialization
                })
                .DefaultIncomingMessage<PongMessage>().UseForReplies();
        })`

You must configure the UseRabbitMq(configure => {...}) option with valid Connectionfactory settings. It seems that the default settings will not been set properly with an empty UseRabbitMq() option.
