### ISSUE TITLE
Node gets lost after some time from the Database (Balanced mode)

### ISSUE THREAD

**Issue by vasicvuk** [JasperFx/wolverine#1187]
**Describe the bug**

We have a Wolverine configured in "Balanced mode" and when the node starts it writes:

```
[2024-12-27 12:39:54Z INF] Found no other existing nodes, deciding to assume leadership in node 879
[2024-12-27 12:39:54Z DBG] 36690000-b560-16fc-156c-08dd267390d8: Enqueued for sending TryAssumeLeadership#36690000-b560-16fc-0156-08dd267390da to local://agents/
[2024-12-27 12:39:54Z INF] Wolverine assigned node id for envelope persistence is 879
[2024-12-27 12:39:54Z DBG] 36690000-b560-16fc-156c-08dd267390d8: Received TryAssumeLeadership#36690000-b560-16fc-0156-08dd267390da at local://agents/ from local://replies/
[2024-12-27 12:39:55Z INF] Started message listening at dbcontrol://36690000-b560-16fc-4522-08dd26738de1/
[2024-12-27 12:39:55Z DBG] 36690000-b560-16fc-156c-08dd267390d8: Started processing Wolverine.Runtime.Agents.IAgentCommand#36690000-b560-16fc-0156-08dd267390da
[2024-12-27 12:39:55Z INF] Node 879 successfully assumed leadership
[2024-12-27 12:40:08Z INF] Successfully started agent wolverinedb://default/ on Node 879
[2024-12-27 12:40:08Z INF] Successfully started agent wolverinedb://default/ on node 879
```

And we can see the record in the database that the node is registered:
![image](https://github.com/user-attachments/assets/315525f3-1bb3-4556-af4b-94e87105fc87)

But for some reason after some time Node just disappears, from the database:
![image](https://github.com/user-attachments/assets/2d9f5f6f-f8ae-40f3-80d5-94f7211452ee)

Even do the node is still running and writes logs such as this all the time:
```
[2024-12-27 12:50:30Z DBG] Successfully processed message Wolverine.Runtime.Agents.IAgentCommand#36690000-b560-16fc-a148-08dd26750bab from dbcontrol://36690000-b560-16fc-4522-08dd26738de1/
[2024-12-27 12:50:30Z DBG] null: Finished processing Wolverine.Runtime.Agents.IAgentCommand#36690000-b560-16fc-a148-08dd26750bab
[2024-12-27 12:50:31Z DBG] null: Received DatabaseOperationBatch#36690000-b560-16fc-bff2-08dd26750c44 at dbcontrol://36690000-b560-16fc-4522-08dd26738de1/ from 
[2024-12-27 12:50:31Z DBG] null: Started processing Wolverine.Runtime.Agents.IAgentCommand#36690000-b560-16fc-bff2-08dd26750c44
[2024-12-27 12:50:31Z DBG] Received message from dbcontrol://36690000-b560-16fc-4522-08dd26738de1/
[2024-12-27 12:50:31Z DBG] Successfully processed message Wolverine.Runtime.Agents.IAgentCommand#36690000-b560-16fc-bff2-08dd26750c44 from dbcontrol://36690000-b560-16fc-4522-08dd26738de1/
[2024-12-27 12:50:31Z DBG] null: Finished processing Wolverine.Runtime.Agents.IAgentCommand#36690000-b560-16fc-bff2-08dd26750c44
```

There is no error on health check failure or something else in the logs, it takes ~10 minutes for the node to disappear.

Another strange this is that `[wolverine_incoming_envelopes]` table is still being regularly written to and processed but with owner_id of 0:
![image](https://github.com/user-attachments/assets/eb68b448-ceb0-4098-a15e-c6fad4182feb)

And we had one case when it didn't process anything until the restart and writing the node in the database.

**Comment by vasicvuk** [comment]
It seems that the issue is when we run the Wolverine node locally using Solo mode, it deletes all the records from the Node table but it still processes the messages with an id of 0 node. Not sure how this should be handled.

**Comment by vasicvuk** [comment]
**UPDATE 2:**
I initially tested with 2.X Wolverine so I switched to latest 3.X version and the situation is the same only difference is that we have:

```
System.InvalidOperationException: There are no active nodes
   at Wolverine.Runtime.Agents.AssignmentGrid.DistributeEvenly(String scheme) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AssignmentGrid.cs:line 130
   at Wolverine.Runtime.Agents.NodeAgentController.EvaluateAssignmentsAsync(IReadOnlyList`1 nodes) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/NodeAgentController.EvaluateAssignments.cs:line 32
[2024-12-27 16:08:23Z ERR] Error trying to reevaluate agent assignments for 'wolverinedb' agents
System.InvalidOperationException: There are no active nodes
   at Wolverine.Runtime.Agents.AssignmentGrid.DistributeEvenly(String scheme) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AssignmentGrid.cs:line 130
   at Wolverine.RDBMS.DurabilityAgentFamily.EvaluateAssignmentsAsync(AssignmentGrid assignments) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/DurabilityAgentFamily.cs:line 70
```

in logs, but the behavior is still the same.

Seems like there is some need for re-registering active node, but not sure what are the cases of node removal are

**Comment by jeremydmiller** [comment]
If you're having any issues whatsoever running in balanced mode, absolutely go up to 3.*. That whole subsystem was redesigned. I'll read through the rest of what you've got going on. I'm not aware of any other existing problems like you're describing here. 

I do think you're a bit off base in how you're describing the "correct" behavior though when you're running as `Solo`. In that case, the existing node should -- and this is async -- pull in every incoming or outgoing envelope in those tables that has an owner_id = 0.

**Comment by jeremydmiller** [comment]
Actually, if y'all are running in `Solo` mode, the behavior you're describing sounds correct as designed.

**Comment by vasicvuk** [comment]
> Actually, if y'all are running in `Solo` mode, the behavior you're describing sounds correct as designed.

You didn't fully understand the problem. I have basically two running instances. Here is it again maybe more descriptive:

One on the environment in Balanced mode prepared for scaling.
Another on the development machine running Solo mode.

When the Solo mode is run the Node on the environment disappeared from the Database. And on the node on environment it gets mentioned exception.

When i shutdown the node on environment it does not return back the node ever until i restart the service, additionally it does process 0 messages even in Balanced mode and this behavior is both with latest released 3 version and 2 version.

**Comment by vasicvuk** [comment]
As mentioned in documentation solo mode is used only for Development purposes

**Comment by vasicvuk** [comment]
@jeremydmiller  will you reopen the issue or should i open another one?

**Comment by jeremydmiller** [comment]
There is absolutely **nothing** in the documentation that says you can use `Solo` to connect to the exact same message store database that a currently running `Balanced` application is using. Of course that's going to be an issue. I understand 100% what you're trying to do, and it's certainly not something that's supported or anticipated. This isn't a bug, it's a very large enhancement request. 

I don't think you're understanding that this is far too large of an ask for a freebie, drive by, OSS issue. As I said before, I'm happy to consider a consulting engagement to build some kind of new "remote debugging mode" enhancement for exactly what you're trying to do here, but this isn't going to happen as a purely free OSS core activity.
