### ISSUE TITLE
Cannot debug in Solo mode while there is a active Balanced instance

### ISSUE THREAD

**Issue by vasicvuk** [JasperFx/wolverine#1195]
**Describe the bug**

Here is the scenario:

We have an active shared development environment on k8s which runs .NET service with Wolverine in **Balanced** mode prepared for scaling.

The issue happens when one of the Developers wants to debug the problem locally, and run **Solo** instance on the development machine.

When the Solo mode is run on the Development machine, the Node on the shared (development) environment disappears from the Database. And on the node in the environment, it gets an exception:

```
System.InvalidOperationException: There are no active nodes
   at Wolverine.Runtime.Agents.AssignmentGrid.DistributeEvenly(String scheme) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AssignmentGrid.cs:line 130
   at Wolverine.Runtime.Agents.NodeAgentController.EvaluateAssignmentsAsync(IReadOnlyList`1 nodes) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/NodeAgentController.EvaluateAssignments.cs:line 32
[2024-12-27 16:08:23Z ERR] Error trying to reevaluate agent assignments for 'wolverinedb' agents
System.InvalidOperationException: There are no active nodes
   at Wolverine.Runtime.Agents.AssignmentGrid.DistributeEvenly(String scheme) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AssignmentGrid.cs:line 130
   at Wolverine.RDBMS.DurabilityAgentFamily.EvaluateAssignmentsAsync(AssignmentGrid assignments) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/DurabilityAgentFamily.cs:line 70
```

When I shut down the development Solo node, the environment Node does not return the node until I restart the service. Additionally, it processes 0 messages even in **Balanced** mode and the "Solo" mode instance is down.

We are using **Wolverine 3.5.1**

**Expectation**: I would expect to somehow be able to debug the application locally with the same Database but without affecting the workload coming to the environment on the server.

**Comment by jeremydmiller** [comment]
"Expectation: I would expect to somehow be able to debug the application locally with the same Database but without affecting the workload coming to the environment on the server."

I can't think of any possible way to solve that without a significant amount of work. Maybe I guess a new "cannot be the leader or take any assignements"

@vasicvuk To be blunt, I'm not willing to invest that much work for what I feel like is an unusual ask for free. We can talk about a support contract or a JasperFx engagement if you'd like, but I'm closing this otherwise. 

Happy to take pull requests if you just want to dive in, but it's going to be non-trivial.
