### ISSUE TITLE
Error while running Metrics collection of inbox and outbox

### ISSUE THREAD

**Issue by timdeschryver** [JasperFx/wolverine#136]
While going through the example on the website I encountered an issue in combination with MS SQL Server.
This can be reproduced with the `InMemoryMediator` example running with a MS SQL Server.

I don't know if this is different with other databases, but while starting the application I receive the following error while it's polling to read the incoming/outgoing messages.

https://github.com/JasperFx/wolverine/blob/4ba7b42fb927803b1223d69a504b61d2426b74c6/src/Persistence/Wolverine.SqlServer/Persistence/SqlServerMessageStore.cs#L69-L97

A potential fix could be to combine both queries with a `union all` ?
If you want I could create a PR with this fix.

```bash
fail: Wolverine.Runtime.WolverineRuntime[0]
      Error while running Metrics collection of inbox and outbox
      System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.
         at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
         at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)
         at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
         at Microsoft.Data.SqlClient.SqlCommand.BeginExecuteReaderInternal(CommandBehavior behavior, AsyncCallback callback, Object stateObject, Int32 timeout, Boolean inRetry, Boolean asyncWrite)
         at Microsoft.Data.SqlClient.SqlCommand.BeginExecuteReaderAsyncCallback(AsyncCallback callback, Object stateObject)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
         at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at Wolverine.SqlServer.Persistence.SqlServerMessageStore.FetchCountsAsync() in C:\Users\timde\dev\playgrounds\wolverine\src\Persistence\Wolverine.SqlServer\Persistence\SqlServerMessageStore.cs:line 95
         at Wolverine.SqlServer.Persistence.SqlServerMessageStore.FetchCountsAsync() in C:\Users\timde\dev\playgrounds\wolverine\src\Persistence\Wolverine.SqlServer\Persistence\SqlServerMessageStore.cs:line 100
         at Wolverine.SqlServer.Persistence.SqlServerMessageStore.FetchCountsAsync() in C:\Users\timde\dev\playgrounds\wolverine\src\Persistence\Wolverine.SqlServer\Persistence\SqlServerMessageStore.cs:line 100
         at Wolverine.RDBMS.Durability.MetricsCalculator.ExecuteAsync(IMessageDatabase database, IDurabilityAgent agent, IDurableStorageSession session) in C:\Users\timde\dev\playgrounds\wolverine\src\Persistence\Wolverine.RDBMS\Durability\MetricsCalculator.cs:line 31
         at Wolverine.RDBMS.Durability.DurabilityAgent.processActionAsync(IDurabilityAction action) in C:\Users\timde\dev\playgrounds\wolverine\src\Persistence\Wolverine.RDBMS\Durability\DurabilityAgent.cs:line 196
```

**Comment by jeremydmiller** [comment]
I'm generally leery of the UNION thing here. I think I'd vote to just be more aggressive with closing the first data reader instead of depending on the reader.DisposeAsync() to close it at the end of the method. 

Good catch, and thank you. But I'd very happily take a PR to address this if you're up for it, or I'm constantly in the code these days.

**Comment by timdeschryver** [comment]
That's a fair point 👍
I'm happy to contribute where I can, I should be able to open a PR later this week.

**Comment by jeremydmiller** [comment]
@timdeschryver Just let me know, happy to take a PR, and happy to deal with it if you can't get to it
