### ISSUE TITLE
Middleware compilation fails for multiple BeforeAsync called in one handler

### ISSUE THREAD

**Issue by dgrozenok** [JasperFx/wolverine#154]
Steps to reproduce:
1. Define 2 interfaces with one with the `Entity1Id` property and another with the `Entity2Id` property.
2. Define a command with both `Entity1Id` and `Entity2Id` and implement both of the interfaces from the step 1.
3. Implement a message handler for the command defined in step 2.
4. Define and register the middleware class with 2 `BeforeAsync` methods: one for handling the interface with `Entity1Id` and another for handling the interface with `Entity2Id`.

Expected Result: In the message handler both entities created by `BeforeAsync` methods are injected.

Actual Result: Compile error at run-time:

- `CS0128: A local variable or function named 'handlerContinuation' is already defined in this scope`

**Comment by Vertygo** [comment]
@dgrozenok that looks like a compiler error. Can you please share a sample code with us?

**Comment by dgrozenok** [comment]
Here is the project with the unit test reproducing the issue:
https://github.com/dgrozenok/WolverineDualMiddleware/blob/main/WolverineDualMiddlewareTest/DualMiddlewareTest.cs#L11

**Comment by dgrozenok** [comment]
Here is the error. You can see that the variable `var handlerContinuation` is defined twice in the generated function:

CS0128: A local variable or function named 'handlerContinuation' is already defined in this scope

Code:

// <auto-generated/>
#pragma warning disable

namespace Internal.Generated.WolverineHandlers
{
    // START: SampleCommandHandler335459866
    public class SampleCommandHandler335459866 : Wolverine.Runtime.Handlers.MessageHandler
    {


        public override System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
        {
            var sampleCommand = (WolverineDualMiddleware.SampleCommand)context.Envelope.Message;
            var sampleMiddleware = new WolverineDualMiddleware.SampleMiddleware();
            (var handlerContinuation, var sampleEntity1) = WolverineDualMiddleware.SampleMiddleware.Before((WolverineDualMiddleware.IEntity1Command)context.Envelope.Message);
            if (handlerContinuation == Wolverine.HandlerContinuation.Stop) return System.Threading.Tasks.Task.CompletedTask;
            (var handlerContinuation, var sampleEntity2) = WolverineDualMiddleware.SampleMiddleware.Before((WolverineDualMiddleware.IEntity2Command)context.Envelope.Message);
            if (handlerContinuation == Wolverine.HandlerContinuation.Stop) return System.Threading.Tasks.Task.CompletedTask;
            WolverineDualMiddleware.SampleHandler.Handle(sampleCommand, sampleEntity1, sampleEntity2);
            return System.Threading.Tasks.Task.CompletedTask;
        }

    }

    // END: SampleCommandHandler335459866
    
    
}


   at Wolverine.Runtime.Handlers.NoHandlerExecutor.InvokeAsync(Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout)
   at Wolverine.Runtime.MessageBus.InvokeAsync(Object message, CancellationToken cancellation, Nullable`1 timeout)
   at Wolverine.Tracking.WolverineHostMessageTrackingExtensions.<>c__DisplayClass4_0.<InvokeMessageAndWaitAsync>b__0(IMessageContext c)
   at Wolverine.Tracking.TrackedSession.ExecuteAndTrackAsync()
   at Wolverine.Tracking.TrackedSession.ExecuteAndTrackAsync()
   at Wolverine.Tracking.WolverineHostMessageTrackingExtensions.ExecuteAndWaitAsync(IHost host, Func`2 action, Int32 timeoutInMilliseconds)
   at WolverineDualMiddlewareTest.DualMiddlewareTest.TwoBeforeMethodsDefinedWork() in /Users/dgrozenok/RiderProjects/WolverineDualMiddleware/WolverineDualMiddlewareTest/DualMiddlewareTest.cs:line 14
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
