### ISSUE TITLE
RabbitMQ Transport Fails With: basic.ack caused a channel exception precondition_failed: unknown delivery tag

### ISSUE THREAD

**Issue by bhillis** [JasperFx/wolverine#189]
Using Wolverine 0.9.7

If a RabbitMQ queue has waiting messages when the consumer connects, the consumer can create an exception on the channel by sending an Ack for an invalid delivery tag.

This shows up later as the AlreadyClosedException from the RabbitMQ client.

```
     Error while trying to retry Envelope #018639ad-917a-4d1c-a244-c3a349976a30 (ExampleMessage) from WmsConnector.RouteGetter.Test.LoadTester to rabbitmq://queue/$shared.WmsConnector.RouteGetter.Test.LoadTester.ExampleMessage
      RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text='PRECONDITION_FAILED - unknown delivery tag 12', classId=60, methodId=80
         at RabbitMQ.Client.Impl.SessionBase.Transmit(OutgoingCommand& cmd)
         at RabbitMQ.Client.Impl.ModelBase.ModelSend(MethodBase method, ContentHeaderBase header, ReadOnlyMemory`1 body)
         at RabbitMQ.Client.Framing.Impl.Model.BasicAck(UInt64 deliveryTag, Boolean multiple)
         at RabbitMQ.Client.Impl.RecoveryAwareModel.BasicAck(UInt64 deliveryTag, Boolean multiple)
         at RabbitMQ.Client.Impl.AutorecoveringModel.BasicAck(UInt64 deliveryTag, Boolean multiple)
         at Wolverine.RabbitMQ.Internal.RabbitMqListener.Complete(UInt64 deliveryTag)
         at Wolverine.RabbitMQ.Internal.RabbitMqEnvelope.Complete()
         at Wolverine.RabbitMQ.Internal.RabbitMqChannelCallback.<>c.<.ctor>b__2_0(RabbitMqEnvelope e, CancellationToken _)
         at Wolverine.Util.Dataflow.LambdaItemHandler`1.ExecuteAsync(T message, CancellationToken cancellation)
         at Wolverine.Util.Dataflow.RetryBlock`1.executeAsync(Item item)
```

# Replication

To replicate, run the producer program first, let the queue build up and then run the consumer.

## Producer

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Test;
using Wolverine;
using Wolverine.RabbitMQ;

var builder = Host.CreateDefaultBuilder(args);

// Configuration options.
builder.UseWolverine(options =>
{
    // Configure RabbitMq.
    options.UseRabbitMq(rabbit =>
        {
            rabbit.HostName = "localhost";
            rabbit.Port = 15672;
            rabbit.UserName = "development";
            rabbit.Password = "development";
        })
        .DeclareExchange("messages.test", ex =>
        {
            ex.ExchangeType = ExchangeType.Topic;
            ex.IsDurable = true;
        })
        .AutoProvision();
    
    options.PublishMessage<ExampleMessage>().ToRabbitExchange("messages.test")
        .CustomizeOutgoingMessagesOfType<ExampleMessage>((envelope, message) =>
            envelope.TopicName = $"{typeof(ExampleMessage)}.{message.TestId}");
        
    options.Publish(x =>
    {
        x.Message<ExampleMessage>();
        x.ToRabbitTopics("messages.test", ex => { });
    });
    var queueName = $"$shared.{typeof(ExampleMessage)}";
    options.UseRabbitMq().BindExchange("messages.test", config =>
    {
        config.BindQueue(queueName, $"{typeof(ExampleMessage)}.#");
    });
    
});

builder.ConfigureServices(services => services.AddHostedService<MessageGeneratorService>());

var app = builder.Build();

app.Run();

namespace Test
{
    public class MessageGeneratorService : BackgroundService{
        private readonly IServiceProvider _serviceProvider;

        public MessageGeneratorService(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }
    
        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            const int workerCount = 1;
            var tasks = new List<Task>();
        
            for (var i = 0; i < workerCount; i++)
            {
                using var scope = _serviceProvider.CreateScope();
                var messageBus = scope.ServiceProvider.GetService<IMessageBus>();
                if (messageBus is null) throw new InvalidOperationException("IMessageBus could not be retrieved");
                tasks.Add(GenerateTaskAsync(messageBus, i, stoppingToken));
            }

            await Task.WhenAll(tasks);
        }

        public static async Task GenerateTaskAsync(IMessageBus bus, int taskId, CancellationToken ct)
        {
            var count = 0;
            var random = new Random(taskId);
            while (!ct.IsCancellationRequested)
            {
                var id = $"{taskId}:{count++}";
                await bus.InvokeAsync(new SendMessageCommand(id), ct);
                var waitDelay = random.Next(500, 1000);
                await Task.Delay(waitDelay, ct);
            }
        }
    }

    public record ExampleMessage(string TestId);

    public record SendMessageCommand(string Id);

    public static class SendMessageHandler
    {
        public static async Task Handle(SendMessageCommand command,
            ILogger<SendMessageCommand> logger,
            IMessageBus bus)
        {
            await bus.PublishAsync(new ExampleMessage(command.Id));
            logger.LogInformation("Sent message for tote {Id}", command.Id);
        } 
    }
}
```

## Consumer

```csharp
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Test;
using Wolverine;
using Wolverine.RabbitMQ;

var builder = Host.CreateDefaultBuilder(args);

// Configuration options.
builder.UseWolverine(options =>
{
    // Configure RabbitMq.
    options.UseRabbitMq(rabbit =>
        {
            rabbit.HostName = "localhost";
            rabbit.Port = 15672;
            rabbit.UserName = "development";
            rabbit.Password = "development";
        })
        .DeclareExchange("messages.test", ex =>
        {
            ex.ExchangeType = ExchangeType.Topic;
            ex.IsDurable = true;
        })
        .AutoProvision();
    
    var queueName = $"$shared.{typeof(ExampleMessage)}";
    options.ListenToRabbitQueue(queueName, q =>
    {
    });
        
    options.UseRabbitMq().BindExchange("messages.test", config =>
    {
        config.BindQueue(queueName, $"{typeof(ExampleMessage)}.#");
    });
    
});


var app = builder.Build();

app.Run();

namespace Test
{
    public static class ReceiveMessageHandler
    {
        public static async Task Handle(ExampleMessage command,
            ILogger<ExampleMessage> logger,
            IMessageBus bus)
        {
            logger.LogInformation("Received message {@Message}", command.TestId);
            var waitDelay = Random.Shared.Next(100, 200);
            await Task.Delay(waitDelay);
            logger.LogInformation("Finished {@Message}", command.TestId);
        }
    
    }
}
```

**Comment by jeremydmiller** [comment]
@bhillis,

First off thanks for taking the time to write this up, and I thought I had responded, so sorry for being slow here. I haven't been able to directly reproduce the issue locally yet -- but I can see it all freeze when I injected a chaos monkey kind of thing into the Rabbit MQ listeners. I'm probably not going to be able to get this into 0.9.9 today/tomorrow, but I'll follow up *some* kind of resiliency patch this week.

**Comment by jeremydmiller** [comment]
@bhillis I could never manage to exactly reproduce this, but was able to inject some chaos monkey stuff in there to make the delivery tag issue happen and just make Wolverine resilient enough to restart the connection to Rabbit MQ when it encounters that error.
