### ISSUE TITLE
Harden the ReleaseGlobalLockAsync() methods

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#219]
This came from https://github.com/JasperFx/wolverine/issues/173, but I'm seeing it occasionally in normal testing

I think this is a timing issue for when the app is being closed while it's trying to work:

```csharp
```
fail: Wolverine.Runtime.WolverineRuntime[0]
      Error while trying to stop DurabilityAgent
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'NpgsqlConnection'.
         at Npgsql.NpgsqlConnection.CreateCommand()
         at Npgsql.NpgsqlConnection.CreateDbCommand()
         at Weasel.Core.CommandExtensions.CreateCommand(DbConnection conn, String sql)
         at Wolverine.Postgresql.PostgresqlSettings.ReleaseGlobalLockAsync(DbConnection conn, Int32 lockId, CancellationToken cancellation, DbTransaction tx)
         at Wolverine.RDBMS.DurableStorageSession.ReleaseNodeLockAsync(Int32 lockId)
         at Wolverine.RDBMS.Durability.DurabilityAgent.StopAsync(CancellationToken cancellationToken)
```

**Comment by agross** [comment]
It's still an issue with 0.9.15.
