### ISSUE TITLE
Persisting sagas using EF to SQL Server throws System.InvalidOperationException

### ISSUE THREAD

**Issue by ksusac** [JasperFx/wolverine#252]
The following configuration throws System.InvalidOperationException:

```
using Microsoft.EntityFrameworkCore;
using Oakton;
using Wolverine;
using Wolverine.EntityFrameworkCore;
using Wolverine.SqlServer;

var builder = WebApplication.CreateBuilder(args);

builder.Host.ApplyOaktonExtensions();

builder.Host.UseWolverine(opt =>
{
    string connectionString = "Server=(localdb)\\MyInstance;Integrated Security=true;";

    opt.Services.AddDbContextWithWolverineIntegration<AppDbContext>(o =>
    {
        o.UseSqlServer(connectionString);
    });

    opt.PersistMessagesWithSqlServer(connectionString);
    opt.UseEntityFrameworkCoreTransactions();
    opt.Policies.UseDurableLocalQueues();
    opt.Policies.AutoApplyTransactions();
});

var app = builder.Build();

app.UseHttpsRedirection();

return await app.RunOaktonCommands(args);

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<ProcessOrderSaga> OrderSagas { get; set; }
}

public record OrderCreated(Guid Id);

public class ProcessOrderSaga : Saga
{
    public Guid Id { get; set; }

    public void Start(OrderCreated order)
    {
        Id = order.Id;
    }
}
```
The result is:
```
Wolverine.Runtime.WolverineRuntime: Error: Failed to start the Wolverine messaging

System.InvalidOperationException: Cannot determine the DbContext type for Message Handler for OrderCreated
   at Wolverine.EntityFrameworkCore.Codegen.EFCorePersistenceFrameProvider.DetermineDbContextType(IChain chain, IContainer container)
   at Wolverine.EntityFrameworkCore.Codegen.EFCorePersistenceFrameProvider.ApplyTransactionSupport(IChain chain, IContainer container)
   at Wolverine.Persistence.AutoApplyTransactions.Apply(IReadOnlyList`1 chains, GenerationRules rules, IContainer container)
   at Wolverine.Configuration.HandlerChainPolicy.Apply(IReadOnlyList`1 chains, GenerationRules rules, IContainer container)
   at Wolverine.Runtime.Handlers.HandlerGraph.Compile(WolverineOptions options, IContainer container)
   at Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken)
```
By adding DbContext as a parameter to Start method, it runs without exception, but by running `dotnet run -- describe` you get the following exception:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an
invocation.
     System.InvalidOperationException: Compilation failures!

     CS0136: A local or parameter named 'result_of_SaveChangesAsync' cannot be declared in this
     scope because that name is used in an enclosing local scope to define a local or parameter

     Code:

     // <auto-generated/>
     #pragma warning disable
     using Microsoft.EntityFrameworkCore;

     namespace Internal.Generated.WolverineHandlers
     {
         // START: OrderCreatedHandler2143142782
         public class OrderCreatedHandler2143142782 : Wolverine.Runtime.Handlers.MessageHandler
         {
             private readonly Microsoft.EntityFrameworkCore.DbContextOptions<AppDbContext>
     _dbContextOptions;

             public
     OrderCreatedHandler2143142782(Microsoft.EntityFrameworkCore.DbContextOptions<AppDbContext>
     dbContextOptions)
             {
                 _dbContextOptions = dbContextOptions;
             }



             public override async System.Threading.Tasks.Task
     HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken
     cancellation)
             {
                 var orderCreated = (OrderCreated)context.Envelope.Message;
                 await using var appDbContext = new AppDbContext(_dbContextOptions);
                 // Enroll the DbContext & IMessagingContext in the outgoing Wolverine outbox
     transaction
                 var envelopeTransaction =
     Wolverine.EntityFrameworkCore.WolverineEntityCoreExtensions.BuildTransaction(appDbContext,
     context);
                 await context.EnlistInOutboxAsync(envelopeTransaction);
                 // Added by EF Core Transaction Middleware
                 var result_of_SaveChangesAsync = await
     appDbContext.SaveChangesAsync(cancellation).ConfigureAwait(false);

                 // If we have separate context for outbox and application, the we need to manually
     commit the transaction
                 if (envelopeTransaction is
     Wolverine.EntityFrameworkCore.Internals.RawDatabaseEnvelopeTransaction rawTx) { await
     rawTx.CommitAsync(); }
                 var processOrderSaga = new ProcessOrderSaga();
                 processOrderSaga.Start(orderCreated, appDbContext);
                 if (!processOrderSaga.IsCompleted())
                 {
                     appDbContext.Add(processOrderSaga);
                     var result_of_SaveChangesAsync = await
     appDbContext.SaveChangesAsync(cancellation).ConfigureAwait(false);
                 }

             }

         }

         // END: OrderCreatedHandler2143142782


     }


       at Assembly JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(string code)
       at void JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly
          generatedAssembly, IServiceVariableSource services)
       at void JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file,
          GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
       at MessageHandler Wolverine.Runtime.Handlers.HandlerGraph.HandlerFor(Type messageType)
       at HandlerChain Wolverine.Runtime.Handlers.HandlerGraph.ChainFor(Type messageType)
       at Wolverine.Runtime.Routing.MessageRouterBase`1..ctor(WolverineRuntime runtime)
       at Wolverine.Runtime.Routing.MessageRouter`1..ctor(WolverineRuntime runtime,
          IEnumerable<MessageRoute> routes)
       at object System.RuntimeMethodHandle.InvokeMethod(object target, Void** arguments, Signature
          sig, bool isConstructor)
       at object System.Reflection.ConstructorInvoker.Invoke(object obj, IntPtr* args, BindingFlags
          invokeAttr)
  at object System.Reflection.ConstructorInvoker.Invoke(object obj, IntPtr* args, BindingFlags
     invokeAttr)
  at object System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder,
     object[] parameters, CultureInfo culture)
  at object System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, object[]
     args, CultureInfo culture)
  at object System.Activator.CreateInstance(Type type, params object[] args)
  at T JasperFx.Core.Reflection.TypeExtensions.CloseAndBuildAs<T>(Type openType, object
     ctorArgument1, object ctorArgument2, params Type[] parameterTypes)
  at IMessageRouter Wolverine.Runtime.WolverineRuntime.RoutingFor(Type messageType)
  at void Wolverine.Runtime.MessageSubscriptions.writeMessageRouting(IReadOnlyList<Type>
     messageTypes)
  at async Task Wolverine.Runtime.MessageSubscriptions.WriteToConsole()
  at async Task Oakton.Descriptions.DescribeCommand.WriteToConsole(IDescribedSystemPart[] parts)
  at async Task<bool> Oakton.Descriptions.DescribeCommand.Execute(DescribeInput input)
  at async Task<int> Oakton.CommandExecutor.execute(CommandRun run)
```
The versions I am running are:
Microsoft.EntityFrameworkCore.SqlServer v. 7.0.4
WolverineFx.EntityFrameworkCore v. 0.9.13
WolverineFx.SqlServer v. 0.9.13

**Comment by jeremydmiller** [comment]
Okay, there were multiple issues, still working on it:)

**Comment by ksusac** [comment]
No problem :) Thank you for the fast fix.
