### ISSUE TITLE
Length of 'received_at' column wolverine_incoming_envelopes

### ISSUE THREAD

**Issue by afmuller** [JasperFx/wolverine#315]
Wolverine version: 0.9.16

On Entity Framework (SQL Server), I am running into SqlException exceptions due to truncation of the 'received_at' column in the 'wolverine_incoming_envelopes' table - due to the length of my namespaces (exceeds the allowed 100 characters).

Is there a way to extend the size of this column in the database?

Thank!

See full exception below:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated in table 'KsbCourier.dbo.wolverine_incoming_envelopes', column 'received_at'. Truncated value: 'local://ksb.couriermgmtsystem.appl
ication.features.usernotifications.commands.insertusernotification'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEnc
rypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__208_1(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Weasel.Core.CommandExtensions.ExecuteOnce(DbCommand command, CancellationToken cancellation)
   at Weasel.Core.CommandExtensions.ExecuteOnce(DbCommand command, CancellationToken cancellation)
   at Wolverine.RDBMS.MessageDatabase`1.StoreIncomingAsync(Envelope envelope)
   at Wolverine.Runtime.MessageContext.flushScheduledMessagesAsync()
   at Wolverine.Runtime.MessageContext.FlushOutgoingMessagesAsync()
   at Wolverine.Runtime.MessageSucceededContinuation.ExecuteAsync(IEnvelopeLifecycle lifecycle, IWolverineRuntime runtime, DateTimeOffset now, Activity activity)

```

**Comment by afmuller** [comment]
For reference, this is the database scheme being created:

![image](https://user-images.githubusercontent.com/15875383/233571667-8cda8b0c-ec78-450a-8b51-c29a716eed6e.png)

**Comment by jeremydmiller** [comment]
@afmuller I'm moving all the string columns to at least 250. It *should* be able to apply the database changes on startup if you use that `AddResourceSetupOnStartup` approach.

I've gotten lazy from using Postgresql w/ or w/o Marten where you generally don't have to specify the length of string fields.
