### ISSUE TITLE
Bi-directional dependency error on startup after upgrading from `0.9.16` to `0.9.17` (and `0.9.18`)

### ISSUE THREAD

**Issue by lucaswalter** [JasperFx/wolverine#349]
I currently have a project which uses wolverine at the application layer and marten as the event store. Prior to upgrading I was on `0.9.16` for all wolverine / marten dependencies  and the application was working as expected.

After upgrading (just the `WolverineFx.*` dependencies), I get this error on startup:
```
System.InvalidOperationException: Detected some kind of bi-directional dependency while trying to discover and plan a missing service registration. Examining types: System.Byte, 
Steambase.Application.Features.Packages.Events.SteamPackage.PackageFetched, Steambase.Data.Domain.Common.Models.SteamKeyValue
```

**Full Stack Trace:**
```
System.InvalidOperationException: Detected some kind of bi-directional dependency while trying to discover and plan a missing service registration. Examining types: System.Byte, Steambase.Application.Features.Packages.Events.SteamPackage.PackageFetched, Steambase.Data.Domain.Common.Models.SteamKeyValue
   at Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.addMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.ResolveFamily(Type serviceType)
   at Lamar.ServiceGraph.FindAll(Type serviceType)
   at Lamar.IoC.Enumerables.ListInstance`1.createPlan(ServiceGraph services)
   at Lamar.IoC.Instances.Instance.CreatePlan(ServiceGraph services)
   at Lamar.ServiceGraph.planResolutionStrategies()
   at Lamar.ServiceGraph.buildOutMissingResolvers()
   at Lamar.ServiceGraph.addMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.ResolveFamily(Type serviceType)
   at Lamar.ServiceGraph.FindDefault(Type serviceType)
   at Lamar.IoC.Instances.ConstructorInstance.explainWhyConstructorCannotBeUsed(Type implementationType, ConstructorInfo constructor, ServiceGraph services)
   at Lamar.IoC.Instances.ConstructorInstance.DetermineConstructor(ServiceGraph services, String& message)
   at Lamar.ServiceGraph.CouldBuild(Type concreteType, String& message)
   at Lamar.ConcreteFamilyPolicy.Build(Type type, ServiceGraph serviceGraph)
   at Lamar.ServiceGraph.<>c__DisplayClass66_0.<TryToCreateMissingFamily>b__1(IFamilyPolicy x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at JasperFx.Core.EnumerableExtensions.FirstValue[TItem,TReturn](IEnumerable`1 enumerable, Func`2 func)
   at Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.addMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.ResolveFamily(Type serviceType)
   at Lamar.ServiceGraph.FindDefault(Type serviceType)
   at Lamar.IoC.Instances.ConstructorInstance.explainWhyConstructorCannotBeUsed(Type implementationType, ConstructorInfo constructor, ServiceGraph services)
   at Lamar.IoC.Instances.ConstructorInstance.DetermineConstructor(ServiceGraph services, String& message)
   at Lamar.ServiceGraph.CouldBuild(Type concreteType, String& message)
   at Lamar.ConcreteFamilyPolicy.Build(Type type, ServiceGraph serviceGraph)
   at Lamar.ServiceGraph.<>c__DisplayClass66_0.<TryToCreateMissingFamily>b__1(IFamilyPolicy x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at JasperFx.Core.EnumerableExtensions.FirstValue[TItem,TReturn](IEnumerable`1 enumerable, Func`2 func)
   at Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.addMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.ResolveFamily(Type serviceType)
   at Lamar.Diagnostics.QueryModel.For(Type type)
   at Wolverine.Configuration.Chain`2.serviceDependencies(IContainer container, IReadOnlyList`1 stopAtTypes)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Wolverine.Marten.Persistence.Sagas.MartenPersistenceFrameProvider.CanApply(IChain chain, IContainer container)
   at Wolverine.Persistence.AutoApplyTransactions.<>c__DisplayClass0_1.<Apply>b__1(IPersistenceFrameProvider x)
   at System.Linq.Enumerable.WhereListIterator`1.ToArray()
   at Wolverine.Persistence.AutoApplyTransactions.Apply(IReadOnlyList`1 chains, GenerationRules rules, IContainer container)
   at Wolverine.Configuration.HandlerChainPolicy.Apply(IReadOnlyList`1 chains, GenerationRules rules, IContainer container)
   at Wolverine.Runtime.Handlers.HandlerGraph.Compile(WolverineOptions options, IContainer container)
   at Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken)
[red]ERROR:[/]System.InvalidOperationException: Detected some kind of bi-directional dependency while trying to discover and plan a missing service registration. Examining types: System.Byte, 
Steambase.Application.Features.Packages.Events.SteamPackage.PackageFetched, Steambase.Data.Domain.Common.Models.SteamKeyValue
  at ServiceFamily Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)                                                                                  
  at ServiceFamily Lamar.ServiceGraph.addMissingFamily(Type serviceType)                                                                                          
  at ServiceFamily Lamar.ServiceGraph.ResolveFamily(Type serviceType)                                                                                             
  at Instance[[]] Lamar.ServiceGraph.FindAll(Type serviceType)                                                                                                    
  at IEnumerable<Instance> Lamar.IoC.Enumerables.ListInstance`1.createPlan(ServiceGraph services)                                                                 
  at void Lamar.IoC.Instances.Instance.CreatePlan(ServiceGraph services)                                                                                          
  at void Lamar.ServiceGraph.planResolutionStrategies()                                                                                                           
  at void Lamar.ServiceGraph.buildOutMissingResolvers()                                                                                                           
  at ServiceFamily Lamar.ServiceGraph.addMissingFamily(Type serviceType)                                                                                          
  at ServiceFamily Lamar.ServiceGraph.ResolveFamily(Type serviceType)                                                                                             
  at Instance Lamar.ServiceGraph.FindDefault(Type serviceType)                                                                                                    
  at string Lamar.IoC.Instances.ConstructorInstance.explainWhyConstructorCannotBeUsed(Type implementationType, ConstructorInfo constructor, ServiceGraph services)
  at ConstructorInfo Lamar.IoC.Instances.ConstructorInstance.DetermineConstructor(ServiceGraph services, out string message)                                      
  at bool Lamar.ServiceGraph.CouldBuild(Type concreteType, out string message)                                                                                    
  at ServiceFamily Lamar.ConcreteFamilyPolicy.Build(Type type, ServiceGraph serviceGraph)                                                                         
  at ServiceFamily Lamar.ServiceGraph.<>c__DisplayClass66_0.<TryToCreateMissingFamily>b__1(IFamilyPolicy x)                                                       
  at bool System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()                                                                                                 
  at TSource System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)                              
  at TSource System.Linq.Enumerable.FirstOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)                                           
  at TReturn JasperFx.Core.EnumerableExtensions.FirstValue<TItem,TReturn>(IEnumerable<TItem> enumerable, Func<TItem, TReturn> func)                               
  at ServiceFamily Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)                                                                                  
  at ServiceFamily Lamar.ServiceGraph.addMissingFamily(Type serviceType)                                                                                          
  at ServiceFamily Lamar.ServiceGraph.ResolveFamily(Type serviceType)                                                                                             
  at Instance Lamar.ServiceGraph.FindDefault(Type serviceType)                                                                                                    
  at string Lamar.IoC.Instances.ConstructorInstance.explainWhyConstructorCannotBeUsed(Type implementationType, ConstructorInfo constructor, ServiceGraph services)
  at ConstructorInfo Lamar.IoC.Instances.ConstructorInstance.DetermineConstructor(ServiceGraph services, out string message)                                      
  at bool Lamar.ServiceGraph.CouldBuild(Type concreteType, out string message)                                                                                    
  at ServiceFamily Lamar.ConcreteFamilyPolicy.Build(Type type, ServiceGraph serviceGraph)                                                                         
  at ServiceFamily Lamar.ServiceGraph.<>c__DisplayClass66_0.<TryToCreateMissingFamily>b__1(IFamilyPolicy x)                                                       
  at bool System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()                                                                                                 
  at TSource System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)                              
  at TSource System.Linq.Enumerable.FirstOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)                                           
  at TReturn JasperFx.Core.EnumerableExtensions.FirstValue<TItem,TReturn>(IEnumerable<TItem> enumerable, Func<TItem, TReturn> func)                               
  at ServiceFamily Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)                                                                                  
  at ServiceFamily Lamar.ServiceGraph.addMissingFamily(Type serviceType)                                                                                          
  at ServiceFamily Lamar.ServiceGraph.ResolveFamily(Type serviceType)                                                                                             
  at IServiceFamilyConfiguration Lamar.Diagnostics.QueryModel.For(Type type)                                                                                      
  at IEnumerable<Type> Wolverine.Configuration.Chain`2.serviceDependencies(IContainer container, IReadOnlyList<Type> stopAtTypes)                                 
  at bool System.Linq.Enumerable.ConcatIterator`1.MoveNext()                                                                                                      
  at bool System.Linq.Enumerable.DistinctIterator`1.MoveNext()                                                                                                    
  at bool System.Linq.Enumerable.Any<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)                                                         
  at bool Wolverine.Marten.Persistence.Sagas.MartenPersistenceFrameProvider.CanApply(IChain chain, IContainer container)                                          
  at bool Wolverine.Persistence.AutoApplyTransactions.<>c__DisplayClass0_1.<Apply>b__1(IPersistenceFrameProvider x)                                               
  at TSource[[]] System.Linq.Enumerable.WhereListIterator`1.ToArray()                                                                                             
  at void Wolverine.Persistence.AutoApplyTransactions.Apply(IReadOnlyList<IChain> chains, GenerationRules rules, IContainer container)                            
  at void Wolverine.Configuration.HandlerChainPolicy.Apply(IReadOnlyList<HandlerChain> chains, GenerationRules rules, IContainer container)                       
  at void Wolverine.Runtime.Handlers.HandlerGraph.Compile(WolverineOptions options, IContainer container)                                                         
  at async Task Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken)                                                                
  at async Task Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)                                                        
  at async Task<bool> Oakton.Commands.RunCommand.Execute(RunInput input)                                                                                          
  at async Task<int> Oakton.CommandExecutor.execute(CommandRun run)
```

After tinkering with types mentioned in the error message, `SteamKeyValue` seems to be the root of the issue. This is a common model which gets passed through multiple messages in my system and is a property on multiple events which get saved to the event store.

The `Children` property on this object references itself in a list. If I remove `Children` from this object, the startup error no longer happens, but it would be ideal if I could keep it as is since this object is modeled the same as its "source of truth" data which I fetch from an external system.

```csharp
public record SteamKeyValue(
    string? Name,
    string? Value,
    List<SteamKeyValue> Children
);
```

---

**Working Dependency Versions**
- WolverineFx -> `0.9.16`
- WolverineFx.FluentValidation -> `0.9.16`
- WolverineFx.Marten -> `0.9.16`
- Marten -> `5.11.0`

**Broken Dependency Versions**
- WolverineFx -> `0.9.17` & `0.9.18`
- WolverineFx.FluentValidation -> `0.9.17` & `0.9.18`
- WolverineFx.Marten -> `0.9.17` & `0.9.18`
- Marten -> `5.11.0` & `6.0.0`

**Comment by jeremydmiller** [comment]
Blech, you're going to have to tell me more about the custom type: Steambase.Application.Features.Packages.Events.SteamPackage.PackageFetched, Steambase.Data.Domain.Common.Models.SteamKeyValue

What is that, what's depending on it? Something that a Wolverine handler depends on depends on that for a constructor function.

**Comment by lucaswalter** [comment]
@jeremydmiller Of course, here is a repository with the most minimal repro I was able to create: https://github.com/lucaswalter/SteamDependencyRepro

* `PackageFetched` -> [Link](https://github.com/lucaswalter/SteamDependencyRepro/blob/main/SteamDependencyRepro/Features/PackageFetched.cs)
* `SteamKeyValue` -> [Link](https://github.com/lucaswalter/SteamDependencyRepro/blob/main/SteamDependencyRepro/Models/SteamKeyValue.cs)

---

**Entry Point - `FetchPackageHandler`**
* Mimics and external API call
* Returns a cascaded `PackageFetched` message
  - `PackedFetched` includes a property with the type `SteamKeyValue`

```csharp
  // Inside FetchPackageHandler
  public static PackageFetched Handle(FetchPackageCommand command)
  {
      /*
       * Real application makes External API call to fetch package data
       * (see 'example_steam_key_value.json` file for a real-data example)
       */

      // Build event
      return new PackageFetched(
          SteamPackageId: command.SteamPackageId,
          ChangeNumber: 123,
          Data: new SteamKeyValue(
              Name: "root",
              Value: null,
              Children: new List<SteamKeyValue>
              {
                  new SteamKeyValue(
                      Name: "key1",
                      Value: "value1",
                      Children: new List<SteamKeyValue>()
                  ),
                  new SteamKeyValue(
                      Name: "key2",
                      Value: "value2",
                      Children: new List<SteamKeyValue>()
                  )
              }
          )
      );
  }
```

**Cascaded Message & Handler - `CreatePackageHandler`**
* This handler consumes the cascaded `PackageFetched` message
* Is responsible for creating an event stream for the fetched package

```csharp
public record PackageFetched(
    long SteamPackageId,
    uint ChangeNumber,
    SteamKeyValue Data // Problematic property
);

public record SteamKeyValue(
    string? Name,
    string? Value,
    List<SteamKeyValue> Children
);

```

```csharp
    // Inside CreatePackageHandler
    public static void Handle(PackageFetched evt, IDocumentSession session)
    {
        var id = CombGuidIdGeneration.NewGuid();
        var packageCreated = new PackageCreated(
            PackageId: id,
            SteamPackageId: evt.SteamPackageId,
            Data: evt.Data,
            ChangeNumber: evt.ChangeNumber);

        session.Events.StartStream<Package>(id, packageCreated);
    }
```
**Other Observation**
When putting together the minimal repro, I noticed this error would only happen after adding in the **Marten** dependencies and configuration. Prior to adding Marten, the app would startup just fine and I could actually get a response back from the minimal api endpoint in the repro.

**Comment by jeremydmiller** [comment]
@lucaswalter -->

https://hachyderm.io/@jeremydmiller/110475420777501650

**Comment by lucaswalter** [comment]
Many thanks!!
