### ISSUE TITLE
Object disposed exception on EF Core db context

### ISSUE THREAD

**Issue by kirill-gerasimenko-da** [JasperFx/wolverine#358]
Hi! 

Seems like I've discovered a bug. Given the sample code at https://github.com/kirill-gerasimenko-da/wolverine-reproduce-bug/tree/master I get the following exception, when I run it: 

```
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failure during message processing execution
      System.Exception: Exception of type 'System.Exception' was thrown.
         at ReproduceWolverineIssue.FollowUpHandler.Handle(FollowUpMessage message, AppDbContext context) in /Users/kir/Projects/ReproduceWolverineIssue/ReproduceWolverineIssue/AppHandler.cs:line 42
         at Internal.Generated.WolverineHandlers.FollowUpMessageHandler785345072.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Internal.Generated.WolverineHandlers.FollowUpMessageHandler785345072.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
fail: Wolverine.Runtime.WolverineRuntime[0]
      Exception detected:
      System.ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
      Object name: 'AppDbContext'.
         at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
         at Microsoft.EntityFrameworkCore.DbContext.get_Database()
         at Wolverine.EntityFrameworkCore.Internals.MappedEnvelopeTransaction.RollbackAsync()
         at Wolverine.Runtime.MessageContext.ClearAllAsync()
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.HandlerPipeline.executeAsync(MessageContext context, Envelope envelope, Activity activity)
         at Wolverine.Runtime.HandlerPipeline.InvokeAsync(Envelope envelope, IChannelCallback channel, Activity activity)

 ```

If I comment out injection of the `AppDbContext` https://github.com/kirill-gerasimenko-da/wolverine-reproduce-bug/blob/b3ebc62719f20467d371bf11cbb710e79a123f55/AppHandler.cs#L39 - the exception is gone and I get the expected behavior - the handler gets hit 3 times (because of the policy above) and then messages goes to the deadletter table.  

Please advise.

**Comment by kirill-gerasimenko-da** [comment]
The generated handler code:
```csharp
// <auto-generated/>
#pragma warning disable

namespace Internal.Generated.WolverineHandlers
{
}




// <auto-generated/>
#pragma warning disable
using Microsoft.EntityFrameworkCore;

namespace Internal.Generated.WolverineHandlers
{
    // START: RequestHandler1747511033
    public class RequestHandler1747511033 : Wolverine.Runtime.Handlers.MessageHandler
    {


        public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
        {
            var appHandler = new ReproduceWolverineIssue.AppHandler();
            var request = (ReproduceWolverineIssue.AppHandler.Request)context.Envelope.Message;
            var outgoing1 = await appHandler.Handle(request, context).ConfigureAwait(false);
            
            // Outgoing, cascaded message
            await context.EnqueueCascadingAsync(outgoing1).ConfigureAwait(false);

        }

    }

    // END: RequestHandler1747511033
    
    
    // START: FollowUpMessageHandler785345072
    public class FollowUpMessageHandler785345072 : Wolverine.Runtime.Handlers.MessageHandler
    {
        private readonly Microsoft.EntityFrameworkCore.DbContextOptions<ReproduceWolverineIssue.AppDbContext> _dbContextOptions;

        public FollowUpMessageHandler785345072(Microsoft.EntityFrameworkCore.DbContextOptions<ReproduceWolverineIssue.AppDbContext> dbContextOptions)
        {
            _dbContextOptions = dbContextOptions;
        }



        public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
        {
            var followUpHandler = new ReproduceWolverineIssue.FollowUpHandler();
            await using var appDbContext = new ReproduceWolverineIssue.AppDbContext(_dbContextOptions);
            var followUpMessage = (ReproduceWolverineIssue.FollowUpHandler.FollowUpMessage)context.Envelope.Message;
            
            // Enroll the DbContext & IMessagingContext in the outgoing Wolverine outbox transaction
            var envelopeTransaction = Wolverine.EntityFrameworkCore.WolverineEntityCoreExtensions.BuildTransaction(appDbContext, context);
            await context.EnlistInOutboxAsync(envelopeTransaction);
            await followUpHandler.Handle(followUpMessage, appDbContext).ConfigureAwait(false);
            
            // Added by EF Core Transaction Middleware
            var result_of_SaveChangesAsync = await appDbContext.SaveChangesAsync(cancellation).ConfigureAwait(false);

            // If we have separate context for outbox and application, the we need to manually commit the transaction
            if (envelopeTransaction is Wolverine.EntityFrameworkCore.Internals.RawDatabaseEnvelopeTransaction rawTx) { await rawTx.CommitAsync(); }
        }

    }

    // END: FollowUpMessageHandler785345072
    
    
}
```

**Comment by kirill-gerasimenko-da** [comment]
The real project code doesn't have DbContext directly injected into the handler, but rather has some other component, where it's injected. I think it might make a difference (or no).

**Comment by jeremydmiller** [comment]
Easy money. Need to clean up MessageContext immediately upon failures as a first start, but also harden the envelope transaction types.
