### ISSUE TITLE
Application does not start after upgrading to Wolverine 0.9.19

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#387]
While researching whether #347 would work with 0.9.19 this shows up in the logs after upgrading Wolverine and Wolverine.Marten.

<details>

```
/usr/local/share/dotnet/dotnet /Users/agross/Downloads/wolverine-issue-347/Repro/bin/Debug/net7.0/Repro.dll
No Wolverine extensions are detected
info: Wolverine.Runtime.WolverineRuntime[0]
      Exporting Open Telemetry metrics from Wolverine with name Wolverine:Repro, version 0.9.19.0
info: Marten.IDocumentStore[0]
      Executed schema update SQL:
      DO $$
      BEGIN
          IF NOT EXISTS(
              SELECT schema_name
                FROM information_schema.schemata
                WHERE schema_name = 'saga_events'
            )
          THEN
            EXECUTE 'CREATE SCHEMA saga_events';
          END IF;
      
      END
      $$;
      
      
      DROP TABLE IF EXISTS saga_events.mt_doc_deadletterevent CASCADE;
      CREATE TABLE saga_events.mt_doc_deadletterevent (
          id                  uuid                        NOT NULL,
          data                jsonb                       NOT NULL,
          mt_last_modified    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
          mt_version          uuid                        NOT NULL DEFAULT (md5(random()::text || clock_timestamp()::text)::uuid),
          mt_dotnet_type      varchar                     NULL,
      CONSTRAINT pkey_mt_doc_deadletterevent_id PRIMARY KEY (id)
      );
      
info: Marten.IDocumentStore[0]
      Executed schema update SQL:
      DO $$
      BEGIN
          IF NOT EXISTS(
              SELECT schema_name
                FROM information_schema.schemata
                WHERE schema_name = 'saga_events'
            )
          THEN
            EXECUTE 'CREATE SCHEMA saga_events';
          END IF;
      
      END
      $$;
      
      
      DROP TABLE IF EXISTS saga_events.mt_streams CASCADE;
      CREATE TABLE saga_events.mt_streams (
          id                  varchar        NOT NULL,
          type                varchar        NULL,
          version             bigint         NULL,
          timestamp           timestamptz    NOT NULL DEFAULT (now()),
          snapshot            jsonb          NULL,
          snapshot_version    integer        NULL,
          created             timestamptz    NOT NULL DEFAULT (now()),
          tenant_id           varchar        NULL DEFAULT '*DEFAULT*',
          is_archived         bool           NULL DEFAULT FALSE,
      CONSTRAINT pkey_mt_streams_id PRIMARY KEY (id)
      );
      DROP TABLE IF EXISTS saga_events.mt_events CASCADE;
      CREATE TABLE saga_events.mt_events (
          seq_id            bigint                      NOT NULL,
          id                uuid                        NOT NULL,
          stream_id         varchar                     NULL,
          version           bigint                      NOT NULL,
          data              jsonb                       NOT NULL,
          type              varchar(500)                NOT NULL,
          timestamp         timestamp with time zone    NOT NULL DEFAULT '(now())',
          tenant_id         varchar                     NULL DEFAULT '*DEFAULT*',
          mt_dotnet_type    varchar                     NULL,
          is_archived       bool                        NULL DEFAULT FALSE,
      CONSTRAINT pkey_mt_events_seq_id PRIMARY KEY (seq_id)
      );
      
      ALTER TABLE saga_events.mt_events
      ADD CONSTRAINT fkey_mt_events_stream_id FOREIGN KEY(stream_id)
      REFERENCES saga_events.mt_streams(id)ON DELETE CASCADE
      ;
      
      
      CREATE UNIQUE INDEX pk_mt_events_stream_and_version ON saga_events.mt_events USING btree (stream_id, version);
      
      CREATE UNIQUE INDEX pk_mt_events_id_unique ON saga_events.mt_events USING btree (id);
      CREATE SEQUENCE saga_events.mt_events_sequence;
      ALTER SEQUENCE saga_events.mt_events_sequence OWNED BY saga_events.mt_events.seq_id;
      DROP TABLE IF EXISTS saga_events.mt_event_progression CASCADE;
      CREATE TABLE saga_events.mt_event_progression (
          name            varchar                     NOT NULL,
          last_seq_id     bigint                      NULL,
          last_updated    timestamp with time zone    NULL DEFAULT (transaction_timestamp()),
      CONSTRAINT pk_mt_event_progression PRIMARY KEY (name)
      );
      
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Started HighWaterAgent
info: Wolverine.Runtime.WolverineRuntime[0]
      Starting Wolverine messaging for application assembly Repro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly Repro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Wolverine.Transports.ListeningAgent[0]
      Started message listening at dbcontrol://153f8227-d977-4fb4-9cf2-9d3901430ace/
fail: Wolverine.Runtime.Agents.StartLocalAgentProcessing[0]
      Invocation failed!
      Npgsql.PostgresException (0x80004005): 42P01: relation "wolverine_messages.wolverine_nodes" does not exist
      
      POSITION: 70
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Wolverine.Postgresql.PostgresqlNodePersistence.LoadAllNodesAsync(CancellationToken cancellationToken)
         at Wolverine.Postgresql.PostgresqlNodePersistence.LoadAllNodesAsync(CancellationToken cancellationToken)
         at Wolverine.Runtime.Agents.NodeAgentController.HandleAsync(StartLocalAgentProcessing command)+MoveNext()
         at Wolverine.Runtime.Agents.NodeAgentController.HandleAsync(StartLocalAgentProcessing command)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
        Exception data:
          Severity: ERROR
          SqlState: 42P01
          MessageText: relation "wolverine_messages.wolverine_nodes" does not exist
          Position: 70
          File: parse_relation.c
          Line: 1371
          Routine: parserOpenTable
fail: Wolverine.Runtime.Agents.StartLocalAgentProcessing[0]
      Inline invocation of StartLocalAgentProcessing { Options = Wolverine.WolverineOptions } failed
      Npgsql.PostgresException (0x80004005): 42P01: relation "wolverine_messages.wolverine_nodes" does not exist
      
      POSITION: 70
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Wolverine.Postgresql.PostgresqlNodePersistence.LoadAllNodesAsync(CancellationToken cancellationToken)
         at Wolverine.Postgresql.PostgresqlNodePersistence.LoadAllNodesAsync(CancellationToken cancellationToken)
         at Wolverine.Runtime.Agents.NodeAgentController.HandleAsync(StartLocalAgentProcessing command)+MoveNext()
         at Wolverine.Runtime.Agents.NodeAgentController.HandleAsync(StartLocalAgentProcessing command)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation)
        Exception data:
          Severity: ERROR
          SqlState: 42P01
          MessageText: relation "wolverine_messages.wolverine_nodes" does not exist
          Position: 70
          File: parse_relation.c
          Line: 1371
          Routine: parserOpenTable
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to start the Wolverine messaging
      Npgsql.PostgresException (0x80004005): 42P01: relation "wolverine_messages.wolverine_nodes" does not exist
      
      POSITION: 70
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Wolverine.Postgresql.PostgresqlNodePersistence.LoadAllNodesAsync(CancellationToken cancellationToken)
         at Wolverine.Postgresql.PostgresqlNodePersistence.LoadAllNodesAsync(CancellationToken cancellationToken)
         at Wolverine.Runtime.Agents.NodeAgentController.HandleAsync(StartLocalAgentProcessing command)+MoveNext()
         at Wolverine.Runtime.Agents.NodeAgentController.HandleAsync(StartLocalAgentProcessing command)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation)
         at Wolverine.Runtime.WolverineRuntime.startAgentsAsync()
         at Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken)
        Exception data:
          Severity: ERROR
          SqlState: 42P01
          MessageText: relation "wolverine_messages.wolverine_nodes" does not exist
          Position: 70
          File: parse_relation.c
          Line: 1371
          Routine: parserOpenTable
fail: Wolverine.Runtime.Agents.NodeAgentController[0]
      Error trying to notify other nodes about this node exiting
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Wolverine.Runtime.Agents.NodeAgentController.StopAsync(IMessageBus messageBus)
fail: Wolverine.Runtime.Agents.NodeAgentController[0]
      Error trying to delete the exiting node from node persistence
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Wolverine.Runtime.Agents.NodeAgentController.StopAsync(IMessageBus messageBus)
info: Wolverine.Transports.ListeningAgent[0]
      Stopped message listener at dbcontrol://153f8227-d977-4fb4-9cf2-9d3901430ace/
```

</details>

**Comment by jeremydmiller** [comment]
@agross Add this to your application setup:

https://github.com/JasperFx/wolverine/blob/a4bbdadcb46666cb8e5b72ead861c2f263c07ba6/src/Samples/CommandBus/Program.cs#L43

**Comment by jeremydmiller** [comment]
Closing this for now.

**Comment by sdesaiLULA** [comment]
I had to do the following along with the above statement
```
.IntegrateWithWolverine(x =>
            {
                x.AutoCreate = AutoCreate.CreateOrUpdate;
            })
```
