### ISSUE TITLE
Saga `NotFound` handler is called, but saving fails

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#439]
I have a saga that might receive a message after being completed. I have added the `NotFound` "handler" and the codegen also calls it. But the SaveChangesAsync that happens after calling NotFound throws NonExistentDocumentException for the saga in question. 

```
fail: Wolverine.Runtime.WolverineRuntime[108]
      Envelope Envelope #0188f832-af70-440f-88bc-32d650653dbc/CorrelationId=aa7332a3e72e1eb20028c704b0e81210 (BuchungAutomatischBeenden) from Infrastructure to local://application.usecases.reservierungen.buchungautomatischbeenden/ was moved to the error queue
      Marten.Exceptions.NonExistentDocumentException: Nonexistent document Application.UseCases.Reservierungen.ReservierungSaga: 0188f832-af66-4adc-a95d-a2d98f1cdbac
         at Marten.Internal.UpdateBatch.throwExceptionsIfAny()
         at Marten.Internal.UpdateBatch.ApplyChangesAsync(IMartenSession session, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.ExecuteBatchAsync(IUpdateBatch batch, CancellationToken token)
         at Marten.Internal.Sessions.DocumentSessionBase.SaveChangesAsync(CancellationToken token)
         at Internal.Generated.WolverineHandlers.BuchungAutomatischBeendenHandler571739271.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Internal.Generated.WolverineHandlers.BuchungAutomatischBeendenHandler571739271.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
```

Codegen output:

<details>

```cs
// <auto-generated/>
#pragma warning disable
using Microsoft.Extensions.Logging;
using Wolverine.Marten.Publishing;

namespace Internal.Generated.WolverineHandlers
{
    // START: BuchungAutomatischBeendenHandler571739271
    public class BuchungAutomatischBeendenHandler571739271 : Wolverine.Runtime.Handlers.MessageHandler
    {
        private readonly Microsoft.Extensions.Logging.ILogger<Application.UseCases.Reservierungen.ReservierungSaga> _logger;
        private readonly Wolverine.Marten.Publishing.OutboxedSessionFactory _outboxedSessionFactory;

        public BuchungAutomatischBeendenHandler571739271(Microsoft.Extensions.Logging.ILogger<Application.UseCases.Reservierungen.ReservierungSaga> logger, Wolverine.Marten.Publishing.OutboxedSessionFactory outboxedSessionFactory)
        {
            _logger = logger;
            _outboxedSessionFactory = outboxedSessionFactory;
        }



        public override async System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
        {
            var buchungAutomatischBeenden = (Application.UseCases.Reservierungen.BuchungAutomatischBeenden)context.Envelope.Message;
            await using var documentSession = _outboxedSessionFactory.OpenSession(context);
            string sagaId = context.Envelope.SagaId ?? buchungAutomatischBeenden.ReservierungId;
            if (string.IsNullOrEmpty(sagaId)) throw new Wolverine.Persistence.Sagas.IndeterminateSagaStateIdException(context.Envelope);
            
            // Try to load the existing saga document
            var reservierungSaga = await documentSession.LoadAsync<Application.UseCases.Reservierungen.ReservierungSaga>(sagaId, cancellation).ConfigureAwait(false);
            if (reservierungSaga == null)
            {
                await Application.UseCases.Reservierungen.ReservierungSaga.NotFound(buchungAutomatischBeenden).ConfigureAwait(false);
            }

            else
            {
                await reservierungSaga.Handle(buchungAutomatischBeenden, documentSession, _logger, cancellation).ConfigureAwait(false);
                if (reservierungSaga.IsCompleted())
                {
                    
                    // Register the document operation with the current session
                    documentSession.Delete(reservierungSaga);
                }

                else
                {
                    
                    // Register the document operation with the current session
                    documentSession.Update(reservierungSaga);
                }

                
                // Commit all pending changes
                await documentSession.SaveChangesAsync(cancellation).ConfigureAwait(false);

            }


            // Commit the unit of work
            await documentSession.SaveChangesAsync(cancellation).ConfigureAwait(false);
        }

    }

    // END: BuchungAutomatischBeendenHandler571739271
    
    
}


```

</details>

**Comment by agross** [comment]
I just upgraded to Wolverine 1.1.0, but the error persists.

I've check the codegen an there no longer is a `SaveChangesAsync` call at the end of the method. But since I use automatic transactions, does some other part of Wolverine call it?

Also, the codegen now chokes on directories that cannot be found (the ones for the cs files, which were previously created automatically).

**Comment by agross** [comment]
Ah, scratch that. The error is thrown because 2 saga messages race. The first one completes the save while the second has the saga already loaded and calls `SaveChanges()` after the first message completed the saga.

1. HandlerA loads the saga
2. HandlerB loads the saga in parallel
3. HandlerA completes the saga (deleting it)
4. HandlerB is done, calls `SaveChanges` on a document that was deleted in step 3.
