### ISSUE TITLE
Basic HelloWorld: System.InvalidOperationException: Compilation failures!

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#450]
Hello,

I am just getting started with Wolverine and am greeted with the following exception when trying to access the following endpoint:

```csharp
using Wolverine.Http;

namespace MyApp.Applications.Handlers.Api;

public static class MyAppLandingEndpoint
{
    [WolverineGet("/api/myapp/registration-price")]
    public static decimal GetRegistrationPrice(int numberOfMembers)
    {
        decimal pricePerMember = numberOfMembers >= 500 ? 450 : 280;
        return pricePerMember * numberOfMembers;
    }
}

```

```
> System.InvalidOperationException: Compilation failures!
> 
> CS1002: ; expected
> CS1001: Identifier expected
> CS1525: expression term 'decimal' not valid
> CS0103: the name 'var' does not exist in the current context
> 
> Code:
> 
> // <auto-generated/>
> #pragma warning disable
> using Microsoft.AspNetCore.Routing;
> using System;
> using System.Linq;
> using Wolverine.Http;
> 
> namespace Internal.Generated.WolverineHandlers
> {
>     // START: GET_api_myapp_registration_price
>     public class GET_api_myapp_registration_price : Wolverine.Http.HttpHandler
>     {
>         private readonly Wolverine.Http.WolverineHttpOptions _options;
> 
>         public GET_api_myapp_registration_price(Wolverine.Http.WolverineHttpOptions options) : base(options)
>         {
>             _options = options;
>         }
> 
> 
> 
>         public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
>         {
>             int numberOfMembers = default;
>             int.TryParse(httpContext.Request.Query["numberOfMembers"], out numberOfMembers);
>             var decimal = MyApp.Applications.Handlers.Api.MyAppLandingEndpoint.GetRegistrationPrice(numberOfMembers);
>             await WriteJsonAsync(httpContext, decimal);
>         }
> 
>     }
> 
>     // END: GET_api_myapp_registration_price
>     
>     
> }
> 
> 
>    at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
>    at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
>    at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
>    at Wolverine.Http.HttpChain.<>c__DisplayClass66_0.<BuildEndpoint>b__0()
>    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>    at System.Lazy`1.CreateValue()
>    at Wolverine.Http.HttpChain.<>c__DisplayClass66_0.<BuildEndpoint>b__1(HttpContext c)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Looks like I've found the unhappy path!

**Comment by jeremydmiller** [comment]
Pfft, I see where it's going wrong. Easy fix for the new bug fix release right after the July 4th holiday
