### ISSUE TITLE
Route Constraints break source code generation

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JasperFx/wolverine#465]
This might be a PEBKAC issue, but I noticed that the source generation breaks when adding a route constraint (something valid with ASP.NET routing).

```c#
using Marten;
using Wolverine.Http;
using WolverineMartenSample.Models;

namespace WolverineMartenSample.Endpoints.Todos;

public static class ShowEndpoint
{
    // HERE route constraint of :int 
    [WolverineGet("/todos/{id:int}")]
    public static async Task<IResult> Get(int id, IQuerySession session)
    {
        var todo = await session.LoadAsync<Todo>(id);
        return todo is null ? Results.NotFound() : Results.Ok(todo);
    }
}
```

I get this error:

```
System.InvalidOperationException: Compilation failures!

CS1514: { expected
CS1513: } expected
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS8124: Tuple must contain at least two elements.
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS1022: Type or namespace definition, or end-of-file expected
CS1022: Type or namespace definition, or end-of-file expected
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS0116: A namespace cannot directly contain members such as fields, methods or statements
CS0509: 'GET_todos_id': cannot derive from sealed type 'int'
CS0115: '<invalid-global-code>.Handle(HttpContext)': no suitable method found to override
CS0103: The name '_sessionFactory' does not exist in the current context

Code:

// <auto-generated/>
#pragma warning disable
using Marten;
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: GET_todos_id:int
    public class GET_todos_id:int : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _options;
        private readonly Marten.ISessionFactory _sessionFactory;

        public GET_todos_id:int(Wolverine.Http.WolverineHttpOptions options, Marten.ISessionFactory sessionFactory) : base(options)
        {
            _options = options;
            _sessionFactory = sessionFactory;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            await using var querySession = _sessionFactory.QuerySession();
            if (!int.TryParse((string)httpContext.GetRouteValue("id"), out var id))
            {
                httpContext.Response.StatusCode = 404;
                return;
            }


            var result = await WolverineMartenSample.Endpoints.Todos.ShowEndpoint.Get(id, querySession).ConfigureAwait(false);
            await result.ExecuteAsync(httpContext).ConfigureAwait(false);
        }

    }

    // END: GET_todos_id:int
    
    
}


   at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Wolverine.Http.HttpChain.<>c__DisplayClass66_0.<BuildEndpoint>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Wolverine.Http.HttpChain.<>c__DisplayClass66_0.<BuildEndpoint>b__1(HttpContext c)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Connection: keep-alive
Host: localhost:5279
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Referer: http://localhost:5279/swagger/index.html
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114"
DNT: 1
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
```

**Comment by jeremydmiller** [comment]
Fixed for 1.2.
