### ISSUE TITLE
Source generation can generate two local variables with the same name

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JasperFx/wolverine#466]
Source generation can generate local variables with the same names, which doesn't compile.

```c#
using Marten;
using Wolverine.Http;
using WolverineMartenSample.Models;

namespace WolverineMartenSample.Endpoints.Todos;

public record UpdateRequest(string Name, bool IsComplete);

public static class UpdateEndpoint
{
    public static async Task<(Todo? todo, IResult response)> LoadAsync(int id, UpdateRequest command, IDocumentSession session)
    {
        var todo = await session.LoadAsync<Todo>(id);
        return todo != null 
            ? (todo, response: new WolverineContinue()) 
            : (todo, response: Results.NotFound());
    }
    
    
    [Tags("Todos")]
    [WolverinePut("/todos/{id}")]
    public static Todo Put(int id, UpdateRequest request, Todo todo, IDocumentSession session)
    {
        todo.Name = request.Name;
        todo.IsComplete = request.IsComplete;
        session.Store(todo);
        return todo;
    }
}
```

```
System.InvalidOperationException: Compilation failures!

CS0128: A local variable or function named 'result' is already defined in this scope

Code:

// <auto-generated/>
#pragma warning disable
using Marten;
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: PUT_todos_id
    public class PUT_todos_id : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _options;
        private readonly Marten.ISessionFactory _sessionFactory;

        public PUT_todos_id(Wolverine.Http.WolverineHttpOptions options, Marten.ISessionFactory sessionFactory) : base(options)
        {
            _options = options;
            _sessionFactory = sessionFactory;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            await using var documentSession = _sessionFactory.OpenSession();
            if (!int.TryParse((string)httpContext.GetRouteValue("id"), out var id))
            {
                httpContext.Response.StatusCode = 404;
                return;
            }


            var (request, jsonContinue) = await ReadJsonAsync<WolverineMartenSample.Endpoints.Todos.UpdateRequest>(httpContext);
            if (jsonContinue == Wolverine.HandlerContinuation.Stop) return;
            (var todo, var result) = await WolverineMartenSample.Endpoints.Todos.UpdateEndpoint.LoadAsync(id, request, documentSession).ConfigureAwait(false);
            if (!(result is Wolverine.Http.WolverineContinue))
            {
                await result.ExecuteAsync(httpContext).ConfigureAwait(false);
                return;
            }

            var result = WolverineMartenSample.Endpoints.Todos.UpdateEndpoint.Put(id, request, todo, documentSession);
            
            // Commit any outstanding Marten changes
            await documentSession.SaveChangesAsync(httpContext.RequestAborted).ConfigureAwait(false);

            await result.ExecuteAsync(httpContext).ConfigureAwait(false);
        }

    }

    // END: PUT_todos_id
    
    
}
```

**Comment by jeremydmiller** [comment]
What version are you using? Did you get this with 1.1.4?

**Comment by khalidabuhakmeh** [comment]
No, it was 1.1.3. I'll try updating to 1.1.4 and report back.

**Comment by khalidabuhakmeh** [comment]
I found another edge case. If the named argument of `LoadAsync` is the same name as the return type definition they you get a variable conflict.

```c#
using Marten;
using Microsoft.AspNetCore.Mvc;
using Wolverine.Http;
using WolverineMartenSample.Models;

namespace WolverineMartenSample.Endpoints.Todos;

public record UpdateRequest(string Name, bool IsComplete);

public static class UpdateEndpoint
{
    public static async Task<(Todo? todo, IResult result)> LoadAsync(int id, UpdateRequest command, IDocumentSession session)
    {
        var todo = await session.LoadAsync<Todo>(id);
        return todo != null 
            ? (todo, new WolverineContinue()) 
            : (todo, Results.NotFound());
    }
    
    [Tags("Todos")]
    [WolverinePut("/todos/{id}")]
    [ProducesResponseType(typeof(Todo), 200)]
    [ProducesResponseType(404)]
    public static Todo Put(int id, UpdateRequest request, Todo todo, IDocumentSession session)
    {
        todo.Name = request.Name;
        todo.IsComplete = request.IsComplete;
        session.Store(todo);
        return todo;
    }
}
```

You get this error.

```text
System.InvalidOperationException: Compilation failures!

CS0128: A local variable or function named 'todo' is already defined in this scope

Code:

// <auto-generated/>
#pragma warning disable
using Marten;
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: PUT_todos_id
    public class PUT_todos_id : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _wolverineHttpOptions;
        private readonly Marten.ISessionFactory _sessionFactory557421587;

        public PUT_todos_id(Wolverine.Http.WolverineHttpOptions wolverineHttpOptions, [Lamar.Named("lightweightSessionFactory")] Marten.ISessionFactory sessionFactory557421587) : base(wolverineHttpOptions)
        {
            _wolverineHttpOptions = wolverineHttpOptions;
            _sessionFactory557421587 = sessionFactory557421587;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            await using var documentSession = _sessionFactory557421587.OpenSession();
            if (!int.TryParse((string)httpContext.GetRouteValue("id"), out var id))
            {
                httpContext.Response.StatusCode = 404;
                return;
            }


            var (request, jsonContinue) = await ReadJsonAsync<WolverineMartenSample.Endpoints.Todos.UpdateRequest>(httpContext);
            if (jsonContinue == Wolverine.HandlerContinuation.Stop) return;
            (var todo, var result1) = await WolverineMartenSample.Endpoints.Todos.UpdateEndpoint.LoadAsync(id, request, documentSession).ConfigureAwait(false);
            if (!(result1 is Wolverine.Http.WolverineContinue))
            {
                await result1.ExecuteAsync(httpContext).ConfigureAwait(false);
                return;
            }

            var todo = WolverineMartenSample.Endpoints.Todos.UpdateEndpoint.Put(id, request, todo, documentSession);
            
            // Commit any outstanding Marten changes
            await documentSession.SaveChangesAsync(httpContext.RequestAborted).ConfigureAwait(false);

            await WriteJsonAsync(httpContext, todo);
        }

    }

    // END: PUT_todos_id
    
    
}


   at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Wolverine.Http.HttpChain.<>c__DisplayClass66_0.<BuildEndpoint>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Wolverine.Http.HttpChain.<>c__DisplayClass66_0.<BuildEndpoint>b__1(HttpContext c)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Connection: keep-alive
Host: localhost:5279
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Content-Type: application/json
Origin: http://localhost:5279
Referer: http://localhost:5279/swagger/index.html
Content-Length: 44
sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114"
DNT: 1
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
```
