### ISSUE TITLE
Random Test Failures with WolverineFx 1.2.0 on .NET 7.0 with WebApplicationFactory Bootstrapping App

### ISSUE THREAD

**Issue by slideep** [JasperFx/wolverine#479]
**Hey everyone,**

I just started experimenting with this project. I was able to get my first message handler in working order. However, I noticed that my existing unit tests started failing randomly, this was right before I considered this spike been complete and ready to move along with rest of the "stuff".  I'm using `WebApplicationFactory` to bootstrap my app, particularly in the randomly failing tests. All three (3), now one (1) failing tests are utilizing `new WebApplicationFactory<Program>().WithWebHostBuilder`. These utilize xUnit's `Theory` attribute and have couple `InlineData` values for each of the test cases. Haven't tried whether disabling or overriding with `DisableAllExternalWolverineTransports` has any difference.

Here are some of the details:

**Target framework:** .NET 7.0

**Version:** WolverineFx 1.1.4, 1.2.0

**Setup and configuration:**

Bootstrapping for Wolverine's part uses only this:
```csharp
builder.Host.UseWolverine(options =>
{
    options.Discovery.IncludeAssembly(Assembly.Load("My.Messaging.Application"));
});
```

It happens with this barebones handler as well: 

```csharp
namespace Some.Messaging.Application.Services;

public record MyMessage(string Text, string NotificationType);

public class MyMessageHandler
{
    public void Handle(MyMessage message)
    {
        Console.WriteLine("I got a message!");
    }
}
```

Test app bootstrapping has this for those randomly failing test suites / cases / theories that have worked before introducing the dependency to Wolverine.

```csharp
await using var app = new WebApplicationFactory<Program>().WithWebHostBuilder(builder =>
```

**Test project packages:**

Along these there's the project reference as well as one group.

```xml
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="7.0.9" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="7.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="xunit" Version="2.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="6.0.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="7.0.9" />
</ItemGroup>
```

**Error and stacktrace**:

This is from my local (Rider provided):

```plaintext
System.AggregateException: One or more hosted services failed to stop. (An error occurred while writing to logger(s). (Cannot access a disposed object...
Object name: 'EventLogInternal'.))
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at xxxx.Tests.SmsNotificationMessageTests.MapSmsNotificationMessage_Created(String language, NotificationMessageType template) in X:\xxxx\xxxx\Sources\Repos\xxxx\xxxx\xxxx.API.Tests\SmsNotificationMessageTests.cs:line 52
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 276
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90

System.AggregateException
An error occurred while writing to logger(s). (Cannot access a disposed object.
Object name: 'EventLogInternal'.)
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, Exception exception, String message, Object[] args)
   at Wolverine.Configuration.EndpointCollection.DrainAsync()
   at Wolverine.Runtime.WolverineRuntime.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

System.ObjectDisposedException
Cannot access a disposed object.
Object name: 'EventLogInternal'.
   at System.Diagnostics.EventLogInternal.OpenForWrite(String currentMachineName)
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
```

CI's workflow run gives this a bit more comprehensive trace:

```plaintext
info: Wolverine.Runtime.WolverineRuntime[0]
      Exporting Open Telemetry metrics from Wolverine with name Wolverine:Some.API, version 1.1.4.0
info: Wolverine.Runtime.WolverineRuntime[0]
      Starting Wolverine messaging for application assembly Some.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly Some.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly Some.Messaging.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Some.Messaging.Application.Integrations.Brevo.BrevoWorker[0]
      Brevo worker running at: 07/18/2023 13:31:12 +00:00
info: System.Net.Http.HttpClient.Brevo.LogicalHandler[100]
      Start processing HTTP request GET https://api.brevo.com/v3/smtp/templates
info: System.Net.Http.HttpClient.Brevo.ClientHandler[100]
      Sending HTTP request GET https://api.brevo.com/v3/smtp/templates
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to 'drain' outstanding messages in local sender Wolverine.Transports.Local.BufferedLocalQueue
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Wolverine.Runtime.WorkerQueues.BufferedReceiver.DrainAsync()
         at Wolverine.Configuration.EndpointCollection.DrainAsync()
[xUnit.net 00:00:21.89]     Some.Application.Tests.SmsNotificationMessageTests.MapSmsNotificationMessage_Created(language: "en", template: NotificationForSomeImportantEvent) [FAIL]
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to 'drain' outstanding messages in local sender Wolverine.Transports.Local.BufferedLocalQueue
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Wolverine.Runtime.WorkerQueues.BufferedReceiver.DrainAsync()
         at Wolverine.Configuration.EndpointCollection.DrainAsync()
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to 'drain' outstanding messages in local sender Wolverine.Transports.Local.BufferedLocalQueue
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Wolverine.Runtime.WorkerQueues.BufferedReceiver.DrainAsync()
         at Wolverine.Configuration.EndpointCollection.DrainAsync()
  Failed Some.Application.Tests.SmsNotificationMessageTests.MapSmsNotificationMessage_Created(language: "en", template: NotificationForSomeImportantEvent) [3 s]
  Error Message:
   System.AggregateException : One or more hosted services failed to stop. (An error occurred while writing to logger(s). (Cannot access a disposed object.
Object name: 'EventLogInternal'.))
---- System.AggregateException : An error occurred while writing to logger(s). (Cannot access a disposed object.
Object name: 'EventLogInternal'.)
-------- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'EventLogInternal'.
  Stack Trace:
     at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Some.Application.Tests.SmsNotificationMessageTests.MapSmsNotificationMessage_Created(String language, NotificationMessageType template) in D:\a\some-messaging-api\some-messaging-api\Some.API.Tests\SmsNotificationMessageTests.cs:line 52
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, Exception exception, String message, Object[] args)
   at Wolverine.Configuration.EndpointCollection.DrainAsync()
   at Wolverine.Runtime.WolverineRuntime.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
----- Inner Stack Trace -----
   at System.Diagnostics.EventLogInternal.OpenForWrite(String currentMachineName)
   at System.Diagnostics.EventLogInternal.InternalWriteEvent(UInt32 eventID, UInt16 category, EventLogEntryType type, String[] strings, Byte[] rawData, String currentMachineName)
   at System.Diagnostics.EventLogInternal.WriteEvent(EventInstance instance, Byte[] data, Object[] values)
   at Microsoft.Extensions.Logging.EventLog.WindowsEventLog.WriteEntry(String message, EventLogEntryType type, Int32 eventID, Int16 category)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.WriteMessage(String message, EventLogEntryType eventLogEntryType, Int32 eventId)
   at Microsoft.Extensions.Logging.EventLog.EventLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
```

**Comment by jeremydmiller** [comment]
@slideep Just for fun, can you take out the WindowsEventLog usage and see if it gets better? Loggers are *never* suppose to throw exceptions. That's your underlying culprit.

**Comment by slideep** [comment]
@jeremydmiller Thanks, Jeremy! I love seeing all the tests light up bright green. The CI workflow ran as well. The refresher on logging providers was a nice read too:
https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-providers

For my particular setup and configuration in regards of logging, I removed all the providers and then based on environment added the necessary loggers suitable for my needs.

`builder.Logging.ClearProviders();`

All good, back to coding!
