### ISSUE TITLE
Anonymous Fsharp record types causes syntax error in generated code

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#515]
The out-of-box FSharp support is super inspiring! I have just come across an edge case with the following endpoint using anonymous records:

```fsharp
module HelloEndpoint =

    [<Wolverine.Http.WolverineGetAttribute("api/hello-anonymous")>]
    let HelloAnonymous() =
        {| Product = "Orange Juice"; Price = 12 |}
```

Which results in the following exception and generated code:

```
System.InvalidOperationException: Compilation failures!

CS1525: Terme d'expression '<' non valide
CS1525: Terme d'expression '>' non valide
CS0246: Le nom de type ou d'espace de noms 'var<>' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?)

Code:

// <auto-generated/>
#pragma warning disable
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: GET_api_hello_anonymous
    public class GET_api_hello_anonymous : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _wolverineHttpOptions;

        public GET_api_hello_anonymous(Wolverine.Http.WolverineHttpOptions wolverineHttpOptions) : base(wolverineHttpOptions)
        {
            _wolverineHttpOptions = wolverineHttpOptions;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var <>f__AnonymousType2761394780_response = MyApp.HelloEndpoint.HelloAnonymous();
            await WriteJsonAsync(httpContext, <>f__AnonymousType2761394780_response);
        }

    }

    // END: GET_api_hello_anonymous
    
    
}


   at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Wolverine.Http.HttpChain.<>c__DisplayClass67_0.<BuildEndpoint>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Wolverine.Http.HttpChain.<>c__DisplayClass67_0.<BuildEndpoint>b__4(HttpContext c)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

The culprit is the var <> token. A workaround is to define the type of the record explicitly using something like:

```fsharp
    type PriceSummary = { Price: int; Product: string }
```

**Comment by jeremydmiller** [comment]
Got it. Won't be hard to deal with that one.
