### ISSUE TITLE
Resource Setup fails with "duplicate key value violates unique constraint pg_type_typname_nsp_index"

### ISSUE THREAD

**Issue by Xzelsius** [JasperFx/wolverine#522]
Hello

We currently struggle with some resource setup failures.
The weird part is, it's somewhat random on one developer machine and never occurred on other developer machines.

```
2023-08-24 11:13:16 Searching 'JasperFx.CodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, 
2023-08-24 11:13:16 PublicKeyToken=null' for commands
2023-08-24 11:13:16 Searching 'Weasel.CommandLine, Version=6.0.1.0, Culture=neutral, 
2023-08-24 11:13:16 PublicKeyToken=null' for commands
2023-08-24 11:13:16 Searching 'Marten.CommandLine, Version=0.0.0.0, Culture=neutral, 
2023-08-24 11:13:16 PublicKeyToken=null' for commands
2023-08-24 11:13:16 Searching 'Wolverine, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' for
2023-08-24 11:13:16 commands
2023-08-24 11:13:16 Searching 'TenantInstance.Configuration.Command, Version=1.0.0.0, 
2023-08-24 11:13:16 Culture=neutral, PublicKeyToken=null' for commands
2023-08-24 11:13:16 Searching 'Wolverine.Http.FluentValidation, Version=0.0.0.0, Culture=neutral, 
2023-08-24 11:13:16 PublicKeyToken=null' for commands
2023-08-24 11:13:16 
2023-08-24 11:13:16 [09:13:16 INF Wolverine.Runtime.WolverineRuntime] Exporting Open Telemetry metrics from Wolverine with name Wolverine:TenantInstance.Shared.Command.Api, version 1.6.0.0
2023-08-24 11:13:16 
2023-08-24 11:13:16 [09:13:16 WRN Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository] Storing keys in a directory '/home/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
2023-08-24 11:13:16 [09:13:16 INF Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] User profile is available. Using '/home/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
2023-08-24 11:13:17 DROP TABLE IF EXISTS public.wolverine_outgoing_envelopes CASCADE;
2023-08-24 11:13:17 CREATE TABLE public.wolverine_outgoing_envelopes (
2023-08-24 11:13:17     id              uuid                        NOT NULL,
2023-08-24 11:13:17     owner_id        integer                     NOT NULL,
2023-08-24 11:13:17     destination     varchar                     NOT NULL,
2023-08-24 11:13:17     deliver_by      timestamp with time zone    NULL,
2023-08-24 11:13:17     body            bytea                       NOT NULL,
2023-08-24 11:13:17     attempts        integer                     NULL DEFAULT 0,
2023-08-24 11:13:17     message_type    varchar                     NOT NULL,
2023-08-24 11:13:17 CONSTRAINT pkey_wolverine_outgoing_envelopes_id PRIMARY KEY (id)
2023-08-24 11:13:17 );
2023-08-24 11:13:17 DROP TABLE IF EXISTS public.wolverine_incoming_envelopes CASCADE;
2023-08-24 11:13:17 CREATE TABLE public.wolverine_incoming_envelopes (
2023-08-24 11:13:17     id                uuid                        NOT NULL,
2023-08-24 11:13:17     status            varchar                     NOT NULL,
2023-08-24 11:13:17     owner_id          integer                     NOT NULL,
2023-08-24 11:13:17     execution_time    timestamp with time zone    NULL DEFAULT NULL,
2023-08-24 11:13:17     attempts          integer                     NULL DEFAULT 0,
2023-08-24 11:13:17     body              bytea                       NOT NULL,
2023-08-24 11:13:17     message_type      varchar                     NOT NULL,
2023-08-24 11:13:17     received_at       varchar                     NULL,
2023-08-24 11:13:17     keep_until        timestamp with time zone    NULL,
2023-08-24 11:13:17 CONSTRAINT pkey_wolverine_incoming_envelopes_id PRIMARY KEY (id)
2023-08-24 11:13:17 );
2023-08-24 11:13:17 DROP TABLE IF EXISTS public.wolverine_dead_letters CASCADE;
2023-08-24 11:13:17 CREATE TABLE public.wolverine_dead_letters (
2023-08-24 11:13:17     id                   uuid                        NOT NULL,
2023-08-24 11:13:17     execution_time       timestamp with time zone    NULL DEFAULT NULL,
2023-08-24 11:13:17     body                 bytea                       NOT NULL,
2023-08-24 11:13:17     message_type         varchar                     NOT NULL,
2023-08-24 11:13:17     received_at          varchar                     NULL,
2023-08-24 11:13:17     source               varchar                     NULL,
2023-08-24 11:13:17     exception_type       varchar                     NULL,
2023-08-24 11:13:17     exception_message    varchar                     NULL,
2023-08-24 11:13:17     sent_at              timestamp with time zone    NULL,
2023-08-24 11:13:17     replayable           boolean                     NULL,
2023-08-24 11:13:17 CONSTRAINT pkey_wolverine_dead_letters_id PRIMARY KEY (id)
2023-08-24 11:13:17 );
2023-08-24 11:13:17 DROP TABLE IF EXISTS public.wolverine_nodes CASCADE;
2023-08-24 11:13:17 CREATE TABLE public.wolverine_nodes (
2023-08-24 11:13:17     id              uuid                        NOT NULL,
2023-08-24 11:13:17     node_number     serial                      NOT NULL,
2023-08-24 11:13:17     description     varchar                     NOT NULL,
2023-08-24 11:13:17     uri             varchar                     NOT NULL,
2023-08-24 11:13:17     started         timestamp with time zone    NOT NULL DEFAULT now(),
2023-08-24 11:13:17     health_check    timestamp with time zone    NOT NULL DEFAULT now(),
2023-08-24 11:13:17     capabilities    text[]                      NULL,
2023-08-24 11:13:17 CONSTRAINT pkey_wolverine_nodes_id PRIMARY KEY (id)
2023-08-24 11:13:17 );
2023-08-24 11:13:17 DROP TABLE IF EXISTS public.wolverine_node_assignments CASCADE;
2023-08-24 11:13:17 CREATE TABLE public.wolverine_node_assignments (
2023-08-24 11:13:17     id         varchar                     NOT NULL,
2023-08-24 11:13:17     node_id    uuid                        NULL,
2023-08-24 11:13:17     started    timestamp with time zone    NOT NULL DEFAULT now(),
2023-08-24 11:13:17 CONSTRAINT pkey_wolverine_node_assignments_id PRIMARY KEY (id)
2023-08-24 11:13:17 );
2023-08-24 11:13:17 
2023-08-24 11:13:17 ALTER TABLE public.wolverine_node_assignments
2023-08-24 11:13:17 ADD CONSTRAINT fkey_wolverine_node_assignments_node_id FOREIGN KEY(node_id)
2023-08-24 11:13:17 REFERENCES public.wolverine_nodes(id)ON DELETE CASCADE
2023-08-24 11:13:17 ;
2023-08-24 11:13:17 
2023-08-24 11:13:17 DROP TABLE IF EXISTS public.wolverine_control_queue CASCADE;
2023-08-24 11:13:17 CREATE TABLE public.wolverine_control_queue (
2023-08-24 11:13:17     id              uuid                        NOT NULL,
2023-08-24 11:13:17     message_type    varchar                     NOT NULL,
2023-08-24 11:13:17     node_id         uuid                        NOT NULL,
2023-08-24 11:13:17     body            bytea                       NOT NULL,
2023-08-24 11:13:17     posted          timestamp with time zone    NOT NULL DEFAULT NOW(),
2023-08-24 11:13:17     expires         timestamp with time zone    NULL,
2023-08-24 11:13:17 CONSTRAINT pkey_wolverine_control_queue_id PRIMARY KEY (id)
2023-08-24 11:13:17 );
2023-08-24 11:13:17 
2023-08-24 11:13:17 [09:13:17 ERR Oakton.Resources.ResourceSetupHostService] Failed to setup resource Envelope Storage of type Wolverine
2023-08-24 11:13:17 System.AggregateException: One or more errors occurred. (23505: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
2023-08-24 11:13:17 
2023-08-24 11:13:17 DETAIL: Key (typname, typnamespace)=(wolverine_outgoing_envelopes, 2200) already exists.)
2023-08-24 11:13:17  ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
2023-08-24 11:13:17 
2023-08-24 11:13:17 DETAIL: Key (typname, typnamespace)=(wolverine_outgoing_envelopes, 2200) already exists.
2023-08-24 11:13:17    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
2023-08-24 11:13:17    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
2023-08-24 11:13:17    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
2023-08-24 11:13:17    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
2023-08-24 11:13:17    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
2023-08-24 11:13:17    at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
2023-08-24 11:13:17    at Weasel.Postgresql.PostgresqlMigrator.executeDelta(SchemaMigration migration, DbConnection conn, AutoCreate autoCreate, IMigrationLogger logger, CancellationToken ct)
2023-08-24 11:13:17    at Weasel.Core.Migrator.ApplyAllAsync(DbConnection conn, SchemaMigration migration, AutoCreate autoCreate, IMigrationLogger logger, CancellationToken ct)
2023-08-24 11:13:17    at Wolverine.RDBMS.MessageDatabase`1.migrateAsync(DbConnection conn)
2023-08-24 11:13:17    at Wolverine.RDBMS.MessageDatabase`1.MigrateAsync()
2023-08-24 11:13:17    at Wolverine.RDBMS.MessageDatabase`1.MigrateAsync()
2023-08-24 11:13:17    at Wolverine.RDBMS.MultiTenancy.MultiTenantedMessageDatabase.executeOnAllAsync(Func`2 action)
2023-08-24 11:13:17   Exception data:
2023-08-24 11:13:17     Severity: ERROR
2023-08-24 11:13:17     SqlState: 23505
2023-08-24 11:13:17     MessageText: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
2023-08-24 11:13:17     Detail: Key (typname, typnamespace)=(wolverine_outgoing_envelopes, 2200) already exists.
2023-08-24 11:13:17     SchemaName: pg_catalog
2023-08-24 11:13:17     TableName: pg_type
2023-08-24 11:13:17     ConstraintName: pg_type_typname_nsp_index
2023-08-24 11:13:17     File: nbtinsert.c
2023-08-24 11:13:17     Line: 664
2023-08-24 11:13:17     Routine: _bt_check_unique
2023-08-24 11:13:17    --- End of inner exception stack trace ---
2023-08-24 11:13:17    at Wolverine.RDBMS.MultiTenancy.MultiTenantedMessageDatabase.executeOnAllAsync(Func`2 action)
2023-08-24 11:13:17    at Wolverine.RDBMS.MultiTenancy.MultiTenantedMessageDatabase.Wolverine.Persistence.Durability.IMessageStoreAdmin.MigrateAsync()
2023-08-24 11:13:17    at Oakton.Resources.ResourceSetupHostService.<>c__DisplayClass5_0.<<StartAsync>g__execute|0>d.MoveNext()
2023-08-24 11:13:17 [red]ERROR:[/]System.AggregateException: One or more errors occurred. (Failed to setup 
2023-08-24 11:13:17 resource Envelope Storage of type Wolverine)
2023-08-24 11:13:17      Oakton.Resources.ResourceSetupException: Failed to setup resource Envelope 
2023-08-24 11:13:17      Storage of type Wolverine                                                  
2023-08-24 11:13:17      …                                                                          
2023-08-24 11:13:17   at async Task Oakton.Resources.ResourceSetupHostService.StartAsync(           
2023-08-24 11:13:17      CancellationToken cancellationToken)                                       
2023-08-24 11:13:17   at async Task Microsoft.Extensions.Hosting.Internal.Host.StartAsync(          
2023-08-24 11:13:17      CancellationToken cancellationToken)                                       
2023-08-24 11:13:17   at async Task<bool> Oakton.Commands.RunCommand.Execute(RunInput input)        
2023-08-24 11:13:17   at async Task<int> Oakton.CommandExecutor.execute(CommandRun run) 
```

The whole solution consists of two web hosts (command and query, both using the same database for Wolverine) and a bunch of referenced projects with the actual logic liked handlers and endpoints. 

We start up everything using docker compose. The compose stack contains things like Azurite, PostgreSQL and others.
The web hosts both depend on PostgreSQL to be healthy. On development machine, PostgreSQL is defined like this
```
postgresql_db:
  image: postgres:15.2-alpine3.17@sha256:07ec36ad2d5ab9250f38c8ef749239b662cf15d03c9ddb7167422edbbdf71156
  restart: always
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
  user: postgres
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 5s
    retries: 5
    start_period: 5s
    timeout: 5s
```

As of now, we mostly use HTTP endpoints and a few command handlers
Here are some parts of `dotnet run -- describe`

```
┌───────────────────────────────────────────────┬───────────────────────────────────────────────┬──────────────────┬──────────────────────────────────────────────┬─────────────────────────────────────────────┐
│ Uri                                           │ Name                                          │ Mode             │ Execution                                    │ Serializers                                 │
├───────────────────────────────────────────────┼───────────────────────────────────────────────┼──────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ local://agents/                               │ agents                                        │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│                                               │                                               │                  │ False                                        │                                             │
│ local://createchildorganizationalunitendpoint │ createchildorganizationalunitendpoint_tenanti │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│ _tenantinstance.configuration.command.endpoin │ nstance.configuration.command.endpoints.organ │                  │ False                                        │                                             │
│ ts.organizationalunits.createchildorganizatio │ izationalunits.createchildorganizationalunite │                  │                                              │                                             │
│ nalunitendpoint.createchildorganizationunitco │ ndpoint.createchildorganizationunitcommand    │                  │                                              │                                             │
│ mmand/                                        │                                               │                  │                                              │                                             │
│ dbcontrol://e00edb5c-a29c-413c-83d7-1cec418df │ dbcontrol://e00edb5c-a29c-413c-83d7-1cec418df │ BufferedInMemory │ MaxDegreeOfParallelism: 1, EnsureOrdered:    │ SystemTextJsonSerializer (application/json) │
│ efd/                                          │ efd/                                          │                  │ True                                         │                                             │
│ local://default/                              │ default                                       │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│                                               │                                               │                  │ False                                        │                                             │
│ local://disableoidcscimendpoint_tenantinstanc │ disableoidcscimendpoint_tenantinstance.config │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│ e.configuration.command.endpoints.idpconfigur │ uration.command.endpoints.idpconfiguration.di │                  │ False                                        │                                             │
│ ation.disableoidcscimendpoint.disableoidcscim │ sableoidcscimendpoint.disableoidcscimcommand  │                  │                                              │                                             │
│ command/                                      │                                               │                  │                                              │                                             │
│ local://durable/                              │ durable                                       │ Durable          │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│                                               │                                               │                  │ False                                        │                                             │
│ local://enableoidcscimendpoint_tenantinstance │ enableoidcscimendpoint_tenantinstance.configu │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│ .configuration.command.endpoints.idpconfigura │ ration.command.endpoints.idpconfiguration.ena │                  │ False                                        │                                             │
│ tion.enableoidcscimendpoint.enableoidcscimcom │ bleoidcscimendpoint.enableoidcscimcommand     │                  │                                              │                                             │
│ mand/                                         │                                               │                  │                                              │                                             │
│ local://replies/                              │ replies                                       │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│                                               │                                               │                  │ False                                        │                                             │
│ local://scheduled/                            │ scheduled                                     │ Durable          │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│                                               │                                               │                  │ False                                        │                                             │
│ local://system/                               │ system                                        │ BufferedInMemory │ MaxDegreeOfParallelism: 1, EnsureOrdered:    │ SystemTextJsonSerializer (application/json) │
│                                               │                                               │                  │ True                                         │                                             │
│ local://updateorganizationalunitendpoint_tena │ updateorganizationalunitendpoint_tenantinstan │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│ ntinstance.configuration.command.endpoints.or │ ce.configuration.command.endpoints.organizati │                  │ False                                        │                                             │
│ ganizationalunits.updateorganizationalunitend │ onalunits.updateorganizationalunitendpoint.up │                  │                                              │                                             │
│ point.updatechildorganizationalunitcommand/   │ datechildorganizationalunitcommand            │                  │                                              │                                             │
│ local://updateorganizationalunitendpoint_tena │ updateorganizationalunitendpoint_tenantinstan │ BufferedInMemory │ MaxDegreeOfParallelism: 20, EnsureOrdered:   │ SystemTextJsonSerializer (application/json) │
│ ntinstance.configuration.command.endpoints.or │ ce.configuration.command.endpoints.organizati │                  │ False                                        │                                             │
│ ganizationalunits.updateorganizationalunitend │ onalunits.updateorganizationalunitendpoint.up │                  │                                              │                                             │
│ point.updaterootorganizationalunitcommand/    │ daterootorganizationalunitcommand             │                  │                                              │                                             │
└───────────────────────────────────────────────┴───────────────────────────────────────────────┴──────────────────┴──────────────────────────────────────────────┴─────────────────────────────────────────────┘
── Wolverine Message Routing ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[11:30:50 INF Wolverine.Runtime.Agents.NodeAgentController] Node e00edb5c-a29c-413c-83d7-1cec418dfefd successfully assumed leadership
┌──────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┐
│ Message Type                                                                                 │ Destination                                                                                 │ Content Type     │
├──────────────────────────────────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────┼──────────────────┤
│ TenantInstance.Configuration.Command.Endpoints.IdpConfiguration.DisableOidcScimEndpoint.Disa │ local://disableoidcscimendpoint_tenantinstance.configuration.command.endpoints.idpconfigura │ application/json │
│ bleOidcScimCommand                                                                           │ tion.disableoidcscimendpoint.disableoidcscimcommand/                                        │                  │
│ TenantInstance.Configuration.Command.Endpoints.IdpConfiguration.EnableOidcScimEndpoint.Enabl │ local://enableoidcscimendpoint_tenantinstance.configuration.command.endpoints.idpconfigurat │ application/json │
│ eOidcScimCommand                                                                             │ ion.enableoidcscimendpoint.enableoidcscimcommand/                                           │                  │
│ TenantInstance.Configuration.Command.Endpoints.OrganizationalUnits.CreateChildOrganizational │ local://createchildorganizationalunitendpoint_tenantinstance.configuration.command.endpoint │ application/json │
│ UnitEndpoint.CreateChildOrganizationUnitCommand                                              │ s.organizationalunits.createchildorganizationalunitendpoint.createchildorganizationunitcomm │                  │
│                                                                                              │ and/                                                                                        │                  │
│ TenantInstance.Configuration.Command.Endpoints.OrganizationalUnits.UpdateOrganizationalUnitE │ local://updateorganizationalunitendpoint_tenantinstance.configuration.command.endpoints.org │ application/json │
│ ndpoint.UpdateChildOrganizationalUnitCommand                                                 │ anizationalunits.updateorganizationalunitendpoint.updatechildorganizationalunitcommand/     │                  │
│ TenantInstance.Configuration.Command.Endpoints.OrganizationalUnits.UpdateOrganizationalUnitE │ local://updateorganizationalunitendpoint_tenantinstance.configuration.command.endpoints.org │ application/json │
│ ndpoint.UpdateRootOrganizationalUnitCommand                                                  │ anizationalunits.updateorganizationalunitendpoint.updaterootorganizationalunitcommand/      │                  │
└──────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┘
── Wolverine Http Endpoints ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌────────────────────────────────────────────────────────────┬─────────────┬──────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────┐
│ Route                                                      │ Http Method │ Handler Method                                                   │ Generated Type Name                                             │
├────────────────────────────────────────────────────────────┼─────────────┼──────────────────────────────────────────────────────────────────┼─────────────────────────────────────────────────────────────────┤
│ /Configuration/OrganizationalUnit                          │ POST        │ TenantInstance.Configuration.Command.Endpoints.OrganizationalUni │ POST_Configuration_OrganizationalUnit                           │
│                                                            │             │ ts.CreateChildOrganizationalUnitEndpoint.Create()                │                                                                 │
│ /Configuration/OrganizationalUnit/{id}/Update              │ POST        │ TenantInstance.Configuration.Command.Endpoints.OrganizationalUni │ POST_Configuration_OrganizationalUnit_id_Update                 │
│                                                            │             │ ts.UpdateOrganizationalUnitEndpoint.Update()                     │                                                                 │
│ Configuration/Groups/{id}/ChangeName                       │ POST        │ TenantInstance.Configuration.Command.Endpoints.Groups.ChangeName │ POST_Configuration_Groups_id_ChangeName                         │
│                                                            │             │ Endpoint.ChangeName()                                            │                                                                 │
│ Configuration/Groups/{id}/Delete                           │ POST        │ TenantInstance.Configuration.Command.Endpoints.Groups.DeleteGrou │ POST_Configuration_Groups_id_Delete                             │
│                                                            │             │ pEndpoint.Delete()                                               │                                                                 │
│ Configuration/Groups/Create                                │ POST        │ TenantInstance.Configuration.Command.Endpoints.Groups.CreateGrou │ POST_Configuration_Groups_Create                                │
│                                                            │             │ pEndpoint.Create()                                               │                                                                 │
│ Configuration/IdpConfiguration/DisableOidcScim             │ POST        │ TenantInstance.Configuration.Command.Endpoints.IdpConfiguration. │ POST_Configuration_IdpConfiguration_DisableOidcScim             │
│                                                            │             │ DisableOidcScimEndpoint.DisableOidcScim()                        │                                                                 │
│ Configuration/IdpConfiguration/EnableOidcScim              │ POST        │ TenantInstance.Configuration.Command.Endpoints.IdpConfiguration. │ POST_Configuration_IdpConfiguration_EnableOidcScim              │
│                                                            │             │ EnableOidcScimEndpoint.EnableOidcScim()                          │                                                                 │
│ Configuration/IdpConfiguration/UpdateOidcClientCredentials │ POST        │ TenantInstance.Configuration.Command.Endpoints.IdpConfiguration. │ POST_Configuration_IdpConfiguration_UpdateOidcClientCredentials │
│                                                            │             │ UpdateOidcClientCredentialsEndpoint.UpdateOidcClientCredentials( │                                                                 │
│                                                            │             │ )                                                                │                                                                 │
│ Configuration/Users/{id}/Delete                            │ POST        │ TenantInstance.Configuration.Command.Endpoints.Users.DeleteUserE │ POST_Configuration_Users_id_Delete                              │
│                                                            │             │ ndpoint.Delete()                                                 │                                                                 │
│ Configuration/Users/{id}/Disable                           │ POST        │ TenantInstance.Configuration.Command.Endpoints.Users.DisableUser │ POST_Configuration_Users_id_Disable                             │
│                                                            │             │ Endpoint.Disable()                                               │                                                                 │
│ Configuration/Users/{id}/Enable                            │ POST        │ TenantInstance.Configuration.Command.Endpoints.Users.EnableUserE │ POST_Configuration_Users_id_Enable                              │
│                                                            │             │ ndpoint.Enable()                                                 │                                                                 │
│ Configuration/Users/{id}/SendInitialPassword               │ POST        │ TenantInstance.Configuration.Command.Endpoints.Users.SendInitial │ POST_Configuration_Users_id_SendInitialPassword                 │
│                                                            │             │ PasswordEndpoint.SendInitialPassword()                           │                                                                 │
│ Configuration/Users/{id}/Update                            │ POST        │ TenantInstance.Configuration.Command.Endpoints.Users.UpdateUserE │ POST_Configuration_Users_id_Update                              │
│                                                            │             │ ndpoint.Update()                                                 │                                                                 │
│ Configuration/Users/Create                                 │ POST        │ TenantInstance.Configuration.Command.Endpoints.Users.CreateUserE │ POST_Configuration_Users_Create                                 │
│                                                            │             │ ndpoint.Create()                                                 │                                                                 │
└────────────────────────────────────────────────────────────┴─────────────┴──────────────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────────────┘
```

Note that we intentionally use local queues instead of durable because multi tenancy without knowing the tenants at startup time is not yet supported in Wolverine.

This is our host setup
```
host.UseWolverine(opts =>
{
    opts.Policies.AutoApplyTransactions();
    opts.UseFluentValidation();
});
```

and later, we configure Marten to integrate with Wolverine

```
marten.IntegrateWithWolverine(masterDatabaseConnectionString: BuildConnectionString(configuration, "Wolverine")).EventForwardingToWolverine();
```

and enable resource setup on startup with
```
services.AddResourceSetupOnStartup();
```
Above line was disabled on on web host to see if this causes the problems.

Please let me know if you have any idea on what is wrong here?
If you need more details, I try to provide them.

**Comment by jeremydmiller** [comment]
I think it's just a timing issue. How likely is it that multiple nodes are spinning up at the same time and trying to do this simultaneously?

**Comment by Xzelsius** [comment]
This code is not yet running in production. Locally, there were two instances.
When we will run this in production, it could be anywhere from 3 to 5 instances that spin up simultaneously.

I think, part of my issue was, that I was using the same PostgreSQL database and schema for technically two different Wolverine apps (both reuse parts, but are not equally at all). So now my query and command API web hosts both have their own schema, thus it's fixed on the dev machine. But in a Kubernetes environment, it might still hit this.

Not sure whether this issue could be fixed by your side at all or within a reasonable amount of time.
My best bet is, that I should migrate stuff before spinning up the instances using init containers. But that's another story.

But it might be worth to add a troubleshooting section to Wolverine too (like Marten has one).
Let me know if I should create a PR to start the troubleshooting section.

**Comment by jeremydmiller** [comment]
@Xzelsius,

As a short term thing, this:

"
Not sure whether this issue could be fixed by your side at all or within a reasonable amount of time.
My best bet is, that I should migrate stuff before spinning up the instances using init containers. But that's another story.
"

Longer term, I'll add a mix of random waits and an advisory lock to stop that from happening
