### ISSUE TITLE
Simultaneous compilations of HTTP handlers

### ISSUE THREAD

**Issue by BrianVallelunga** [JasperFx/wolverine#527]
I'm seeing behavior where two HTTP requests are being handled at the same time and one of them fails with the following exception:

> System.InvalidOperationException: Frame chain is being re-arranged, tried to set Lamar.IoC.Frames.GetInstanceFromNestedContainerFrame as the 'Next' property on Lamar.IoC.Frames.NestedContainerCreation
   at JasperFx.CodeGeneration.Frames.Frame.set_Next(Frame value)
   at JasperFx.CodeGeneration.Model.MethodFrameArranger.chainFrames(Frame[] frames)
   at JasperFx.CodeGeneration.Model.MethodFrameArranger.Arrange(AsyncMode& asyncMode, Frame& topFrame)
   at JasperFx.CodeGeneration.GeneratedMethod.ArrangeFrames(GeneratedType type, IServiceVariableSource services)...

Sometimes we'll get this error:

> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at JasperFx.CodeGeneration.DependencyGatherer.findDependencies(Frame frame)+MoveNext()
         at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at JasperFx.CodeGeneration.DependencyGatherer.<.ctor>b__3_0(Frame frame)
         at JasperFx.Core.LightweightCache`2.get_Item(TKey key)
         at JasperFx.CodeGeneration.DependencyGatherer.findDependencies(Variable variable)+MoveNext()

This seems related to https://github.com/JasperFx/wolverine/issues/42 but we're running the latest build of Wolverine, 1.6.

**Comment by BrianVallelunga** [comment]
I'm going to try and reproduce this in a basic sample next week. It happens running locally, but not on our dev server, so I want to figure out what the difference is.

**Comment by jeremydmiller** [comment]
It's a very generic exception. Is this from Wolverine.HTTP endpoints or message handlers?

**Comment by BrianVallelunga** [comment]
It's using the HTTP endpoints and is caused when multiple HTTP requests are hitting the app simultaneously, especially if one of the other requests is taking a long time. I'm working on a repo.

**Comment by BrianVallelunga** [comment]
I've attached a repo of the issue. I suspect I missed something in the documentation because the issue only happens when I add a custom middleware. Commenting out the middleware in the Program.cs file fixes the issue. The middleware just logs a message in the Begin method.

The Index page fires off a few fetches to the two API endpoints and logs the response in the console.

[WolverineFrameChainRepo.zip](https://github.com/JasperFx/wolverine/files/12553478/WolverineFrameChainRepo.zip)

**Comment by jeremydmiller** [comment]
Think I have it. Scoping problem with IoC related frames.

**Comment by BrianVallelunga** [comment]
Great, thanks!
