### ISSUE TITLE
Is it possible to invoke an handler from an Oakton command?

### ISSUE THREAD

**Issue by pomma89** [JasperFx/wolverine#529]
Hi,

I am trying to invoke an handler from an Oakton command within the same ASP.NET Core application, but I do not know if it is supported and if I am doing it the right way.

Following code implements what I am trying to do:

```cs
using Oakton;
using Wolverine;

[assembly: OaktonCommandAssembly]
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Host.UseWolverine();

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();

app.UseHttpsRedirection();

return await app.RunOaktonCommands(args);

public class Ping
{
    public int Number { get; set; }
}

public class PingHandler
{
    public void Handle(Ping ping)
    {
        Console.WriteLine(ping.Number);
    }
}

public class PingInput : NetCoreInput
{
    public int Number { get; set; }
}

public class PingCommand : OaktonAsyncCommand<PingInput>
{
    public override async Task<bool> Execute(PingInput input)
    {
        var host = input.BuildHost();
        await host.InvokeAsync(new Ping { Number = input.Number });
        return true;
    }
}
```

When I run it with `dotnet run -- ping 1`, I get the following error:

```txt
No Wolverine extensions are detected
Searching 'JasperFx.CodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Wolverine, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'WebApplication2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' for commands

info: Wolverine.Runtime.WolverineRuntime[0]
      Exporting Open Telemetry metrics from Wolverine with name Wolverine:WebApplication2, version 1.6.0.0
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to create a message handler for Ping
      Wolverine.Runtime.Routing.IndeterminateRoutesException: Could not determine any valid subscribers or local handlers for message type Ping

         at Wolverine.Runtime.Routing.EmptyMessageRouter`1.FindSingleRouteForSending()
         at Wolverine.Runtime.WolverineRuntime.findInvoker(Type messageType)
[red]ERROR:[/]Wolverine.Runtime.Routing.IndeterminateRoutesException: Could not determine any valid subscribers or local handlers for
message type Ping

  at Task Wolverine.Runtime.Handlers.NoHandlerExecutor.InvokeAsync(object message, MessageBus bus, CancellationToken
     cancellation, TimeSpan? timeout, string tenantId)
  at Task Wolverine.Runtime.MessageBus.InvokeAsync(object message, CancellationToken cancellation, TimeSpan? timeout)
  at Task Wolverine.HostBuilderExtensions.InvokeAsync<T>(IHost host, T command)
  at async Task<bool> PingCommand.Execute(PingInput input) in C:\Users\aless\source\repos\WebApplication2\Program.cs:44
  at async Task<int> Oakton.CommandExecutor.execute(CommandRun run)
```

If I add to the Oakton command a call to `AssertWolverineConfigurationIsValid`:

```cs
public class PingCommand : OaktonAsyncCommand<PingInput>
{
    public override async Task<bool> Execute(PingInput input)
    {
        var host = input.BuildHost();
        host.AssertWolverineConfigurationIsValid(); // <----
        await host.InvokeAsync(new Ping { Number = input.Number });
        return true;
    }
}
```

Error message changes, as if the handler had become available but another error occurred while invoking it:

```txt
No Wolverine extensions are detected
Searching 'JasperFx.CodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'Wolverine, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' for commands
Searching 'WebApplication2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' for commands

info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly WebApplication2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Wolverine.Runtime.WolverineRuntime[0]
      Exporting Open Telemetry metrics from Wolverine with name Wolverine:WebApplication2, version 1.6.0.0
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to create a message handler for Ping
      System.InvalidOperationException: Frame chain is being re-arranged, tried to set Wolverine.Runtime.Handlers.MessageFrame as the 'Next' property on Lamar.IoC.Instances.InstanceConstructorFrame
         at JasperFx.CodeGeneration.Frames.Frame.set_Next(Frame value)
         at JasperFx.CodeGeneration.Model.MethodFrameArranger.chainFrames(Frame[] frames)
         at JasperFx.CodeGeneration.Model.MethodFrameArranger.Arrange(AsyncMode& asyncMode, Frame& topFrame)
         at JasperFx.CodeGeneration.GeneratedMethod.ArrangeFrames(GeneratedType type, IServiceVariableSource services)
         at JasperFx.CodeGeneration.GeneratedType.ArrangeFrames(IServiceVariableSource services)
         at JasperFx.CodeGeneration.GeneratedAssembly.GenerateCode(IServiceVariableSource services)
         at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
         at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
         at Wolverine.Runtime.Handlers.HandlerGraph.HandlerFor(Type messageType)
         at Wolverine.Runtime.WolverineRuntime.Wolverine.Runtime.IExecutorFactory.BuildFor(Type messageType)
         at Wolverine.Runtime.WolverineRuntime.findInvoker(Type messageType)
[red]ERROR:[/]System.InvalidOperationException: Frame chain is being re-arranged, tried to set Wolverine.Runtime.Handlers.MessageFrame
as the 'Next' property on Lamar.IoC.Instances.InstanceConstructorFrame
  at Task Wolverine.Runtime.Handlers.NoHandlerExecutor.InvokeAsync(object message, MessageBus bus, CancellationToken
     cancellation, TimeSpan? timeout, string tenantId)
  at Task Wolverine.Runtime.MessageBus.InvokeAsync(object message, CancellationToken cancellation, TimeSpan? timeout)
  at Task Wolverine.HostBuilderExtensions.InvokeAsync<T>(IHost host, T command)
  at async Task<bool> PingCommand.Execute(PingInput input) in C:\Users\aless\source\repos\WebApplication2\Program.cs:45
  at async Task<int> Oakton.CommandExecutor.execute(CommandRun run)
```

If I run the `describe` command, the handler seems to be available:

```txt
┌──────────────┬──────────────┬──────────────────────────┬───────────────────────┐
│ Message Name │ Message Type │ Handler.Method()         │ Generated Type Name   │
│              │   namespace  │   namespace              │                       │
├──────────────┼──────────────┼──────────────────────────┼───────────────────────┤
│ Ping         │ Ping         │ PingHandler.Handle(ping) │ PingHandler2000246286 │
│              │              │                          │                       │
└──────────────┴──────────────┴──────────────────────────┴───────────────────────┘


── Wolverine Listeners ─────────────────────────────────────────────────────────────────────────────────────────────────
info: Wolverine.Runtime.WolverineRuntime[0]
      Starting Wolverine messaging for application assembly WebApplication2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
info: Wolverine.Runtime.WolverineRuntime[0]
      External transports are disabled, skipping conventional listener discovery
info: Wolverine.Runtime.WolverineRuntime[0]
      'Stubbing' out all external Wolverine transports for testing
info: Wolverine.Runtime.WolverineRuntime[0]
      'Stubbing' out all external Wolverine transports for testing
info: Wolverine.Runtime.WolverineRuntime[0]
      'Stubbing' out all external Wolverine transports for testing
info: Wolverine.Runtime.WolverineRuntime[0]
      All external endpoint listeners are disabled because of configuration
┌────────────────────┬───────────┬──────────────────┬─────────────────────────────────┬────────────────────────────────┐
│ Uri                │ Name      │ Mode             │ Execution                       │ Serializers                    │
├────────────────────┼───────────┼──────────────────┼─────────────────────────────────┼────────────────────────────────┤
│ local://agents/    │ agents    │ BufferedInMemory │ MaxDegreeOfParallelism: 20,     │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: False            │ (application/json)             │
│ local://default/   │ default   │ BufferedInMemory │ MaxDegreeOfParallelism: 12,     │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: False            │ (application/json)             │
│ local://durable/   │ durable   │ Durable          │ MaxDegreeOfParallelism: 12,     │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: False            │ (application/json)             │
│ local://ping/      │ ping      │ BufferedInMemory │ MaxDegreeOfParallelism: 12,     │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: False            │ (application/json)             │
│ local://replies/   │ replies   │ BufferedInMemory │ MaxDegreeOfParallelism: 12,     │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: False            │ (application/json)             │
│ local://scheduled/ │ scheduled │ Durable          │ MaxDegreeOfParallelism: 12,     │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: False            │ (application/json)             │
│ local://system/    │ system    │ BufferedInMemory │ MaxDegreeOfParallelism: 1,      │ SystemTextJsonSerializer       │
│                    │           │                  │ EnsureOrdered: True             │ (application/json)             │
└────────────────────┴───────────┴──────────────────┴─────────────────────────────────┴────────────────────────────────┘


── Wolverine Message Routing ───────────────────────────────────────────────────────────────────────────────────────────
┌──────────────┬───────────────┬──────────────────┐
│ Message Type │ Destination   │ Content Type     │
├──────────────┼───────────────┼──────────────────┤
│ Ping         │ local://ping/ │ application/json │
└──────────────┴───────────────┴──────────────────┘


── Wolverine Sending Endpoints ─────────────────────────────────────────────────────────────────────────────────────────
┌────────────────────┬───────────┬──────────────────┬─────────────────────────────────────────────┐
│ Uri                │ Name      │ Mode             │ Serializer(s)                               │
├────────────────────┼───────────┼──────────────────┼─────────────────────────────────────────────┤
│ local://agents/    │ agents    │ BufferedInMemory │ SystemTextJsonSerializer (application/json) │
│ local://default/   │ default   │ BufferedInMemory │ SystemTextJsonSerializer (application/json) │
│ local://durable/   │ durable   │ Durable          │ SystemTextJsonSerializer (application/json) │
│ local://ping/      │ ping      │ BufferedInMemory │ SystemTextJsonSerializer (application/json) │
│ local://replies/   │ replies   │ BufferedInMemory │ SystemTextJsonSerializer (application/json) │
│ local://scheduled/ │ scheduled │ Durable          │ SystemTextJsonSerializer (application/json) │
│ local://system/    │ system    │ BufferedInMemory │ SystemTextJsonSerializer (application/json) │
└────────────────────┴───────────┴──────────────────┴─────────────────────────────────────────────┘

```

Thank you for any information you can provide,
Goodbye,
Alessio

**Comment by jeremydmiller** [comment]
Easy money, you'll have to `Start()` the host, not just build it. 

So:

```csharp
public class PingCommand : OaktonAsyncCommand<PingInput>
{
    public override async Task<bool> Execute(PingInput input)
    {
        var host = input.BuildHost();

        // Add this line of code.
        await host.StartAsync(CancellationToken.None);
        host.AssertWolverineConfigurationIsValid(); // <----
        await host.InvokeAsync(new Ping { Number = input.Number });
        return true;
    }
}

```

**Comment by pomma89** [comment]
Thank you very much @jeremydmiller, it works 👍

Starting the host also makes the call to `AssertWolverineConfigurationIsValid()` unnecessary, it works correctly without it.

Thanks again,
Goodbye,
Alessio
