### ISSUE TITLE
Using Refit client in wolverine http handler results in compilation failures

### ISSUE THREAD

**Issue by erdtsieck** [JasperFx/wolverine#568]
Reproduction steps:

Add Refit client:

```cs
builder.Services.AddRefitClient<ITestHttpClient>();

public interface ITestHttpClient
{
    [Get("/test{id}")]
    Task<string> GetAfzenderAsync(string id);
}
```

Wolverine endpoint:

```cs
public record Message1(string Text);
public class Test1Endpoint
{
    [WolverinePost("Test1")]
    public static OutgoingMessages Post(Message1 message, ITestHttpClient testCLient)
    {
        return new OutgoingMessages { new Message2(message.Text) };
    }
}

public record Message2(string Text);
public class Test2Handler
{
    public static void Handle(Message2 message)
    {
        Console.WriteLine("I got a message!");
    }
}
```

Results in the follow exception:

```
System.InvalidOperationException: Compilation failures!

CS1061: 'IMessageContext' does not contain a definition for 'EnqueueCascadingAsync' and no accessible extension method 'EnqueueCascadingAsync' accepting a first argument of type 'IMessageContext' could be found (are you missing a using directive or an assembly reference?)

Code:

// <auto-generated/>
#pragma warning disable
using Lamar;
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: POST_Test1
    public class POST_Test1 : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _wolverineHttpOptions;
        private readonly Lamar.IContainer _rootContainer;

        public POST_Test1(Wolverine.Http.WolverineHttpOptions wolverineHttpOptions, Lamar.IContainer rootContainer) : base(wolverineHttpOptions)
        {
            _wolverineHttpOptions = wolverineHttpOptions;
            _rootContainer = rootContainer;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            await using var nestedContainer = (Lamar.IContainer)_rootContainer.GetNestedContainer();
            var messageContext = nestedContainer.GetInstance<Wolverine.IMessageContext>();
            
            /*
            * The scoping is Transient, so a Lambda registration requires
            * the usage of a nested container for resolution for correct scoping.
            * A formal factory provider may be an alternative
            */
            var testHttpClient = nestedContainer.GetInstance<ITestHttpClient>();
            // Reading the request body via JSON deserialization
            var (message, jsonContinue) = await ReadJsonAsync<WolverineRefitTest.Controllers.Message1>(httpContext);
            if (jsonContinue == Wolverine.HandlerContinuation.Stop) return;
            
            // The actual HTTP request handler execution
            var outgoingMessages = WolverineRefitTest.Controllers.Test1Endpoint.Post(message, testHttpClient);

            
            // Outgoing, cascaded message
            await messageContext.EnqueueCascadingAsync(outgoingMessages).ConfigureAwait(false);

            // Wolverine automatically sets the status code to 204 for empty responses
            httpContext.Response.StatusCode = 204;
        }

    }

    // END: POST_Test1
    
    
}


   at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Wolverine.Http.HttpChain.<>c__DisplayClass71_0.<BuildEndpoint>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Wolverine.Http.HttpChain.<>c__DisplayClass71_0.<BuildEndpoint>b__4(HttpContext c)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Forwarding the message to a "normal" wolverine handler works just fine:

```cs
public record Message1(string Text);
public class Test1Endpoint
{
    [WolverinePost("Test1")]
    public static OutgoingMessages Post(Message1 message)
    {
        return new OutgoingMessages { new Message2(message.Text) };
    }
}

public record Message2(string Text);
public class Test2Handler
{
    public static OutgoingMessages Handle(Message2 message, ITestHttpClient testCLient)
    {
        return new OutgoingMessages { new Message3(message.Text) };
    }
}

public record Message3(string Text);
public class Test3Handler
{
    public static void Handle(Message3 message)
    {
        Console.WriteLine("I got a message!");
    }
}
```

**Comment by erdtsieck** [comment]
[WolverineRefitTest.zip](https://github.com/JasperFx/wolverine/files/12738086/WolverineRefitTest.zip)

Here is the full source code

**Comment by jeremydmiller** [comment]
@erdtsieck Meh. I gotta dig into Refit and remind myself how it builds things. This might have to be addressed with a Wolverine.Http.Refit Nuget. I might be kicking this into 1.8 instead of 1.7.2

**Comment by erdtsieck** [comment]
> @erdtsieck Meh. I gotta dig into Refit and remind myself how it builds things. This might have to be addressed with a Wolverine.Http.Refit Nuget. I might be kicking this into 1.8 instead of 1.7.2

That is fine. I added a workaround as you can see. It only happens on http handlers

**Comment by alistair** [comment]
@jeremydmiller is the issue the difference in MessageContext vs IMessageContext in the following code.

https://github.com/JasperFx/wolverine/blob/main/src/Wolverine/Runtime/Handlers/CaptureCascadingMessages.cs#L10-L14

IMessageContext doesn't contain EnqueueCascadingAsync.  Normally the code generated creates a MessageContext directly, potentially meaning the code just works.

But in the nestedContainer mode we are actually fetching the IMessageContext. 

Options here

1) fetch a MessageContext from the nested container.  Probably by updating the CaptureCascadingMessages code?
2) cast the IMessageContext to MessageContext.  not 100% sure where.
3) Add EnqueueCascadingAsync to the IMessageContext interface.   seems like a bad idea.
4) Use the IMessageBus interface in CaptureCascadingMessages code

**Comment by jeremydmiller** [comment]
@erdtsieck What version did you try this with? Based on what @alistair said, I think this was fixed by https://github.com/JasperFx/wolverine/commit/d1b0e21bacabb9508d5638378d6ebda23cc78d91.

I confirmed that it's working w/ a test just now. I'm closing. Fixes will be in 1.8 now. I'm skipping 1.7.2 and going for 1.8 with some new testing utilities.

**Comment by erdtsieck** [comment]
> @erdtsieck What version did you try this with? Based on what @alistair said, I think this was fixed by https://github.com/JasperFx/wolverine/commit/d1b0e21bacabb9508d5638378d6ebda23cc78d91.
> 
> I confirmed that it's working w/ a test just now. I'm closing. Fixes will be in 1.8 now. I'm skipping 1.7.2 and going for 1.8 with some new testing utilities.

I will try tomorrow

**Comment by jeremydmiller** [comment]
Meh, it's fixed locally, but the next step is a little optimization so that we can ignore the lambda registration for refit. I'll open a secondary issue for this.
