### ISSUE TITLE
Incompatible JasperFX.Core version in WolverineFx.Postgresql

### ISSUE THREAD

**Issue by redbaty** [JasperFx/wolverine#637]
**Describe the bug**
This error is thrown while calling `host.SetupResources();`

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Weasel.Postgresql.PostgresqlProvider' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'
   at Weasel.Core.DatabaseProvider`6..ctor(String defaultDatabaseSchemaName)
   at Weasel.Postgresql.PostgresqlProvider..ctor()
   at Weasel.Postgresql.PostgresqlProvider..cctor()
   --- End of inner exception stack trace ---
   at Weasel.Postgresql.PostgresqlMigrator..ctor()
   at Wolverine.Postgresql.PostgresqlMessageStore..ctor(DatabaseSettings databaseSettings, DurabilitySettings settings, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass27_0.<quickResolve>b__0(CtorArg x)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Frames.InjectedServiceField.ToVariableExpression(LambdaDefinition definition)
   at JasperFx.CodeGeneration.Expressions.LambdaDefinition.ExpressionFor(Variable variable)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Lamar.IoC.Frames.ListAssignmentFrame`1.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Instances.FuncResolverDefinition.BuildResolver()
   at Lamar.IoC.Instances.GeneratedInstance.BuildFuncResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
   at Lamar.ServiceGraph.FindResolver(Type serviceType)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Oakton.Resources.ResourcesCommand.FindResources(IServiceProvider services, String typeName, String resourceName)
   at Oakton.Resources.ResourceHostExtensions.SetupResources(IHost host, CancellationToken cancellation, String resourceType, String resourceName)
```

I believe this is due to an incompatible version of `Weasel.Postgresql` which depends on `Weasel.Core` that expects an older version of `JasperFX`

**To Reproduce**
1. Create a new project with postgresql persistance
2. Call `host.SetupResources()`

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22631.2715
 - Version WolverineFx.Postgresql 1.12.0

**Comment by jeremydmiller** [comment]
Upgrade to Wolverine 1.12.1 when that's available in the next 30 minutes

**Comment by jeremydmiller** [comment]
@redbaty I'll still pull your PR in later as a longer term fix. Thank you!

**Comment by redbaty** [comment]
Hey there, sorry for the timing confusion on the pull request hehe.

By the way even on the latest 1.12.2 there's still an error thrown while using postgres:

```
System.InvalidCastException: Unable to cast object of type 'Weasel.Core.DbObjectName' to type 'Weasel.Postgresql.PostgresqlObjectName'.
   at Weasel.Postgresql.Tables.Table.ColumnExpression.ForeignKeyTo(DbObjectName referencedIdentifier, String referencedColumnName, String fkName, CascadeAction onDelete, CascadeAction onUpdate)
   at Wolverine.Postgresql.PostgresqlMessageStore.AllObjects()+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Wolverine.RDBMS.MessageDatabase`1.get_Objects()
   at Weasel.Core.Migrations.DatabaseBase`1.<>c.<AllObjects>b__19_0(IFeatureSchema group)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Weasel.Core.Migrations.DatabaseBase`1.ApplyAllConfiguredChangesToDatabaseAsync(IGlobalLock`1 globalLock, Nullable`1 override, ReconnectionOptions reconnectionOptions, CancellationToken ct)
   at Oakton.Resources.ResourceHostExtensions.SetupResources(IHost host, CancellationToken cancellation, String resourceType, String resourceName)
```

I had it fixed in by doing this in the PR: https://github.com/JasperFx/wolverine/pull/638/commits/a454a5ac1f5e87748797da2bf4ad417d630115bc#diff-96018c9e1e0dcb7add35644a779053e4ee707e7fc1775f7e5d60a1fd09af3a16

**Comment by redbaty** [comment]
Works after 1.12.3, thanks! 🎉
