### ISSUE TITLE
ArgumentNullException on serializer in MessageRoute constructor

### ISSUE THREAD

**Issue by p-fx** [JasperFx/wolverine#645]
When upgrading the Wolverine NuGet packages - `WolverineFx`, `WolverineFx.EntityFrameworkCore`, `WolverineFx.RabbitMQ` and `WolverineFx.SqlServer`  in a .NET Web Api application to a version higher then `1.7.1` then below exception occurs on startup when defining the RabbitMQ routing setup.

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'serializer')
   at Wolverine.Runtime.Routing.    ..ctor(IMessageSerializer serializer, ISendingAgent sender, IEnumerable`1 rules, IReplyTracker replyTracker)
   at Wolverine.Runtime.Routing.MessageRoute..ctor(Type messageType, Endpoint endpoint, IReplyTracker replies)
   at Wolverine.Runtime.Routing.MessageRouterBase`1.<>c__DisplayClass2_0.<.ctor>b__1(Endpoint endpoint)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Wolverine.Runtime.Routing.MessageRouterBase`1..ctor(WolverineRuntime runtime)
   at Wolverine.Runtime.Routing.MessageRouter`1..ctor(WolverineRuntime runtime, IEnumerable`1 routes)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Wolverine.Runtime.WolverineRuntime.RoutingFor(Type messageType)
   at Wolverine.Runtime.MessageBus.PublishAsync[T](T message, DeliveryOptions options)
   at Wolverine.Runtime.MessageContext.EnqueueCascadingAsync(Object message)
   at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
   at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
   at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation)
   at Wolverine.Runtime.WolverineRuntime.startNodeAgentWorkflowAsync()
   at Wolverine.Runtime.WolverineRuntime.startAgentsAsync()
   at Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\Dev\Spikes\WolverineWithRabbitMQ\Program.cs:line 42
```
---

The most minimal reproducible example I could set up is below one, where the combination of `PersistMessagesWithSqlServer` and `options.Publish(config => config.Message(typeof(Greeting)).ToRabbitTopics("Messages"));` causes the error to occur.

I'm experiencing this error when running on .NET 6 (but also on 8) hosted in Kestrel or IIS. I know that it's bizarre to mention that this error does rarely occur when running from within Visual Studio (2022) on IIS Express ... Any related integration tests via Alba do fail on the same error.

--- 
```
using Oakton.Resources;
using Wolverine;
using Wolverine.Attributes;
using Wolverine.EntityFrameworkCore;
using Wolverine.RabbitMQ;
using Wolverine.SqlServer;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddSwaggerGen();

builder.Host.UseWolverine((hostBuilderContext, options) =>
{
    options.UseRabbitMq(options =>
    {
        options.HostName = "localhost";
        options.UserName = "guest";
        options.Password = "guest";
    });

    options.Policies.UseDurableOutboxOnAllSendingEndpoints();
    options.UseEntityFrameworkCoreTransactions();
    options.PersistMessagesWithSqlServer(
        "Data Source=(localdb)\\mssqllocaldb;database=SomeDatabase;trusted_connection=yes
        );

    options.Publish(config => config.Message(typeof(Greeting)).ToRabbitTopics("Messages"));

    builder.Host.UseResourceSetupOnStartup();
});

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapControllers();
app.Run();

[MessageIdentity("Messages.Greeting")]
public sealed class Greeting
{
    public string Message { get; set; } = string.Empty;
}
```

**Comment by jeremydmiller** [comment]
@p-fx Huh, no clue so far, but I'm looking at this now.

**Comment by jeremydmiller** [comment]
@p-fx Hey, do you have any of the serializer extension libs like MemoryPack or MessagePack present?

**Comment by jeremydmiller** [comment]
I did make *a* fix to 1.13 coming soon that might knock this out.

**Comment by jeremydmiller** [comment]
I *think* this will be closed by https://github.com/JasperFx/wolverine/commit/0fa4f65ef9e894d951c0561630e16876245db090

**Comment by p-fx** [comment]
Great. Will have a look once 1.13.0 is available. Thanks!
(Just for completeness, I'm not using any MemoryPack or MessagePack extensions.)
