### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified

### ISSUE THREAD

**Issue by nkosi23** [JasperFx/wolverine#662]
**Describe the bug**
_I do not know if the JasperFx.Core project is still being maintained since it has had no activity in over a year, and the description says that Wolverine is its successor, I therefore repost this issue here and apologize if this is not appropriate._ 

When running a basic empty ASP.NET Core project in F# configured to use a library calling JasperFx under the hoods (Oakton, Wolverine, etc...) I get the following exception on application startup:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'
   at Oakton.CommandFactory..ctor()
   at Oakton.CommandLineHostingExtensions.ApplyOaktonExtensions(IHostBuilder builder)
```

What is strange is that the dll is correctly copied to the output directory, however its metadata are a bit strange: namely the version is set to 0.0.0.0, here is what JetBrains Rider displays about the assembly referenced by the project

```
Name: JasperFx.Core
Full name: JasperFx.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
Location: /home/username/.nuget/packages/jasperfx.core/1.5.1/lib/net7.0/JasperFx.Core.dll
Mvid: 0726d806-ac4a-4c0f-8c5e-398ba3a43e29
Platform: net7.0
```

Needless to say that this issue is quite blocking, running a project with something as basic as the below should reproduce the exception:

```fsharp

    let exitCode = 0
    let builder = WebApplication.CreateBuilder(args)
    builder.Host.ApplyOaktonExtensions()

    builder.Services.AddControllers()
    builder.Services.AddResourceSetupOnStartup()

   let app = builder.Build()

  app.RunOaktonCommands(args) |> Async.AwaitTask 
  
  exitCode

```

If I remove the lines regarding oakton and try to configure Wolverine using the UseWolverine method of the hostbuilder, this exception will be thrown at that point instead. I've seen people succefully boostrap JasperFx-based projects using F# [like here](https://github.com/JasperFx/marten/issues/1283#issue-453263241) so I'm a bit puzzled.

Everything works properly in the C# version but I am in the process of migrating all the projects to F#. Any idea or pointers? Cleaning/Rebuilding does not help unfortunately. The project targets .NET 7:

```xml
<PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

 <ItemGroup>
        <PackageReference Include="FSharp.SystemTextJson" Version="1.2.42"/>
        <PackageReference Include="JasperFx.Core" Version="1.5.1"/>
        <PackageReference Include="MailKit" Version="4.2.0"/>
        <PackageReference Include="Marten" Version="6.4.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0"/>
        <PackageReference Include="WolverineFx" Version="1.8.0"/>
        <PackageReference Include="WolverineFx.Http" Version="1.8.0"/>
    </ItemGroup>
```

**To Reproduce**
1. Create a new F# ASP.NET Core project referencing a JasperFx based project
2. Run the application
3. The exception is produced

**Expected behavior**
The application is launched

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux x64
 - Browser N/A
 - Version openSUSE

**Comment by jeremydmiller** [comment]
**Jasper** is the old name for Wolverine, and that is no longer maintained as that became Wolverine. **JasperFx.Core** is a shared library used by Marten, Wolverine, and others that is actively maintained. 

This sounds like a run of the mill Nuget reference problem which unfortunately happens quite often with projects that are moving. If you were on the latest Wolverine or Oakton, both are forcing you to the latest JasperFx.Core, which should knock out the problem.

There's nothing actionable here, so I am closing this one.
