### ISSUE TITLE
Insertion failure after updating Wolverine from 1.7.1 to 1.12.4 and csharp to v8: insert into .wolverine_node_records 

### ISSUE THREAD

**Issue by Richard87** [JasperFx/wolverine#671]
**Describe the bug**

**To Reproduce**
Running Wolverine v1.12 fails 

**Expected behavior**
No error messages in log

**Logs**
```
net /Users/richard/Projects/happydogs/backend/Web/bin/Debug/net8.0/Web.dll
Connecting to database: localhost:5433/postgres as postgres
Searching 'JasperFx.CodeGeneration.Commands, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' for commands
Searching 'Weasel.CommandLine, Version=6.4.1.0, Culture=neutral, 
PublicKeyToken=null' for commands
Searching 'Marten.CommandLine, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' for commands
Searching 'Wolverine, Version=1.12.4.0, Culture=neutral, PublicKeyToken=null' 
for commands
Searching 'Wolverine.Http.FluentValidation, Version=0.0.0.0, Culture=neutral, 
PublicKeyToken=null' for commands

info: Marten.IDocumentStore[0]
      Exporting Open Telemetry metrics from MartenDb (martendb-event-lag)
info: Wolverine.Http.HttpGraph[0]
      Found 118 Wolverine HTTP endpoints in assemblys Web, Wolverine.Http.FluentValidation, Happydogs

dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Oakton.Resources.ResourceSetupHostService[0]
      Ran Setup() on resource Envelope Storage of type Wolverine
info: Oakton.Resources.ResourceSetupHostService[0]
      Ran Setup() on resource WolverineEnvelopeStorage of type WeaselDatabase
info: Oakton.Resources.ResourceSetupHostService[0]
      Ran Setup() on resource Marten of type WeaselDatabase
info: Oakton.Resources.ResourceSetupHostService[0]
      Ran Setup() on resource WolverineEnvelopeStorage of type WeaselDatabase
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Started HighWaterAgent
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'MembersView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'MembersView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'DogView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'DogView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'BreederView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'BreederView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'UniqueMemberEmailView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'UniqueMemberEmailView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'ContactListView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'ContactListView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'MemberDetailsView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'MemberDetailsView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'ImageView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'ImageView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'LitterPrivateDetailsView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'LitterPrivateDetailsView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'LitterPublicDetailsView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'LitterPublicDetailsView:All' has started from sequence 65001 and a high water mark of 65001
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Starting projection agent for 'ThreadView:All'
info: Marten.Events.Daemon.AsyncProjectionHostedService[0]
      Projection agent for 'ThreadView:All' has started from sequence 65001 and a high water mark of 65001
info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly Web, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly Wolverine.Http.FluentValidation, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Wolverine.Configuration.HandlerDiscovery[0]
      Searching assembly Happydogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null for Wolverine message handlers
info: Wolverine.Transports.ListeningAgent[0]
      Started message listening at dbcontrol://9f6c2df0-1f48-401f-8b65-0b0cbf98a380/
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5036
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/richard/Projects/happydogs/backend/Web
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
fail: Wolverine.Runtime.Agents.IAgentCommand[0]
      Invocation failed!
      Wolverine.RDBMS.Polling.DatabaseBatchCommandException: Database operation batch failure:
      insert into .wolverine_node_records (node_number, event_name, description) values (@p0, @p1, @p2);insert into .wolverine_node_records (node_number, event_name, description) values (@p3, @p4, @p5);insert into .wolverine_node_records (node_number, event_name, description) values (@p6, @p7, @p8);
      p0: 1877737017
      p1: NodeStarted
      p2: 
      p3: 159
      p4: ElectionRequested
      p5: 
      p6: 159
      p7: LeadershipAssumed
      p8: wolverine://leader/
       ---> Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "."
      
      POSITION: 13
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()
        Exception data:
          Severity: ERROR
          SqlState: 42601
          MessageText: syntax error at or near "."
          Position: 13
          File: scan.l
          Line: 1188
          Routine: scanner_yyerror
         --- End of inner exception stack trace ---
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
fail: Wolverine.Runtime.Agents.IAgentCommand[0]
      Inline invocation of Wolverine.RDBMS.Polling.DatabaseOperationBatch failed
      Wolverine.RDBMS.Polling.DatabaseBatchCommandException: Database operation batch failure:
      insert into .wolverine_node_records (node_number, event_name, description) values (@p0, @p1, @p2);insert into .wolverine_node_records (node_number, event_name, description) values (@p3, @p4, @p5);insert into .wolverine_node_records (node_number, event_name, description) values (@p6, @p7, @p8);
      p0: 1877737017
      p1: NodeStarted
      p2: 
      p3: 159
      p4: ElectionRequested
      p5: 
      p6: 159
      p7: LeadershipAssumed
      p8: wolverine://leader/
       ---> Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "."
      
      POSITION: 13
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
         at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()
        Exception data:
          Severity: ERROR
          SqlState: 42601
          MessageText: syntax error at or near "."
          Position: 13
          File: scan.l
          Line: 1188
          Routine: scanner_yyerror
         --- End of inner exception stack trace ---
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+MoveNext()
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation)

```

**Desktop (please complete the following information):**
```xml
    <ItemGroup>
        <PackageReference Include="Marten" Version="6.4.0" />
        <PackageReference Include="WolverineFx" Version="1.12.4" />
        <PackageReference Include="WolverineFx.FluentValidation" Version="1.12.4" />
        <PackageReference Include="WolverineFx.Http.FluentValidation" Version="1.12.4" />
        <PackageReference Include="WolverineFx.HTTP" Version="1.12.4" />
        <PackageReference Include="WolverineFx.Marten" Version="1.12.4" />
    </ItemGroup>
```

**Smartphone (please complete the following information):**
 - OS: MacOS, Fedora
 - Browser Chrome

**Additional context**

**Comment by Richard87** [comment]
Fixed by https://github.com/JasperFx/wolverine/commit/e01ed6c3f68528b0df0aa5c8940823304543b348
