### ISSUE TITLE
Detected some kind of bi-directional dependency while trying to discover and plan a missing service registration. Examining types: System.Text.Json.JsonSerializerOptions

### ISSUE THREAD

**Issue by pawelklimczyk** [JasperFx/wolverine#673]
I have a strange issue when incorporating _StackExchangeRedis_ and _Wolverine_. I used newest nuget packages.

I tried both "SystemTextJsonSerializer" and "NewtonsoftSerializer".
Unfortunately the bug still occurs. 

**Repro steps below**

_Program.cs_

```
public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        var mvcBuilder = builder.Services.AddMvc();
        builder.Services.AddTransient<SampleService>();

        //builder.Services.AddTransient<IRedisClient, TestRedisClient>();
        //builder.Services.AddSingleton<ISerializer, NewtonsoftSerializer>();
        //builder.Services.AddTransient<JsonSerializerOptions>();
        //builder.Services.AddSingleton<ISerializer, NewtonsoftSerializer>();
        //builder.Services.AddSingleton<IRedisClient, RedisClient>();
        //builder.Services.AddSingleton<IRedisConnectionPoolManager, RedisConnectionPoolManager>();
        //builder.Services.AddSingleton((provider) =>
        //{
        //    return provider.GetRequiredService<IRedisClient>().GetDefaultDatabase();
        //});
        
        builder.Services.AddStackExchangeRedisExtensions<SystemTextJsonSerializer>(new RedisConfiguration());
        //builder.Services.AddStackExchangeRedisExtensions<NewtonsoftSerializer>(new RedisConfiguration());

        builder.Host.UseWolverine(options =>
        {
            options.Discovery.IncludeAssembly(typeof(Program).Assembly);
        });


        var app = builder.Build();

        app.UseHttpsRedirection();
        app.UseAuthorization();
        app.MapControllers();

        app.Run();
    }
}
```

_project.csproj_

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
		<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
		<PackageReference Include="StackExchange.Redis" Version="2.7.10" />
		<PackageReference Include="StackExchange.Redis.Extensions.AspNetCore" Version="10.0.2" />
		<PackageReference Include="StackExchange.Redis.Extensions.Core" Version="10.0.2" />
		<PackageReference Include="StackExchange.Redis.Extensions.Newtonsoft" Version="10.0.2" />
		<PackageReference Include="StackExchange.Redis.Extensions.System.Text.Json" Version="10.0.2" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />
		<PackageReference Include="WolverineFx" Version="1.13.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
		<PackageReference Include="WolverineFx.FluentValidation" Version="1.13.1" />
	</ItemGroup>
</Project>
```

**Screenshots**
![obraz](https://github.com/JasperFx/wolverine/assets/1084668/c5d387f8-37c0-44f8-9107-81c1de67d283)

**Comment by jeremydmiller** [comment]
@pawelklimczyk That exception message from Lamar should be telling you what the dependency problem is and how it gets there. Can you post in the full stack trace maybe?

**Comment by pawelklimczyk** [comment]
@jeremydmiller 
```
   at Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.addMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.ResolveFamily(Type serviceType)
   at Lamar.ServiceGraph.FindDefault(Type serviceType)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass41_0.<couldBuild>b__0(ParameterInfo p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Lamar.IoC.Instances.ConstructorInstance.couldBuild(ConstructorInfo ctor, ServiceGraph services)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass42_0.<DetermineConstructor>b__1(ConstructorInfo x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Lamar.IoC.Instances.ConstructorInstance.DetermineConstructor(ServiceGraph services, String& message)
   at Lamar.ServiceGraph.CouldBuild(Type concreteType, String& message)
   at Lamar.ConcreteFamilyPolicy.Build(Type type, ServiceGraph serviceGraph)
   at Lamar.ServiceGraph.<>c__DisplayClass66_0.<TryToCreateMissingFamily>b__1(IFamilyPolicy x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at JasperFx.Core.EnumerableExtensions.FirstValue[TItem,TReturn](IEnumerable`1 enumerable, Func`2 func)
   at Lamar.ServiceGraph.TryToCreateMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.addMissingFamily(Type serviceType)
   at Lamar.ServiceGraph.ResolveFamily(Type serviceType)
   at Lamar.ServiceGraph.FindDefault(Type serviceType)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass41_0.<couldBuild>b__0(ParameterInfo p)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at Lamar.IoC.Instances.ConstructorInstance.couldBuild(ConstructorInfo ctor, ServiceGraph services)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass42_0.<DetermineConstructor>b__1(ConstructorInfo x)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Lamar.IoC.Instances.ConstructorInstance.DetermineConstructor(ServiceGraph services, String& message)
   at Lamar.IoC.Instances.ConstructorInstance.createPlan(ServiceGraph services)
   at Lamar.IoC.Instances.Instance.CreatePlan(ServiceGraph services)
   at Lamar.ServiceGraph.planResolutionStrategies()
   at Lamar.ServiceGraph.buildOutMissingResolvers()
   at Lamar.ServiceGraph.Initialize()
   at Lamar.IoC.Scope..ctor(IServiceCollection services)
   at Lamar.Container..ctor(IServiceCollection services)
   at Lamar.Microsoft.DependencyInjection.LamarServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at WolverineAndRedis.Program.Main(String[] args) in c:\Projects\wolverine-playground\Gmtl.Playground.Wolverine\WolverineAndRedis\Program.cs:line 37

```

**Comment by jeremydmiller** [comment]
@pawelklimczyk Okay, how about the exception message? I put some energy into Lamar being able to tell you exactly what the bi-directional dependency was:-)

**Comment by pawelklimczyk** [comment]
First of all, thank you for maintaining such a powerful project. I try to incorporate Wolverine in one of my business-project. Right now i'm testing how to adapt it :)

The error is it's on the screenshot :P

`Detected some kind of bi-directional dependency while trying to discover and plan a missing service registration. Examining types: System.Text.Json.JsonSerializerOptions`


Basically adding this line `builder.Services.AddStackExchangeRedisExtensions<SystemTextJsonSerializer>(new RedisConfiguration());` crashes Lamar. 


My suspicion is one of the consturctors in `JsonSerializerOptions (System.Text.Json)` which takes `JsonSerializerOptions` as a parameter. It might end-up in loop-loop?!....

**Comment by jeremydmiller** [comment]
@pawelklimczyk It's exactly what you already said. Just add a service registration to `JsonSerializerOptions` and you should be good to go. But note, this **had absolutely nothing to do with Wolverine** and you should open a bug for the stack exchange team to make their registration extensions smart enough to add default registrations.

**Comment by pawelklimczyk** [comment]
This is what helped 

`services.AddSingleton<ISerializer>((provider) => new NewtonsoftSerializer());`

@jeremydmiller  thanks!
