### ISSUE TITLE
Inability to use sessions with saga in ASB

### ISSUE THREAD

**Issue by kirill-gerasimenko-da** [JasperFx/wolverine#686]
**Describe the bug**
Unexpected behavior (exceptions and hanging message) in saga message processing in ASB transport with FIFO queues.

**To Reproduce**

https://github.com/kirill-gerasimenko-da/sagawolverine - this has a reproduce code. 

1. Create a FIFO queue in Azure Service Bus (session support enabled)
2. Send message to create new Saga
2.1 Start SagaHost, then uncomment and run the first block in MessageSource/Program.cs
2.2 The output in SagaHost is the following (even though there's an exception - the saga is created in the database successfully)

```
fail: Wolverine.AzureServiceBus.Internal.AzureServiceBusSessionListener[0]
      Error while trying to retry Envelope #018cff63-db9a-4b92-9f2f-056f1e2ad962/CorrelationId=59c9afd9-3305-48a6-9e41-30e911633aaa from MessageSource to asb://queue/kir-fifo
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Wolverine.AzureServiceBus.Internal.SessionSpecificListener.<>c.<.ctor>b__9_0(AzureServiceBusEnvelope e, CancellationToken _) in /home/runner/work/wolverine/wolverine/src/Transports/Azure/Wolverine.AzureServiceBus/Internal/SessionSpecificListener.cs:line 151
         at Wolverine.Util.Dataflow.LambdaItemHandler`1.ExecuteAsync(T message, CancellationToken cancellation)
         at Wolverine.Util.Dataflow.RetryBlock`1.PostAsync(T message)
fail: Wolverine.AzureServiceBus.Internal.AzureServiceBusSessionListener[0]
      Error while trying to retry Envelope #018cff63-db9a-4b92-9f2f-056f1e2ad962/CorrelationId=59c9afd9-3305-48a6-9e41-30e911633aaa (StartSagaMessage) from MessageSource to asb://queue/kir-fifo
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Wolverine.AzureServiceBus.Internal.SessionSpecificListener.<>c.<.ctor>b__9_0(AzureServiceBusEnvelope e, CancellationToken _) in /home/runner/work/wolverine/wolverine/src/Transports/Azure/Wolverine.AzureServiceBus/Internal/SessionSpecificListener.cs:line 151
         at Wolverine.Util.Dataflow.LambdaItemHandler`1.ExecuteAsync(T message, CancellationToken cancellation)
         at Wolverine.Util.Dataflow.RetryBlock`1.executeAsync(Item item)
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (9ms) [Parameters=[@p0='?' (DbType = Guid), @p1='?', @p2='?'], CommandType='Text', CommandTimeout='30']
      INSERT INTO "Saga" ("Id", "Email", "Username")
      VALUES (@p0, @p1, @p2);
info: Contracts.StartSagaMessage[104]
      Successfully processed message Contracts.StartSagaMessage#018cff63-db9a-4b92-9f2f-056f1e2ad962 from asb://queue/kir-fifo

```

2.3 the message is **still** can be found in Service bus (so saga was created, but the message was not removed from the queue?)

```
{"id":"dc626099-2996-4c88-8796-9763974f6a19","username":"Kirill"}
```

3. Send message to update the Saga
3.1 Don't stop the SagaHost
3.2 Comment the first block and uncomment and run the second block in MessageSource/Program.cs
3.3 There will be no output in SagaHost, but the new message will be available in the Service Bus
3.4 Once you restart SagaHost you will see a lot of exceptions popping up
  -- some of them will be regarding the PK failure in the database for the saga persistence
  -- a little bit later the transport will be latched with messages like this
```
fail: Wolverine.Persistence.Durability.DurableSendingAgent[203]
      Sending agent for asb://queue/kir-fifo is latched
fail: Wolverine.Persistence.Durability.DurableSendingAgent[0]
      Failure trying to send a message batch to asb://queue/kir-fifo
      System.InvalidOperationException: The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value. Reference:1fc88254-b8f7-4711-946b-2efbb1567123, TrackingId:7c1eb8b3000002da00001c8165a1a4f6_G4S1_B18S2, Timestamp:2024-01-12T20:46:24
      For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
         at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(AmqpMessage batchMessage, TimeSpan timeout, CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__24_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
         at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
         at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendAsync(IReadOnlyCollection`1 messages, CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(IEnumerable`1 messages, CancellationToken cancellationToken)
         at Wolverine.AzureServiceBus.Internal.AzureServiceBusSenderProtocol.SendBatchAsync(ISenderCallback callback, OutgoingMessageBatch batch) in /home/runner/work/wolverine/wolverine/src/Transports/Azure/Wolverine.AzureServiceBus/Internal/AzureServiceBusSenderProtocol.cs:line 52
```

**Expected behavior**
- When creating new saga - no NRE should be thrown, and if Saga is persisted in the database then the message should be removed from the Service Bus.
- You should not need to restart the saga host process if there's an error, it still has to consume other messages
- You should be able to send updates to the saga successfully, leading to the new saga state persisting in the database and message removed from the Service Bus

**Comment by kirill-gerasimenko-da** [comment]
Using not FIFO queue and removing session support from the code - makes the code work as expected.

**Comment by jeremydmiller** [comment]
I think this is completely related to your other issue.
