### ISSUE TITLE
Possible Regression bug in Marten 7.0-beta 5

### ISSUE THREAD

**Issue by flew2bits** [JasperFx/wolverine#718]
The `Include` functionality in Marten 7 beta 5 breaks functionality that works in 6.4.

Given the following:

```csharp
public record DocumentA(Guid Id, string DetailA);
public record DocumentB(Guid Id, string DetailB);
```

in Marten 7b5, the following throws an exception.

```csharp
DocumentB? docB = null;
var docA = session.Query<DocumentA>().Include<DocumentB>(a => a.Id, b => docB = b).SingleOrDefault(a => a.id = THEID);
```

The exception is
```
      System.NotImplementedException: The method or operation is not implemented.
         at Marten.Linq.Members.IdMember.Marten.Linq.Members.IQueryableMember.get_LocatorForIncludedDocumentId()
         at Marten.Linq.Includes.IdInIncludedDocumentIdentifierFilter.Apply(ICommandBuilder builder)
         at Marten.Linq.SqlGeneration.SelectorStatement.configure(ICommandBuilder sql)
         at Marten.Linq.SqlGeneration.Statement.Apply(ICommandBuilder builder)
         at Marten.Linq.SqlGeneration.Statement.Apply(ICommandBuilder builder)
         at Marten.Linq.QueryHandlers.OneResultHandler`1.ConfigureCommand(ICommandBuilder builder, IMartenSession session)
         at Marten.Linq.Includes.IncludeQueryHandler`1.ConfigureCommand(ICommandBuilder builder, IMartenSession session)
         at Marten.Util.CommandExtensions.BuildCommand(IMartenSession session, IQueryHandler handler)
         at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
         at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
         at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
         at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
         at Marten.Linq.MartenLinqQueryProvider.ExecuteHandlerAsync[T](IQueryHandler`1 handler, CancellationToken token)
         at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, SingleValueMode valueMode)
         at JasperFx.Core.Exceptions.ExceptionTransformExtensions.TransformAndThrow(IEnumerable`1 transforms, Exception ex)
         at JasperFx.Core.Exceptions.ExceptionTransforms.TransformAndThrow(Exception ex)
         at Marten.Exceptions.MartenExceptionTransformer.WrapAndThrow(Exception exception)
         at Marten.Linq.MartenLinqQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken token, SingleValueMode valueMode)
         at Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\flew2\RiderProjects\RegressionRepro\RegressionRepro\Program.cs:line 56
```

However, this works fine in Marten 6.4.1.

Here's a single file repro that demonstrates the problem.

https://gist.github.com/flew2bits/c89bec4cd5a893f63b8f6af96c200611

**Comment by flew2bits** [comment]
Sorry. wrong project. I'll repost this in Marten.
