### ISSUE TITLE
Orleans 8 breaks using Wolverine 2 Alpha-1

### ISSUE THREAD

**Issue by dodyg** [JasperFx/wolverine#729]
**Describe the bug**

Orleans version 7 works just fine with Wolverine. When I updated my Orleans references to 8.00, I got the following errors

```
    <PackageReference Include="Microsoft.Orleans.Client" Version="8.0.0" />
    <PackageReference Include="Microsoft.Orleans.Runtime" Version="8.0.0" />
```

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Lamar.IoC.LamarMissingRegistrationException: Unknown service registration 'System.Object' of Microsoft.AspNetCore.Connections.IConnectionListenerFactory
   at Lamar.IoC.Scope.GetInstance(Type serviceType, String name)
   at Lamar.IoC.Scope.GetRequiredKeyedService(Type serviceType, Object serviceKey)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService[T](IServiceProvider provider, Object serviceKey)
   at Orleans.Runtime.Messaging.SiloConnectionListener..ctor(IServiceProvider serviceProvider, IOptions`1 connectionOptions, IOptions`1 siloConnectionOptions, MessageCenter messageCenter, IOptions`1 endpointOptions, ILocalSiloDetails localSiloDetails, ConnectionManager connectionManager, ConnectionCommon connectionShared, ProbeRequestMonitor probeRequestMonitor, ConnectionPreambleHelper connectionPreambleHelper) in /_/src/Orleans.Runtime/Networking/SiloConnectionListener.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)   at System.Activator.CreateInstance(Type type, Object[] args)
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Frames.InjectedServiceField.ToVariableExpression(LambdaDefinition definition)
   at JasperFx.CodeGeneration.Expressions.LambdaDefinition.ExpressionFor(Variable variable)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Lamar.IoC.Frames.ListAssignmentFrame`1.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Instances.FuncResolverDefinition.BuildResolver()
   at Lamar.IoC.Instances.GeneratedInstance.BuildFuncResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
   at Lamar.ServiceGraph.FindResolver(Type serviceType)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo..ctor(ILocalSiloDetails siloDetails, IServiceProvider services) in /_/src/Orleans.Runtime/Silo/Silo.cs:line 171
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)   at System.Activator.CreateInstance(Type type, Object[] args)
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass27_0.<quickResolve>b__0(CtorArg x)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Frames.InjectedServiceField.ToVariableExpression(LambdaDefinition definition)
   at JasperFx.CodeGeneration.Expressions.LambdaDefinition.ExpressionFor(Variable variable)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Lamar.IoC.Frames.ListAssignmentFrame`1.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Instances.FuncResolverDefinition.BuildResolver()
   at Lamar.IoC.Instances.GeneratedInstance.BuildFuncResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
   at Lamar.ServiceGraph.FindResolver(Type serviceType)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in F:\GitHub\tahayyuz\src\BIAS.Web\Program.cs:line 214
   at Program.<Main>(String[] args)
```

**Comment by jeremydmiller** [comment]
@dodyg I won't be able to solve this without a reproduction step. **Something** in your codebase seems to be doing something strange with `Microsoft.AspNetCore.Connections.IConnectionListenerFactory`. There's really nothing actionable for me to do otherwise.

**Comment by dodyg** [comment]
Thanks for checking it out. Let me write a test project.

**Comment by krmiteva** [comment]
I have the same issue, after upgrading to Orleans 8.1.0 and WolverineFx 2.15.0 I got Unknown service registration 'System.Object' of Microsoft.AspNetCore.Connections.IConnectionListenerFactory

**Comment by BrianVallelunga** [comment]
Not to hijack your issue, but I'd be interested in hearing how you're integrating the two frameworks. We've been eyeing Orleans for a specific use case.

**Comment by dodyg** [comment]
This issue is fixed in Wolverine 3+
