### ISSUE TITLE
Marten / Wolverine crashes after update to V7.1 / V2.0

### ISSUE THREAD

**Issue by AdvantBeiten** [JasperFx/wolverine#765]
After upading to the latest versions of Marten / Wolvering, the system crashed at app.Run.

I deleted all gernerated code and drop and re-created the database. So there is no old data / code to cause trouble.

Any ideas? 
Thanks!

System.ArgumentOutOfRangeException: The CurrentRevision member has to be of type int (Parameter 'value')
   at Marten.Storage.Metadata.MetadataColumn`1.set_Member(MemberInfo value)
   at Marten.Schema.VersionAttribute.Modify(DocumentMapping mapping, MemberInfo member)
   at Marten.Schema.DocumentMapping.<>c__DisplayClass113_0.<applyAnyMartenAttributes>b__9(MartenAttribute att)
   at JasperFx.Core.Reflection.ReflectionExtensions.ForAttribute[T](MemberInfo provider, Action`1 action)
   at Marten.Schema.DocumentMapping.<applyAnyMartenAttributes>b__113_2(PropertyInfo prop)
   at JasperFx.Core.EnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Marten.Schema.DocumentMapping.applyAnyMartenAttributes(Type documentType)
   at Marten.Schema.DocumentMapping..ctor(Type documentType, StoreOptions storeOptions)
   at Marten.Schema.DocumentMapping`1..ctor(StoreOptions storeOptions)
   at Marten.DocumentMappingBuilder`1.Build(StoreOptions options)
   at Marten.Storage.StorageFeatures.Build(Type type, StoreOptions options)
   at Marten.Storage.StorageFeatures.MappingFor(Type documentType)
   at Marten.Storage.StorageFeatures.FindMapping(Type documentType)
   at Marten.Storage.StorageFeatures.BuildAllMappings()
   at Marten.StoreOptions.ApplyConfiguration()
   at Marten.DocumentStore..ctor(StoreOptions options)
   at Marten.MartenServiceCollectionExtensions.<>c.<AddMarten>b__7_1(IServiceProvider s)
   at Lamar.IoC.Resolvers.SingletonLambdaResolver`2.Build(Scope scope)
   at Lamar.IoC.Resolvers.SingletonResolver`1.Resolve(Scope scope)
   at Lamar.IoC.Instances.LambdaInstance`2.<ToResolver>b__14_0(Scope scope)
   at Lamar.ServiceGraph.<>c__DisplayClass58_0.<FindResolver>b__0(Scope s)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Wolverine.Marten.WolverineOptionsMartenExtensions.<>c__DisplayClass0_0.<IntegrateWithWolverine>b__0(IServiceProvider s)
   at Lamar.IoC.Resolvers.SingletonLambdaResolver`2.Build(Scope scope)
   at Lamar.IoC.Resolvers.SingletonResolver`1.Resolve(Scope scope)
   at Lamar.IoC.Instances.LambdaInstance`2.Resolve(Scope scope)
   at Lamar.IoC.Instances.Instance.QuickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass27_0.<quickResolve>b__0(CtorArg x)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Enumerables.ListInstance`1.<>c__DisplayClass11_0.<QuickResolve>b__0(Instance x)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at Lamar.IoC.Enumerables.ListInstance`1.QuickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass27_0.<quickResolve>b__0(CtorArg x)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Frames.InjectedServiceField.ToVariableExpression(LambdaDefinition definition)
   at JasperFx.CodeGeneration.Expressions.LambdaDefinition.ExpressionFor(Variable variable)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Lamar.IoC.Frames.ListAssignmentFrame`1.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Instances.FuncResolverDefinition.BuildResolver()
   at Lamar.IoC.Instances.GeneratedInstance.BuildFuncResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
   at Lamar.ServiceGraph.FindResolver(Type serviceType)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in D:\Atlas3000\Atlas3000.WebApi\Program.cs:line 145

**Comment by jeremydmiller** [comment]
Yeah, one way or another, it's an invalid usage of the `[Version]` attribute. Track that down first.

**Comment by AdvantBeiten** [comment]
Thanks! That did the trick. I used a long (which worked in V6), but now it has be be int.
