### ISSUE TITLE
FailureActions.AndPauseProcessing(TimeSpan) doesn't seem to be working correctly

### ISSUE THREAD

**Issue by robertdusek** [JasperFx/wolverine#782]
`FailureActions.AndPauseProcessing(TimeSpan)` doesn't seem to be working correctly.

My setup looks like this

```
options.LocalQueueFor<ThisMeansTrouble>().Sequential();
options.OnException<Exception>()
    .Requeue().AndPauseProcessing(30.Seconds());
```

But my log output shows the message being reprocessed immediately before it's eventually dead-lettered:

```
16:25:36 fail: Repro.ThisMeansTrouble[105]
      Failed to process message Repro.ThisMeansTrouble#018e62e7-b65a-4853-b0f0-c46c04f5d457 from local://repro.thismeanstrouble/
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Repro.UnreliableHandler.Handle(ThisMeansTrouble message) in /Users/robert.dusek/Desktop/Repro/UnreliableHandler.cs:line 9
         at Internal.Generated.WolverineHandlers.ThisMeansTroubleHandler986978479.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
16:25:36 info: Wolverine.Runtime.WolverineRuntime[0]
      Requeue for message 018e62e7-b65a-4853-b0f0-c46c04f5d457 of message type Repro.ThisMeansTrouble
16:25:36 fail: Repro.ThisMeansTrouble[105]
      Failed to process message Repro.ThisMeansTrouble#018e62e7-b65a-4853-b0f0-c46c04f5d457 from local://repro.thismeanstrouble/
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Repro.UnreliableHandler.Handle(ThisMeansTrouble message) in /Users/robert.dusek/Desktop/Repro/UnreliableHandler.cs:line 9
         at Internal.Generated.WolverineHandlers.ThisMeansTroubleHandler986978479.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
16:25:36 fail: Wolverine.Runtime.RemoteInvocation.FailureAcknowledgementHandler[0]
      Received failure acknowledgement on reply for message 018e62e7-b65a-4853-b0f0-c46c04f5d457 from service Repro with message 'Moved message 018e62e7-b65a-4853-b0f0-c46c04f5d457 to the Error Queue.
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Repro.UnreliableHandler.Handle(ThisMeansTrouble message) in /Users/robert.dusek/Desktop/Repro/UnreliableHandler.cs:line 9
         at Internal.Generated.WolverineHandlers.ThisMeansTroubleHandler986978479.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)'
16:25:36 info: Wolverine.Transports.Local.DurableLocalQueue[0]
      Pausing message listening at local://repro.thismeanstrouble/
16:25:36 fail: Wolverine.Runtime.WolverineRuntime[108]
      Envelope Envelope #018e62e7-b65a-4853-b0f0-c46c04f5d457/CorrelationId=83bad262b7a9da89a6da85972c41672f (ThisMeansTrouble) from Repro to local://repro.thismeanstrouble/ was moved to the error queue
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Repro.UnreliableHandler.Handle(ThisMeansTrouble message) in /Users/robert.dusek/Desktop/Repro/UnreliableHandler.cs:line 9
         at Internal.Generated.WolverineHandlers.ThisMeansTroubleHandler986978479.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation)
```

Wolverine 2.1.2 & Marten 7.4.0

**Comment by jeremydmiller** [comment]
Before we call this a bug, what's the full setup you have for error handling? The tests for this functionality are happily passing right now. Are you sure some other error policy isn't kicking in first?

**Comment by robertdusek** [comment]
There's no other error policies configured, here's my whole Wolverine setup:
```c#
builder.Host.UseWolverine(options =>
{
    options.LocalQueueFor<ThisMeansTrouble>().Sequential();
    options.OnException<Exception>()
        .Requeue().AndPauseProcessing(30.Seconds());

    
    options.Policies.AutoApplyTransactions();
    options.Policies.UseDurableLocalQueues();
    options.Policies.UseDurableOutboxOnAllSendingEndpoints();
});
```

**Comment by jeremydmiller** [comment]
There was a test for this using Rabbit MQ, but the mechanics are different for local queues. I've got a failing test now

**Comment by jeremydmiller** [comment]
Race condition. Should be pause, then requeue after the listener is paused.

**Comment by jeremydmiller** [comment]
Not *just* a race condition

**Comment by jeremydmiller** [comment]
Got it. Brought to light some other internal flaws too. Good times. Fix coming in 2.2.0. 

@robertdusek Thanks for your patience with these things!

**Comment by robertdusek** [comment]
@jeremydmiller 
Thanks for taking a look at this. Unfortunately I'm still seeing (different) errors after updating to Marten 7.6 and Wolverine 2.2.1.

I call the handler that throws:
```
16:51:45 fail: Repro.ThisMeansTrouble[105]
      Failed to process message Repro.ThisMeansTrouble#018ebfb2-1db5-4d6c-8536-a8e2dab1c872 from local://repro.thismeanstrouble/
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Repro.UnreliableHandler.Handle(ThisMeansTrouble message, ILogger`1 logger) in /Users/robert.dusek/Desktop/Repro/UnreliableHandler.cs:line 10
         at Internal.Generated.WolverineHandlers.ThisMeansTroubleHandler986978479.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 164
```

The queue is paused and the message is requeued, but Wolverine detects it as a duplicate message:
```
16:51:45 info: Wolverine.Transports.Local.DurableLocalQueue[0]
      Pausing message listening at local://repro.thismeanstrouble/
16:51:45 info: Wolverine.Runtime.WolverineRuntime[0]
      Requeue for message 018ebfb2-1db5-4d6c-8536-a8e2dab1c872 of message type Repro.ThisMeansTrouble
16:51:45 fail: Wolverine.Runtime.WorkerQueues.DurableReceiver[0]
      Duplicate incoming envelope detected
      Wolverine.Persistence.Durability.DuplicateIncomingEnvelopeException: Duplicate incoming envelope with message id 018ebfb2-1db5-4d6c-8536-a8e2dab1c872
         at Wolverine.RDBMS.MessageDatabase`1.StoreIncomingAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/MessageDatabase.Incoming.cs:line 78
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.receiveOneAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 275
16:51:45 fail: Wolverine.Runtime.WolverineRuntime[0]
      Error while trying to retry Envelope #018ebfb2-1db5-4d6c-8536-a8e2dab1c872/CorrelationId=2d1abc3e4cf7433cc9341846f4597ec4 (ThisMeansTrouble) from Repro to local://repro.thismeanstrouble/
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.<>c.<.ctor>b__15_2(Envelope env, CancellationToken _) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 73
         at Wolverine.Util.Dataflow.LambdaItemHandler`1.ExecuteAsync(T message, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Util/Dataflow/RetryBlock.cs:line 23
         at Wolverine.Util.Dataflow.RetryBlock`1.PostAsync(T message) in /home/runner/work/wolverine/wolverine/src/Wolverine/Util/Dataflow/RetryBlock.cs:line 94
```

The queue is restarted and the message is reprocessed, the exception is thrown and the queue pauses again:
```
16:51:45 info: Wolverine.Runtime.Agents.NodeAgentController[0]
      Successfully started agent wolverinedb://default/ on Node 2
16:51:45 info: Wolverine.Runtime.WolverineRuntime[0]
      Successfully started agent wolverinedb://default/ on node 2
16:51:50 info: Wolverine.RDBMS.DurabilityAgent[0]
      Issuing a command to recover 1 incoming messages from the inbox to destination local://repro.thismeanstrouble/
16:51:50 warn: Repro.UnreliableHandler[0]
      Handler called
16:51:50 fail: Repro.ThisMeansTrouble[105]
      Failed to process message Repro.ThisMeansTrouble#018ebfb2-1db5-4d6c-8536-a8e2dab1c872 from local://repro.thismeanstrouble/
      System.Exception: Exception of type 'System.Exception' was thrown.
         at Repro.UnreliableHandler.Handle(ThisMeansTrouble message, ILogger`1 logger) in /Users/robert.dusek/Desktop/Repro/UnreliableHandler.cs:line 10
         at Internal.Generated.WolverineHandlers.ThisMeansTroubleHandler986978479.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.ExecuteAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 164
16:51:50 info: Wolverine.Transports.Local.DurableLocalQueue[0]
      Pausing message listening at local://repro.thismeanstrouble/
16:51:50 info: Wolverine.Runtime.WolverineRuntime[0]
      Requeue for message 018ebfb2-1db5-4d6c-8536-a8e2dab1c872 of message type Repro.ThisMeansTrouble
```

Then immediately the following entries start to repeat:
```
16:51:50 fail: Wolverine.Runtime.WorkerQueues.DurableReceiver[0]
      Unexpected failure
      System.ArgumentOutOfRangeException: Erroneous persistence of an incoming envelope to 'any' node (Parameter 'Envelope')
         at Wolverine.RDBMS.MessageDatabase`1.StoreIncomingAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/MessageDatabase.Incoming.cs:line 53
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.receiveOneAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 275
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.executeWithRetriesAsync(Func`1 action) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 303
16:51:50 info: Wolverine.RDBMS.DurabilityAgent[206]
      Recovered 1 incoming envelopes from storage
16:51:50 info: Wolverine.RDBMS.DurabilityAgent[0]
      Successfully recovered 1 messages from the inbox for listener local://repro.thismeanstrouble/
16:51:50 fail: Wolverine.Runtime.WorkerQueues.DurableReceiver[0]
      Unexpected failure
      System.ArgumentOutOfRangeException: Erroneous persistence of an incoming envelope to 'any' node (Parameter 'Envelope')
         at Wolverine.RDBMS.MessageDatabase`1.StoreIncomingAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/MessageDatabase.Incoming.cs:line 53
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.receiveOneAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 275
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.executeWithRetriesAsync(Func`1 action) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 303
16:51:50 fail: Wolverine.Runtime.WorkerQueues.DurableReceiver[0]
      Unexpected failure
      System.ArgumentOutOfRangeException: Erroneous persistence of an incoming envelope to 'any' node (Parameter 'Envelope')
         at Wolverine.RDBMS.MessageDatabase`1.StoreIncomingAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/MessageDatabase.Incoming.cs:line 53
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.receiveOneAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 275
         at Wolverine.Runtime.WorkerQueues.DurableReceiver.executeWithRetriesAsync(Func`1 action) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 303
```

Thanks again for all your help with this!

**Comment by jeremydmiller** [comment]
Hey guys, if you put a comment on a closed issue, there's a less than zero chance I'll ever see it. Open a new issue or reopen this one.
