### ISSUE TITLE
Balanced durability mode doesn't work with RabbitMQ

### ISSUE THREAD

**Issue by ArkadiuszChorian** [JasperFx/wolverine#788]
**Describe the bug**
When using RabbitMQ with default `DurabilityMode = Balanced` app is unable to start.
All Wolverine and Marten packages are latest as for now: Wolverine 2.1.2 and Marten 7.4.0

There are two other issues strictly related to that and giving necessary context:
#645 and #746 

**Firstly** this exception is thrown:
```
fail: Wolverine.Runtime.Agents.StartLocalAgentProcessing[0]
      Invocation failed!
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'serializer')
         at Wolverine.Runtime.Routing.MessageRoute..ctor(IMessageSerializer serializer, ISendingAgent sender, IEnumerable`1 rules, IReplyTracker replyTracker)
         at Wolverine.Runtime.Routing.MessageRoute..ctor(Type messageType, Endpoint endpoint, IReplyTracker replies)
         at Wolverine.Runtime.Routing.MessageRouterBase`1.<>c__DisplayClass2_0.<.ctor>b__1(Endpoint endpoint)
         at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
         at Wolverine.Runtime.Routing.MessageRouterBase`1..ctor(WolverineRuntime runtime)
         at Wolverine.Runtime.Routing.MessageRouter`1..ctor(WolverineRuntime runtime, IEnumerable`1 routes)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
         at System.Activator.CreateInstance(Type type, Object[] args)
         at JasperFx.Core.Reflection.TypeExtensions.CloseAndBuildAs[T](Type openType, Object ctorArgument1, Object ctorArgument2, Type[] parameterTypes)
         at Wolverine.Runtime.WolverineRuntime.RoutingFor(Type messageType)
         at Wolverine.Runtime.MessageBus.PublishAsync[T](T message, DeliveryOptions options)
         at Wolverine.Runtime.MessageContext.EnqueueCascadingAsync(Object message)
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Agents.InternalMessageHandler`1.HandleAsync(MessageContext context, CancellationToken cancellation)
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation)
```
Which is the same as described in #645 

**Secondly** there is workaround for this which is setting:
`options.Durability.Mode = DurabilityMode.Solo;`

I use it temporarily in solo mode to proceed with development but unfortunately it won't be acceptable on prod environment in my project.

This workaround is taken from #746 

**Thirdly** and actually really strange:
It is possible to run it without above workaround.
You just need to run your app twice.
In the first run you'll get exception described above.
When you run again everything will be fine.

In the first run there is a log:
`Found no other existing nodes, deciding to assume leadership in node 1`
and right after that above exception is thrown.

In the second run these logs are printed:
```
Starting agents for Node da6a8488-5f77-48b1-b481-5f55a9b67653 with assigned node id 2
Found no elected leader on node startup, requesting node 1 to be the new leader
Wolverine assigned node id for envelope persistence is 2
```
and app runs properly.

**To reproduce**
Use what is described in #746

**Comment by jeremydmiller** [comment]
@ArkadiuszChorian Hey, the previous issue was closed because I **cannot reproduce the issue locally at all**. Without reproduction steps that actually cause the issue, I can't merely "use what is described in #746"

**Comment by jeremydmiller** [comment]
Only guess I have at this point is that this might help: https://github.com/JasperFx/wolverine/issues/660

**Comment by ArkadiuszChorian** [comment]
@jeremydmiller thanks, I see. We'll make repro repo soon.

**Comment by jeremydmiller** [comment]
I'm making some guesses at the root cause and pushing a PR to the next release. Just re-open if 2.2.0 doesn't help please

**Comment by ArkadiuszChorian** [comment]
@jeremydmiller thanks for making an attempt to resolve the issue. Hope it will help, so waiting for 2.2.0.

Despite that we were able to setup quite polished repro repo for this:
https://github.com/ArkadiuszChorian/wolverine-balanced-durability-issue

Many thanks @nmapx and @doctorspider42 for help with reproducing the issue and setting up that repo.

**Comment by ArkadiuszChorian** [comment]
Hi again @jeremydmiller. We tested 2.2.0 on our [repro repo](https://github.com/ArkadiuszChorian/wolverine-balanced-durability-issue-788) and unfortunately #791 didn't help - Balanced mode still not working.

**Comment by ArkadiuszChorian** [comment]
@jeremydmiller here is reopened issue #818
