### ISSUE TITLE
Balanced durability mode doesn't work with RabbitMQ (attempt 2)

### ISSUE THREAD

**Issue by ArkadiuszChorian** [JasperFx/wolverine#818]
This issue is direct continuation of #788.

Verified wolverine v2.2.0 which have included PR #791 aim to fix this but it still doesn't work on [repro repo](https://github.com/ArkadiuszChorian/wolverine-balanced-durability-issue-788).

I would appreciate further investigation on this @jeremydmiller

**Comment by jeremydmiller** [comment]
@ArkadiuszChorian I'm sorry, but your make script didn't work for me, and I just don't have enough bandwidth to trouble shoot whatever is going on with your docker setup. You'd neglected to mention -- unless I completely missed that -- that your issue came from publishing an app to docker because this works all day long just running the process. 

I'll take one more shot at it if you can feed me the exact stack trace after Wolverine 2.4 hits later this evening with just a little more in the exception message that might explain what I'm guessing is a race condition of some sort.

And Wolverine is a community OSS project that accepts pull requests, so feel free to dig in if you can. Or my bandwidth weirdly goes up if you engage w/ JasperFx Software.

**Comment by ArkadiuszChorian** [comment]
@jeremydmiller Unfortunately it's not the happy ending for my project but I understand your limited bandwidth. Despite that I'll try to follow up your last comment.

First of all
> your issue came from publishing an app to docker because this works all day long just running the process

That would be good clue but unfortunately it's not the case here. We prepared repro repo using `docker` and `make` only to automate whole setup for you but this issue is still present without docker (aka native development).

Now this part
> I'll take one more shot at it if you can feed me the exact stack trace after Wolverine 2.4 hits later this evening with just a little more in the exception message that might explain what I'm guessing is a race condition of some sort.

I updated Wolverine to 2.5 and below are the logs (app run without docker). Maybe it'll somehow trigger an idea in your mind.
```
info: Wolverine.Runtime.Agents.NodeAgentController[0]
      Starting agents for Node d9b91381-d801-48ef-a88e-51644065d494 with assigned node id 1
info: Wolverine.Runtime.Agents.NodeAgentController[0]
      Found no other existing nodes, deciding to assume leadership in node 1
fail: Wolverine.Runtime.WolverineRuntime[0]
      Failed to start the Wolverine messaging
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.ArgumentOutOfRangeException: Endpoint rabbitmq://exchange/test.exchange does not have an active sending agent. Message type: Wolverine.Runtime.Agents.TryAssumeLeadership (Parameter 'endpoint')
         at Wolverine.Runtime.Routing.MessageRoute..ctor(Type messageType, Endpoint endpoint, IReplyTracker replies) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRoute.cs:line 28
         at Wolverine.Runtime.Routing.MessageRouterBase`1.<>c__DisplayClass2_0.<.ctor>b__1(Endpoint endpoint) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRouterBase.cs:line 30
         at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
         at Wolverine.Runtime.Routing.MessageRouterBase`1..ctor(WolverineRuntime runtime) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRouterBase.cs:line 29
         at Wolverine.Runtime.Routing.MessageRouter`1..ctor(WolverineRuntime runtime, IEnumerable`1 routes) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRouter.cs:line 9
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
         at System.Activator.CreateInstance(Type type, Object[] args)
         at JasperFx.Core.Reflection.TypeExtensions.CloseAndBuildAs[T](Type openType, Object ctorArgument1, Object ctorArgument2, Type[] parameterTypes)
         at Wolverine.Runtime.WolverineRuntime.RoutingFor(Type messageType) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Routing.cs:line 97
         at Wolverine.Runtime.MessageBus.PublishAsync[T](T message, DeliveryOptions options) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/MessageBus.cs:line 154
         at Wolverine.Runtime.WolverineRuntime.startNodeAgentWorkflowAsync() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 180
         at Wolverine.Runtime.WolverineRuntime.startAgentsAsync() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 135
         at Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.HostService.cs:line 51
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.ArgumentOutOfRangeException: Endpoint rabbitmq://exchange/test.exchange does not have an active sending agent. Message type: Wolverine.Runtime.Agents.TryAssumeLeadership (Parameter 'endpoint')
         at Wolverine.Runtime.Routing.MessageRoute..ctor(Type messageType, Endpoint endpoint, IReplyTracker replies) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRoute.cs:line 28
         at Wolverine.Runtime.Routing.MessageRouterBase`1.<>c__DisplayClass2_0.<.ctor>b__1(Endpoint endpoint) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRouterBase.cs:line 30
         at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToArray()
         at Wolverine.Runtime.Routing.MessageRouterBase`1..ctor(WolverineRuntime runtime) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRouterBase.cs:line 29
         at Wolverine.Runtime.Routing.MessageRouter`1..ctor(WolverineRuntime runtime, IEnumerable`1 routes) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRouter.cs:line 9
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
         at System.Activator.CreateInstance(Type type, Object[] args)
         at JasperFx.Core.Reflection.TypeExtensions.CloseAndBuildAs[T](Type openType, Object ctorArgument1, Object ctorArgument2, Type[] parameterTypes)
         at Wolverine.Runtime.WolverineRuntime.RoutingFor(Type messageType) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Routing.cs:line 97
         at Wolverine.Runtime.MessageBus.PublishAsync[T](T message, DeliveryOptions options) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/MessageBus.cs:line 154
         at Wolverine.Runtime.WolverineRuntime.startNodeAgentWorkflowAsync() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 180
         at Wolverine.Runtime.WolverineRuntime.startAgentsAsync() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 135
         at Wolverine.Runtime.WolverineRuntime.StartAsync(CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.HostService.cs:line 51
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
fail: Wolverine.Runtime.Agents.IAgentCommand[0]
      Invocation failed!
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'Npgsql.PoolingDataSource'.
         at Npgsql.ThrowHelper.ThrowObjectDisposedException(String objectName)
         at Npgsql.NpgsqlDataSource.CheckDisposed()
         at Npgsql.PoolingDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataSource.OpenDbConnectionAsync(CancellationToken cancellationToken)
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/Polling/DatabaseOperationBatch.cs:line 61
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
fail: Wolverine.Runtime.Agents.IAgentCommand[0]
      Inline invocation of Wolverine.RDBMS.Polling.DatabaseOperationBatch failed
      System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'Npgsql.PoolingDataSource'.
         at Npgsql.ThrowHelper.ThrowObjectDisposedException(String objectName)
         at Npgsql.NpgsqlDataSource.CheckDisposed()
         at Npgsql.PoolingDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataSource.OpenConnectionAsync(CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataSource.OpenDbConnectionAsync(CancellationToken cancellationToken)
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/Polling/DatabaseOperationBatch.cs:line 61
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 212
         at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 93
```

**Comment by doctorspider42** [comment]
After lots of debugging, I found a line that was most likely causing this problem. After making that change, the error is no longer present, and the app starts, and runs, as expected.
The solution was starting Node Agent Workflow AFTER starting Messaging Transports, so the Agent is already initialized, and we don't get the null exception. 

Please don't hesitate to check the PR:
https://github.com/JasperFx/wolverine/pull/952

I've also updated our repro repo, so now it works with the Wolverine's docker-compose, and doesn't require any make scripts. 
To reproduce the error, simply run docker-compose from Wolverine, as you'd normally do, and then start the repro app normally.
https://github.com/ArkadiuszChorian/wolverine-balanced-durability-issue-788

@jeremydmiller @nkosi23
