### ISSUE TITLE
 Errors encountered while persisting messages to SqlServer for durable local queues

### ISSUE THREAD

**Issue by lokeshkumarbalu** [JasperFx/wolverine#829]
I'm in the process of configuring durable local queues using EFCore. Initially, I attempted to set up the system by running the sample example in the repository. However, I encountered errors during the execution.

```
fail: Wolverine.Runtime.Agents.IAgentCommand[0]
      Invocation failed!
      Wolverine.RDBMS.Polling.DatabaseBatchCommandException: Database operation batch failure:
1. Wolverine.RDBMS.Durability.PersistNodeRecord

       ---> System.InvalidOperationException: BeginExecuteReader: CommandText property has not been initialized
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in .\wolverine\src\Persistence\Wolverine.RDBMS\Polling\DatabaseOperationBatch.cs:line 69
         --- End of inner exception stack trace ---
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in .\wolverine\src\Persistence\Wolverine.RDBMS\Polling\DatabaseOperationBatch.cs:line 79
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in .\wolverine\src\Persistence\Wolverine.RDBMS\Polling\DatabaseOperationBatch.cs:line 91
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in .\wolverine\src\Wolverine\Runtime\Agents\AgentCommandHandler.cs:line 36
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in .\wolverine\src\Wolverine\Runtime\Handlers\Executor.cs:line 202


fail: Wolverine.Runtime.Agents.IAgentCommand[0]
      Inline invocation of Wolverine.RDBMS.Polling.DatabaseOperationBatch failed
      Wolverine.RDBMS.Polling.DatabaseBatchCommandException: Database operation batch failure:
1. Wolverine.RDBMS.Durability.PersistNodeRecord

       ---> System.InvalidOperationException: BeginExecuteReader: CommandText property has not been initialized
         at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in .\wolverine\src\Persistence\Wolverine.RDBMS\Polling\DatabaseOperationBatch.cs:line 69
         --- End of inner exception stack trace ---
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in .\wolverine\src\Persistence\Wolverine.RDBMS\Polling\DatabaseOperationBatch.cs:line 79
         at Wolverine.RDBMS.Polling.DatabaseOperationBatch.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in .\wolverine\src\Persistence\Wolverine.RDBMS\Polling\DatabaseOperationBatch.cs:line 91
         at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in .\wolverine\src\Wolverine\Runtime\Agents\AgentCommandHandler.cs:line 36
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in .\wolverine\src\Wolverine\Runtime\Handlers\Executor.cs:line 202
         at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in .\wolverine\src\Wolverine\Runtime\Handlers\Executor.cs:line 212
         at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in .\wolverine\src\Wolverine\Runtime\Handlers\Executor.cs:line 93

```

**To Reproduce**
1. Open "wolverine.sln" and execute the EFCoreSample project.
2. After launching the application, give it a few seconds to initialize, and you'll observe the errors appearing shortly after that.

**Expected behavior**
1. Launch "wolverine.sln" and execute the EFCoreSample project.
2. Upon application startup, allow a few moments for initialization. No errors should occur, and the addition of items to the "sample.items" table should proceed smoothly.

**Desktop**
 - OS: Windows Server
 - Browser [Chrome]
 - Version:  2022

**Comment by jeremydmiller** [comment]
@lokeshkumarbalu Thanks for the heads up. It's an issue that was addressed in the Postgresql side of things that gets used a lot more, but missed on the Sql Server side. The fix will be in the next Wolverine release.

**Comment by lokeshkumarbalu** [comment]
@jeremydmiller Many thanks for the update, cheers!
