### ISSUE TITLE
Leadership Election: Leader not elected after crash

### ISSUE THREAD

**Issue by davidkvc** [JasperFx/wolverine#897]
**Describe the bug**
When running in Balanced mode, when the app crashes, new leader is not elected. Ideally the app should gracefully shut down and cleanup it's node record in the DB. But we can't guarantee that always to happen in prod.

**To Reproduce**
1. Start the application
2. Kill the application (no graceful shutdown) **before it manages to handle leadership election**, e.g. within 2 seconds
3. Start the application again

I'm getting these error logs:

```
System.TimeoutException: Timed out waiting for expected acknowledgement for original message 018f935e-8690-45b1-b9fa-f0e47c3cf014 of type Wolverine.Runtime.Agents.TryAssumeLeadership
   at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId)
   at Wolverine.Runtime.WolverineRuntime.InvokeAsync(Guid nodeId, IAgentCommand command) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 58
   at Wolverine.Runtime.Agents.TryAssumeLeadership.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/TryAssumeLeadership.cs:line 24
   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 212
   at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 93
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 129
   at Wolverine.Runtime.WolverineRuntime.executeHealthChecks() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 200
Wolverine.Runtime.Agents.IAgentCommand: Error: Invocation failed!

System.TimeoutException: Timed out waiting for expected acknowledgement for original message 018f935f-9820-4040-8265-c61f4bf24f0b of type Wolverine.Runtime.Agents.TryAssumeLeadership
   at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId)
   at Wolverine.Runtime.WolverineRuntime.InvokeAsync(Guid nodeId, IAgentCommand command) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 58
   at Wolverine.Runtime.Agents.TryAssumeLeadership.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/TryAssumeLeadership.cs:line 24
   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
Wolverine.Runtime.Agents.IAgentCommand: Error: Inline invocation of TryAssumeLeadership { CurrentLeaderId = , CandidateId = b3b8e0d4-58e4-4ce2-8f1b-19ad039bb635 } failed

System.TimeoutException: Timed out waiting for expected acknowledgement for original message 018f935f-9820-4040-8265-c61f4bf24f0b of type Wolverine.Runtime.Agents.TryAssumeLeadership
   at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId)
   at Wolverine.Runtime.WolverineRuntime.InvokeAsync(Guid nodeId, IAgentCommand command) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 58
   at Wolverine.Runtime.Agents.TryAssumeLeadership.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/TryAssumeLeadership.cs:line 24
   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 212
   at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 93
Wolverine.Runtime.WolverineRuntime: Error: Error trying to perform agent health checks
```

wolverine_nodes (only last one is actually running):

```
                  id                  | node_number | description |                        uri                        |            started            |         health_check          | capabilities
--------------------------------------+-------------+-------------+---------------------------------------------------+-------------------------------+-------------------------------+--------------
 b3b8e0d4-58e4-4ce2-8f1b-19ad039bb635 |           2 | DAVID       | dbcontrol://b3b8e0d4-58e4-4ce2-8f1b-19ad039bb635/ | 2024-05-19 22:30:17.010025+00 | 2024-05-19 22:31:00.076288+00 | {}
 e27471b6-8dfe-43ef-a521-a02d743d1c71 |           3 | DAVID       | dbcontrol://e27471b6-8dfe-43ef-a521-a02d743d1c71/ | 2024-05-19 22:31:15.121514+00 | 2024-05-19 22:34:58.271995+00 | {}
 e38b1643-cd70-43ce-8c96-5a998dce6258 |           4 | DAVID       | dbcontrol://e38b1643-cd70-43ce-8c96-5a998dce6258/ | 2024-05-19 23:45:27.392171+00 | 2024-05-19 23:45:27.392171+00 | {}
 b7191d83-95d5-4f17-85bf-9a52bc0044bb |           5 | DAVID       | dbcontrol://b7191d83-95d5-4f17-85bf-9a52bc0044bb/ | 2024-05-19 23:45:49.84426+00  | 2024-05-19 23:46:02.891215+00 | {}
 7ad7bc91-6b57-444f-b5cc-10393010ff8a |           6 | DAVID       | dbcontrol://7ad7bc91-6b57-444f-b5cc-10393010ff8a/ | 2024-05-19 23:46:40.640568+00 | 2024-05-19 23:46:40.640568+00 | {}
 16fed387-a4ad-4c8a-b57f-12ff5b6862dd |           7 | DAVID       | dbcontrol://16fed387-a4ad-4c8a-b57f-12ff5b6862dd/ | 2024-05-19 23:47:02.830686+00 | 2024-05-20 00:19:56.683784+00 | {}
```

wolverine_node_assignments:

\<empty>

**Expected behavior**
Leader is always elected from active nodes

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Configuration:
```csharp
var builder = WebApplication.CreateBuilder(args);

// other config ...

var connectionString = builder.Configuration.GetConnectionString("db")!;
builder.Host.UseWolverine(opts =>
{
    opts.PersistMessagesWithPostgresql(connectionString);
    opts.UseEntityFrameworkCoreTransactions();
    opts.Policies.UseDurableLocalQueues();
});
builder.Host.UseResourceSetupOnStartup();
```

Packages:
```
<PackageReference Include="WolverineFx" Version="2.8.1" />
<PackageReference Include="WolverineFx.EntityFrameworkCore" Version="2.8.1" />
<PackageReference Include="WolverineFx.Postgresql" Version="2.8.1" />
```

I have digged through some code related to leader election and it seems that [only leader is able to remove stale nodes](https://github.com/JasperFx/wolverine/blob/cfeeeb16adefe29f246ca1e7beb483cfcd39af1b/src/Wolverine/Runtime/Agents/NodeAgentController.HeartBeat.cs#L34) which doesn't work here. Also we should only consider other **non-stale** nodes [here](https://github.com/JasperFx/wolverine/blob/cfeeeb16adefe29f246ca1e7beb483cfcd39af1b/src/Wolverine/Runtime/Agents/NodeAgentController.HeartBeat.cs#L80C23-L80C80)? That algorithm picks a stale node for me and it eventually times out because that node will never exist again.

**Comment by jeremydmiller** [comment]
@davidkvc I'm pushing something today to "close" this just in the sense of having any given node be able to eject any stale notes on startup. The health check time is a minute by default, so you might wanna speed that up.

Longer term, I want to build in *something* so you can kickstart the leader no matter what. And/or introduce an HTTP transport option for gossip between nodes to be able to do the leadership work much faster
