### ISSUE TITLE
DROP Statement fails in Wolverine.SqlServer

### ISSUE THREAD

**Issue by MaxDotSouth** [JasperFx/wolverine#927]
I introduced PersistMessagesWithSqlServer() into my code.
While the first run did work as expected (tables, procedures created),
the second run of the code produced an exception at application startup:

Microsoft.Data.SqlClient.SqlException: 'Cannot drop type 'wolverine.EnvelopeIdList' because it is being referenced by object 'uspDeleteIncomingEnvelopes'. There may be other objects that reference this type.'

(SQLServer does not allow dropping the table because the stored procedure does have a reference on it)

The same behaviour is shown in version 2.11.1 and 2.12.2.

If i manually drop all procedures the application starts and runs as expected.

Full exception trace:

Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot drop type 'wolverine.EnvelopeIdList' because it is being referenced by object 'uspDeleteIncomingEnvelopes'. There may be other objects that reference this type.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__210_1(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Comment by jeremydmiller** [comment]
Okay, but that would only run if you were trying to tear down the storage

**Comment by MaxDotSouth** [comment]
Weasel schema migration detects a difference in SchemaMigration.DetermineAsync()
Still can't find the reason for it, but will close this issue as it is nothing to bother for Wolverine.SqlServer.
Thank you!

**Comment by MaxDotSouth** [comment]
see comment above
