### ISSUE TITLE
Generated Code using reserved 'lock' keyword

### ISSUE THREAD

**Issue by walero-moon** [JasperFx/wolverine#934]
**Describe the bug**
Code Generated by Wolverine can use a reserved keyword in its handlers, throwing an exception when code is generated during runtime.

Especifically, it seems that if the return type of a method is named like a reserved keyword, the compiled code uses that keyword as a variable. I came across this issue when using a record `Lock`, being used as a return type for `Load` and `LoadAsync`.

Example code below:
```cs
using Microsoft.AspNetCore.Mvc;
using Wolverine.Http;

namespace Operto.Nova.Access.Adapters.Compatibility.Actions;

public record Lock {
    public required string Id;
}

public record ReservedKeywordBugResponse(string Id)
    : AcceptResponse($"/lock/{Id}");

public static class ReservedKeywordBugEndpoint
{
    public static Lock Load(
        string id
    )
    {
        
        return new Lock { Id = id };
    }

    [WolverinePut("/lock/{lockId}")]
    [ProducesResponseType(typeof(string), 400)]
    public static ReservedKeywordBugResponse Handle(
        string lockId
    )
    {
        var response = new ReservedKeywordBugResponse(lockId);

        return response;
    }
}
```

The generated code, generated with `dotnet run -- codegen write`:
```cs
// <auto-generated/>
#pragma warning disable
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: PUT_lock_lockId
    public class PUT_lock_lockId : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _wolverineHttpOptions;

        public PUT_lock_lockId(Wolverine.Http.WolverineHttpOptions wolverineHttpOptions) : base(wolverineHttpOptions)
        {
            _wolverineHttpOptions = wolverineHttpOptions;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var lockId = (string)httpContext.GetRouteValue("lockId");
            string id = httpContext.Request.Query["id"].FirstOrDefault();
            var lock = Operto.Nova.Access.Adapters.Compatibility.Actions.ReservedKeywordBugEndpoint.Load(id);
            
            // The actual HTTP request handler execution
            var reservedKeywordBugResponse_response = Operto.Nova.Access.Adapters.Compatibility.Actions.ReservedKeywordBugEndpoint.Handle(lockId);

            // This response type customizes the HTTP response
            ApplyHttpAware(reservedKeywordBugResponse_response, httpContext);
            // Writing the response body to JSON because this was the first 'return variable' in the method signature
            await WriteJsonAsync(httpContext, reservedKeywordBugResponse_response);
        }

    }

    // END: PUT_lock_lockId
    
    
}
```

The exception thrown when the code is generated during runtime when sending a request to the endpoint:
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: Compilation failures!

CS1002: ; expected
CS1003: Syntax error, '(' expected
CS1525: Invalid expression term '='
CS1026: ) expected
CS0103: The name 'var' does not exist in the current context

Code:

// <auto-generated/>
#pragma warning disable
using Microsoft.AspNetCore.Routing;
using System;
using System.Linq;
using Wolverine.Http;

namespace Internal.Generated.WolverineHandlers
{
    // START: PUT_lock_lockId
    public class PUT_lock_lockId : Wolverine.Http.HttpHandler
    {
        private readonly Wolverine.Http.WolverineHttpOptions _wolverineHttpOptions;

        public PUT_lock_lockId(Wolverine.Http.WolverineHttpOptions wolverineHttpOptions) : base(wolverineHttpOptions)
        {
            _wolverineHttpOptions = wolverineHttpOptions;
        }



        public override async System.Threading.Tasks.Task Handle(Microsoft.AspNetCore.Http.HttpContext httpContext)
        {
            var lockId = (string)httpContext.GetRouteValue("lockId");
            string id = httpContext.Request.Query["id"].FirstOrDefault();
            var lock = Operto.Nova.Access.Adapters.Compatibility.Actions.ReservedKeywordBugEndpoint.Load(id);
            
            // The actual HTTP request handler execution
            var reservedKeywordBugResponse_response = Operto.Nova.Access.Adapters.Compatibility.Actions.ReservedKeywordBugEndpoint.Handle(lockId);

            // This response type customizes the HTTP response
            ApplyHttpAware(reservedKeywordBugResponse_response, httpContext);
            // Writing the response body to JSON because this was the first 'return variable' in the method signature
            await WriteJsonAsync(httpContext, reservedKeywordBugResponse_response);
        }

    }

    // END: PUT_lock_lockId
    
    
}


   at JasperFx.RuntimeCompiler.AssemblyGenerator.Generate(String code)
   at JasperFx.RuntimeCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
   at JasperFx.RuntimeCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
   at Wolverine.Http.HttpChain.<BuildEndpoint>b__112_3() in /home/runner/work/wolverine/wolverine/src/Http/Wolverine.Http/HttpChain.EndpointBuilder.cs:line 62
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Wolverine.Http.HttpChain.<>c__DisplayClass112_0.<BuildEndpoint>b__4(HttpContext c) in /home/runner/work/wolverine/wolverine/src/Http/Wolverine.Http/HttpChain.EndpointBuilder.cs:line 66
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by jeremydmiller** [comment]
Just not anything that's ever been anticipated. Not a big fix though

**Comment by jeremydmiller** [comment]
@walero-moon On it today

**Comment by jeremydmiller** [comment]
Closed by https://github.com/JasperFx/wolverine/pull/939
