### ISSUE TITLE
Error when resuming from a paused local queue (part 2)

### ISSUE THREAD

**Issue by evan-at-tusksoft** [JasperFx/wolverine#966]
This bug appears to be related to #782 and #826. I am using Wolverine 2.15.2 with durable local queues.

I have a message handler with the following exception policy:
```cs
chain.OnException<MyCustomException>()
    .Requeue().AndPauseProcessing(15.Minutes())
    .Then.MoveToErrorQueue().And(SendFailureMessage);
```

When the handler is invoked and throws an instance of `MyCustomException`, Wolverine correctly persists the message to the local queue and tries again after 15 minutes. When the message is retried and the handler throws a second time, it is again requeued, but immediately starts throwing this exception in an endless loop:
```
[15:54:54 ERR] Unexpected failure
System.ArgumentOutOfRangeException: Erroneous persistence of an incoming envelope to 'any' node (Parameter 'Envelope')
   at Wolverine.RDBMS.MessageDatabase`1.StoreIncomingAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/MessageDatabase.Incoming.cs:line 52
   at Wolverine.Runtime.WorkerQueues.DurableReceiver.deferOneAsync(Envelope envelope) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 274
   at Wolverine.Runtime.WorkerQueues.DurableReceiver.executeWithRetriesAsync(Func`1 action) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WorkerQueues/DurableReceiver.cs:line 302
```

Please let me know if I can provide more information. Thanks in advance!

**Comment by jeremydmiller** [comment]
@evan-at-tusksoft I could certainly be wrong, but I think I'm pushing the fix for this one now

**Comment by evan-at-tusksoft** [comment]
@jeremydmiller Unfortunately, it did not fix it. After updating to Wolverine 2.16.0, the exception is still thrown. The messages in the `wolverine_incoming_envelopes` table still have an `owner_id` value of `0`. Here's a screenshot of the location where the exception is being thrown:
![image](https://github.com/user-attachments/assets/ee87902d-c803-4f99-8cb4-b51efadb5db0)

Interestingly, I'm now seeing an additional exception in the logs:
```
[08:50:07 ERR] Error trying to reevaluate agent assignments for 'wolverinedb' agents
System.InvalidOperationException: There are no active nodes
   at Wolverine.Runtime.Agents.AssignmentGrid.DistributeEvenly(String scheme) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AssignmentGrid.cs:line 141
   at Wolverine.RDBMS.DurabilityAgentFamily.EvaluateAssignmentsAsync(AssignmentGrid assignments) in /home/runner/work/wolverine/wolverine/src/Persistence/Wolverine.RDBMS/DurabilityAgentFamily.cs:line 70
   at Wolverine.Runtime.Agents.NodeAgentController.EvaluateAssignmentsAsync(IReadOnlyList`1 nodes) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/NodeAgentController.EvaluateAssignments.cs:line 25
```
