### ISSUE TITLE
Error timed out TryAssumeLeadership

### ISSUE THREAD

**Issue by krmiteva** [JasperFx/wolverine#968]
I was using WolverineFx v 1.7.0 in .net 7 application with Marten library IntegrateWithWolverine option. I had no issues with leadership election so far. Then I've updated WolverineFx to v 2.12.2 and after deployment using Kubernetes suddenly all three pods started failing with 

Timed out waiting for expected acknowledgement for original message 0190966f-8fcd-41d6-97d5-e33717b26ebc of type Wolverine.Runtime.Agents.TryAssumeLeadership.
 at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Routing/MessageRoute.cs:line 147
   at Wolverine.Runtime.WolverineRuntime.InvokeAsync(Guid nodeId, IAgentCommand command) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 64
   at Wolverine.Runtime.Agents.TryAssumeLeadership.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/TryAssumeLeadership.cs:line 32
   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 60
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 222
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 222
   at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 114
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 137
   at Wolverine.Runtime.WolverineRuntime.executeHealthChecks() in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 217

I've tried restarting the pods one by one, but it didn't help. Not sure why I get this error and how to fix it. Can someone please help?

**Update**
It seems that two of the nodes are trying to elect the third node, but the third node is trying to elect node that does not exist any more. If I restart the third node it tries to elect one of the other two nodes, but they are still trying to elect node that does not exist any more, because I just restarted it.

**Comment by jeremydmiller** [comment]
I've tried repeatedly to address this in more recent versions of Wolverine to make wolverine delete dormant / obsolete nodes in the node table.

The quick workaround is to get into your nodes table that Wolverine creates and wipe out any obsolete nodes. This should absolutely *not* be necessary any longer, but ¯\_(ツ)_/¯

this can happen if wolverine nodes are being shut down without getting a chance to clean up after itself. Recent Wolveirne is **supposed** to wipe out the dormant nodes on startup.

There's some longer term work in flight to hopefully address this by using HTTP communication between nodes.

Starting and stopping nodes in rapid sequence is also probably making this worse:(

**Comment by krmiteva** [comment]
Thank you for the reply, I've looked at the wolverine_nodes table and everything is okay in there, there is no obsolete nodes and are up to date, but it's seems like some type of cache in var candidate = _tracker.OtherNodes().MinBy(x => x.AssignedNodeId); in NodeAgentController where it keeps pooling not existing node.

**Comment by elexisvenator** [comment]
Think I hit this as well just now in prod:

<details>
  <summary>Expand for stacktrace</summary>
  ```log
Timed out waiting for expected acknowledgement for original message 0190ba56-0aaf-40f6-a4b2-8000c93a14b5 of type Wolverine.Runtime.Agents.TryAssumeLeadership
   at Wolverine.Runtime.Routing.MessageRoute.InvokeAsync[T](Object message, MessageBus bus, CancellationToken cancellation, Nullable`1 timeout, String tenantId)
   at Wolverine.Runtime.WolverineRuntime.InvokeAsync(Guid nodeId, IAgentCommand command) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/WolverineRuntime.Agents.cs:line 58
   at Wolverine.Runtime.Agents.TryAssumeLeadership.ExecuteAsync(IWolverineRuntime runtime, CancellationToken cancellationToken) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/TryAssumeLeadership.cs:line 24
   at Wolverine.Runtime.Agents.AgentCommandHandler.HandleAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Agents/AgentCommandHandler.cs:line 36
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 202
   at Wolverine.Runtime.Handlers.Executor.InvokeAsync(MessageContext context, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 212
   at Wolverine.Runtime.Handlers.Executor.InvokeInlineAsync(Envelope envelope, CancellationToken cancellation) in /home/runner/work/wolverine/wolverine/src/Wolverine/Runtime/Handlers/Executor.cs:line 93
  ```
 
</details>

One thing that was different was in my case was that the nodes table was empty! Not sure how this was the case, and the app appeared functional. Forcing a redeployment of the application containers silenced the errors and I could see the expected records in the node table after.

**Comment by krmiteva** [comment]
In my case I've managed to fixed it by scaling down all pods and then scale up again. Because we have a zero downtime deployment I didn't want to do that on prod but that was the only solution.

**Comment by elexisvenator** [comment]
Happened again on Friday, this really spams the error logs :/ Cause still seems to be an issue with nodes terminating/starting up in an unhealthy manner. Forcing a new deployment/recycling nodes still solves the problem until it appears again.

**Comment by elexisvenator** [comment]
And again in multiple regions today :(

**Comment by jeremydmiller** [comment]
@krmiteva @elexisvenator I'm on this this morning finally. For right now, I'm doing a mild change where @krmiteva suggested, and anecdotally, the tests for leadership failover are behaving much better -- so that's a big positive!

Right now, I'm feeling like this is my programming waterloo. Wolverine 3.0 is going to introduce an Http transport specifically for an optimized way to do inter-node chatter. I'm hoping that will be beneficial. But for now, the somewhat improved leadership failover will go into 2.15.3 later today.

I think I'd like to consider a mild rewrite of this functionality for 3.0. Again.
