### ISSUE TITLE
Injecting IServiceProvider in handler fails

### ISSUE THREAD

**Issue by huesla** [JasperFx/wolverine#97]
Hi,
when trying to inject an IServiceProvider in a message handler, it fails at the code compilation step:

```
System.InvalidOperationException: Compilation failures!

CS0119: 'IServiceProvider' is a type, which is not valid in the given context
CS0119: 'IServiceProvider' is a type, which is not valid in the given context

Code:

// <auto-generated/>
      #pragma warning disable

      namespace Internal.Generated.WolverineHandlers
      {
          // START: MyCommandHandler2028426067
          public class MyCommandHandler2028426067 : Wolverine.Runtime.Handlers.MessageHandler
          {


              public override System.Threading.Tasks.Task HandleAsync(Wolverine.Runtime.MessageContext context, System.Threading.CancellationToken cancellation)
              {
                  var inline_serviceProvider = (System.IServiceProvider) ;
                  var myHandler = new MyHandler(inline_serviceProvider);
                  var myCommand = (MyCommand)context.Envelope.Message;
                  myHandler.Handle(myCommand);
                  return System.Threading.Tasks.Task.CompletedTask;
              }

          }

          // END: MyCommandHandler2028426067


      }


         at LamarCompiler.AssemblyGenerator.Generate(String code)
         at LamarCompiler.AssemblyGenerator.Compile(GeneratedAssembly generatedAssembly, IServiceVariableSource services)
         at LamarCompiler.CodeFileExtensions.InitializeSynchronously(ICodeFile file, GenerationRules rules, ICodeFileCollection parent, IServiceProvider services)
         at Wolverine.Runtime.Handlers.HandlerGraph.HandlerFor(Type messageType)
         at Wolverine.Runtime.WolverineRuntime.Wolverine.Runtime.IExecutorFactory.BuildFor(Type messageType)
         at Wolverine.Runtime.HandlerPipeline.ExecutorFor(Type messageType)
         at Wolverine.Runtime.HandlerPipeline.InvokeNowAsync(Envelope envelope, CancellationToken cancellation)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Strangely enough when injecting a class that depends on IServiceProvider, it works, but only when this class is registered as singleton, not as transient.

**How to reproduce**
1. Start off with a default ASP.NET 6 project. Add a handler class that gets IServiceProvider injected in the constructor
2. Create a handler method that takes a message
3. Invoke ICommandBus.InvokeAsync(myMessage)

Is this expected behaviour of Wolverine/Lamar? Can IServiceProvider not be injected?

**Comment by jeremydmiller** [comment]
Definitely not expected behavior, but also not something I would have ever have thought to test either (obviously). It's not intended, idiomatic usage. What are you doing that btw? And thanks for the repro steps!

**Comment by huesla** [comment]
In our current use case, at the time at which the handler is called it is not yet known which instances are required from the IoC container. Due to this, we inject the IServiceProvider to retrieve the required instances during the processing of the message. May you have some input on how this use case can be handled with Wolverine? Thanks in advance!
